drop table t_threeboard;
CREATE TABLE `t_Threeboard` (
  `Id` bigint NOT NULL AUTO_INCREMENT COMMENT '主键Id',
  `Matchid` varchar(20) DEFAULT NULL,
  `S2p3` double DEFAULT NULL COMMENT 'Sp3',
  `S2p0` double DEFAULT NULL COMMENT 'Sp0',
  `S2k3` double DEFAULT NULL,
  `S2k0` double DEFAULT NULL,
  `One2p3` double DEFAULT NULL COMMENT 'Ep3',
  `One2p0` double DEFAULT NULL COMMENT 'Ep0',
  `One2k3` double DEFAULT NULL,
  `One2k0` double DEFAULT NULL,
  `Two2p3` double DEFAULT NULL COMMENT 'Ep3',
  `Two2p0` double DEFAULT NULL COMMENT 'Ep0',
  `Two2k3` double DEFAULT NULL,
  `Two2k0` double DEFAULT NULL,
  `Average12h2p3` double DEFAULT NULL COMMENT 'Ep3',
  `Average12h2p0` double DEFAULT NULL COMMENT 'Ep0',
  `Average12h2k3` double DEFAULT NULL,
  `Average12h2k0` double DEFAULT NULL,
  `S80p3` double DEFAULT NULL COMMENT 'Sp3',
  `S80p0` double DEFAULT NULL COMMENT 'Sp0',
  `S80k3` double DEFAULT NULL,
  `S80k0` double DEFAULT NULL,
  `One80p3` double DEFAULT NULL COMMENT 'Ep3',
  `One80p0` double DEFAULT NULL COMMENT 'Ep0',
  `One80k3` double DEFAULT NULL,
  `One80k0` double DEFAULT NULL,
  `Two80p3` double DEFAULT NULL COMMENT 'Ep3',
  `Two80p0` double DEFAULT NULL COMMENT 'Ep0',
  `Two80k3` double DEFAULT NULL,
  `Two80k0` double DEFAULT NULL,
  `Average12h80p3` double DEFAULT NULL COMMENT 'Ep3',
  `Average12h80p0` double DEFAULT NULL COMMENT 'Ep0',
  `Average12h80k3` double DEFAULT NULL,
  `Average12h80k0` double DEFAULT NULL,
  `S81p3` double DEFAULT NULL COMMENT 'Sp3',
  `S81p0` double DEFAULT NULL COMMENT 'Sp0',
  `S81k3` double DEFAULT NULL,
  `S81k0` double DEFAULT NULL,
  `One81p3` double DEFAULT NULL COMMENT 'Ep3',
  `One81p0` double DEFAULT NULL COMMENT 'Ep0',
  `One81k3` double DEFAULT NULL,
  `One81k0` double DEFAULT NULL,
  `Two81p3` double DEFAULT NULL COMMENT 'Ep3',
  `Two81p0` double DEFAULT NULL COMMENT 'Ep0',
  `Two81k3` double DEFAULT NULL,
  `Two81k0` double DEFAULT NULL,
  `Average12h81p3` double DEFAULT NULL COMMENT 'Ep3',
  `Average12h81p0` double DEFAULT NULL COMMENT 'Ep0',
  `Average12h81k3` double DEFAULT NULL,
  `Average12h81k0` double DEFAULT NULL,
  `S82p3` double DEFAULT NULL COMMENT 'Sp3',
  `S82p0` double DEFAULT NULL COMMENT 'Sp0',
  `S82k3` double DEFAULT NULL,
  `S82k0` double DEFAULT NULL,
  `One82p3` double DEFAULT NULL COMMENT 'Ep3',
  `One82p0` double DEFAULT NULL COMMENT 'Ep0',
  `One82k3` double DEFAULT NULL,
  `One82k0` double DEFAULT NULL,
  `Two82p3` double DEFAULT NULL COMMENT 'Ep3',
  `Two82p0` double DEFAULT NULL COMMENT 'Ep0',
  `Two82k3` double DEFAULT NULL,
  `Two82k0` double DEFAULT NULL,
  `Average12h82p3` double DEFAULT NULL COMMENT 'Ep3',
  `Average12h82p0` double DEFAULT NULL COMMENT 'Ep0',
  `Average12h82k3` double DEFAULT NULL,
  `Average12h82k0` double DEFAULT NULL,
  `S115p3` double DEFAULT NULL COMMENT 'Sp3',
  `S115p0` double DEFAULT NULL COMMENT 'Sp0',
  `S115k3` double DEFAULT NULL,
  `S115k0` double DEFAULT NULL,
  `One115p3` double DEFAULT NULL COMMENT 'Ep3',
  `One115p0` double DEFAULT NULL COMMENT 'Ep0',
  `One115k3` double DEFAULT NULL,
  `One115k0` double DEFAULT NULL,
  `Two115p3` double DEFAULT NULL COMMENT 'Ep3',
  `Two115p0` double DEFAULT NULL COMMENT 'Ep0',
  `Two115k3` double DEFAULT NULL,
  `Two115k0` double DEFAULT NULL,
  `Average12h115p3` double DEFAULT NULL COMMENT 'Ep3',
  `Average12h115p0` double DEFAULT NULL COMMENT 'Ep0',
  `Average12h115k3` double DEFAULT NULL,
  `Average12h115k0` double DEFAULT NULL,
  `S177p3` double DEFAULT NULL COMMENT 'Sp3',
  `S177p0` double DEFAULT NULL COMMENT 'Sp0',
  `S177k3` double DEFAULT NULL,
  `S177k0` double DEFAULT NULL,
  `One177p3` double DEFAULT NULL COMMENT 'Ep3',
  `One177p0` double DEFAULT NULL COMMENT 'Ep0',
  `One177k3` double DEFAULT NULL,
  `One177k0` double DEFAULT NULL,
  `Two177p3` double DEFAULT NULL COMMENT 'Ep3',
  `Two177p0` double DEFAULT NULL COMMENT 'Ep0',
  `Two177k3` double DEFAULT NULL,
  `Two177k0` double DEFAULT NULL,
  `Average12h177p3` double DEFAULT NULL COMMENT 'Ep3',
  `Average12h177p0` double DEFAULT NULL COMMENT 'Ep0',
  `Average12h177k3` double DEFAULT NULL,
  `Average12h177k0` double DEFAULT NULL,
  `S281p3` double DEFAULT NULL COMMENT 'Sp3',
  `S281p0` double DEFAULT NULL COMMENT 'Sp0',
  `S281k3` double DEFAULT NULL,
  `S281k0` double DEFAULT NULL,
  `One281p3` double DEFAULT NULL COMMENT 'Ep3',
  `One281p0` double DEFAULT NULL COMMENT 'Ep0',
  `One281k3` double DEFAULT NULL,
  `One281k0` double DEFAULT NULL,
  `Two281p3` double DEFAULT NULL COMMENT 'Ep3',
  `Two281p0` double DEFAULT NULL COMMENT 'Ep0',
  `Two281k3` double DEFAULT NULL,
  `Two281k0` double DEFAULT NULL,
  `Average12h281p3` double DEFAULT NULL COMMENT 'Ep3',
  `Average12h281p0` double DEFAULT NULL COMMENT 'Ep0',
  `Average12h281k3` double DEFAULT NULL,
  `Average12h281k0` double DEFAULT NULL, 
  `Createtime` datetime DEFAULT now() COMMENT '创建时间',
  `Updatetime` datetime DEFAULT now() COMMENT '更新时间',
  `Mark` varchar(20) DEFAULT NULL COMMENT '结果',
  PRIMARY KEY (`Id`),
  UNIQUE KEY `IDX_t_euro_his_MatchId` (`Matchid`),
  KEY `IDX_t_euro_his_CreateTime` (`Createtime`)
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8mb3 COMMENT='三木板';
