// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: clientinfo.proto

package com.ukelink.um.proto;

public final class Clientinfo {
  private Clientinfo() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface ClientInfoOrBuilder extends
      // @@protoc_insertion_point(interface_extends:com.ukelink.um.proto.ClientInfo)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>.com.ukelink.um.proto.ClientInfo.UserType userType = 1;</code>
     */
    int getUserTypeValue();
    /**
     * <code>.com.ukelink.um.proto.ClientInfo.UserType userType = 1;</code>
     */
    ClientInfo.UserType getUserType();

    /**
     * <code>.com.ukelink.um.proto.ClientInfo.UserValue userValue = 2;</code>
     */
    boolean hasUserValue();
    /**
     * <code>.com.ukelink.um.proto.ClientInfo.UserValue userValue = 2;</code>
     */
    ClientInfo.UserValue getUserValue();
    /**
     * <code>.com.ukelink.um.proto.ClientInfo.UserValue userValue = 2;</code>
     */
    ClientInfo.UserValueOrBuilder getUserValueOrBuilder();

    /**
     * <code>string client_id = 3;</code>
     */
    String getClientId();
    /**
     * <code>string client_id = 3;</code>
     */
    com.google.protobuf.ByteString
        getClientIdBytes();

    /**
     * <code>string deviceType = 4;</code>
     */
    String getDeviceType();
    /**
     * <code>string deviceType = 4;</code>
     */
    com.google.protobuf.ByteString
        getDeviceTypeBytes();
  }
  /**
   * Protobuf type {@code com.ukelink.um.proto.ClientInfo}
   */
  public  static final class ClientInfo extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:com.ukelink.um.proto.ClientInfo)
      ClientInfoOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use ClientInfo.newBuilder() to construct.
    private ClientInfo(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private ClientInfo() {
      userType_ = 0;
      clientId_ = "";
      deviceType_ = "";
    }

    @Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private ClientInfo(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {
              int rawValue = input.readEnum();

              userType_ = rawValue;
              break;
            }
            case 18: {
              UserValue.Builder subBuilder = null;
              if (userValue_ != null) {
                subBuilder = userValue_.toBuilder();
              }
              userValue_ = input.readMessage(UserValue.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(userValue_);
                userValue_ = subBuilder.buildPartial();
              }

              break;
            }
            case 26: {
              String s = input.readStringRequireUtf8();

              clientId_ = s;
              break;
            }
            case 34: {
              String s = input.readStringRequireUtf8();

              deviceType_ = s;
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return Clientinfo.internal_static_com_ukelink_um_proto_ClientInfo_descriptor;
    }

    @Override
    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return Clientinfo.internal_static_com_ukelink_um_proto_ClientInfo_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              ClientInfo.class, Builder.class);
    }

    /**
     * Protobuf enum {@code com.ukelink.um.proto.ClientInfo.UserType}
     */
    public enum UserType
        implements com.google.protobuf.ProtocolMessageEnum {
      /**
       * <code>error = 0;</code>
       */
      error(0),
      /**
       * <pre>
       *IM
       * </pre>
       *
       * <code>userId = 1;</code>
       */
      userId(1),
      /**
       * <code>sim = 2;</code>
       */
      sim(2),
      /**
       * <code>sip = 3;</code>
       */
      sip(3),
      /**
       * <code>groupId = 4;</code>
       */
      groupId(4),
      UNRECOGNIZED(-1),
      ;

      /**
       * <code>error = 0;</code>
       */
      public static final int error_VALUE = 0;
      /**
       * <pre>
       *IM
       * </pre>
       *
       * <code>userId = 1;</code>
       */
      public static final int userId_VALUE = 1;
      /**
       * <code>sim = 2;</code>
       */
      public static final int sim_VALUE = 2;
      /**
       * <code>sip = 3;</code>
       */
      public static final int sip_VALUE = 3;
      /**
       * <code>groupId = 4;</code>
       */
      public static final int groupId_VALUE = 4;


      public final int getNumber() {
        if (this == UNRECOGNIZED) {
          throw new IllegalArgumentException(
              "Can't get the number of an unknown enum value.");
        }
        return value;
      }

      /**
       * @deprecated Use {@link #forNumber(int)} instead.
       */
      @Deprecated
      public static UserType valueOf(int value) {
        return forNumber(value);
      }

      public static UserType forNumber(int value) {
        switch (value) {
          case 0: return error;
          case 1: return userId;
          case 2: return sim;
          case 3: return sip;
          case 4: return groupId;
          default: return null;
        }
      }

      public static com.google.protobuf.Internal.EnumLiteMap<UserType>
          internalGetValueMap() {
        return internalValueMap;
      }
      private static final com.google.protobuf.Internal.EnumLiteMap<
          UserType> internalValueMap =
            new com.google.protobuf.Internal.EnumLiteMap<UserType>() {
              public UserType findValueByNumber(int number) {
                return UserType.forNumber(number);
              }
            };

      public final com.google.protobuf.Descriptors.EnumValueDescriptor
          getValueDescriptor() {
        return getDescriptor().getValues().get(ordinal());
      }
      public final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptorForType() {
        return getDescriptor();
      }
      public static final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptor() {
        return ClientInfo.getDescriptor().getEnumTypes().get(0);
      }

      private static final UserType[] VALUES = values();

      public static UserType valueOf(
          com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
        if (desc.getType() != getDescriptor()) {
          throw new IllegalArgumentException(
            "EnumValueDescriptor is not for this type.");
        }
        if (desc.getIndex() == -1) {
          return UNRECOGNIZED;
        }
        return VALUES[desc.getIndex()];
      }

      private final int value;

      private UserType(int value) {
        this.value = value;
      }

      // @@protoc_insertion_point(enum_scope:com.ukelink.um.proto.ClientInfo.UserType)
    }

    public interface UserValueOrBuilder extends
        // @@protoc_insertion_point(interface_extends:com.ukelink.um.proto.ClientInfo.UserValue)
        com.google.protobuf.MessageOrBuilder {

      /**
       * <code>string number = 1;</code>
       */
      String getNumber();
      /**
       * <code>string number = 1;</code>
       */
      com.google.protobuf.ByteString
          getNumberBytes();

      /**
       * <code>int64 id = 2;</code>
       */
      long getId();
    }
    /**
     * Protobuf type {@code com.ukelink.um.proto.ClientInfo.UserValue}
     */
    public  static final class UserValue extends
        com.google.protobuf.GeneratedMessageV3 implements
        // @@protoc_insertion_point(message_implements:com.ukelink.um.proto.ClientInfo.UserValue)
        UserValueOrBuilder {
    private static final long serialVersionUID = 0L;
      // Use UserValue.newBuilder() to construct.
      private UserValue(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
        super(builder);
      }
      private UserValue() {
        number_ = "";
      }

      @Override
      public final com.google.protobuf.UnknownFieldSet
      getUnknownFields() {
        return this.unknownFields;
      }
      private UserValue(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        this();
        if (extensionRegistry == null) {
          throw new NullPointerException();
        }
        int mutable_bitField0_ = 0;
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
            com.google.protobuf.UnknownFieldSet.newBuilder();
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 10: {
                String s = input.readStringRequireUtf8();

                number_ = s;
                break;
              }
              case 16: {

                id_ = input.readInt64();
                break;
              }
              default: {
                if (!parseUnknownField(
                    input, unknownFields, extensionRegistry, tag)) {
                  done = true;
                }
                break;
              }
            }
          }
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(this);
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(
              e).setUnfinishedMessage(this);
        } finally {
          this.unknownFields = unknownFields.build();
          makeExtensionsImmutable();
        }
      }
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return Clientinfo.internal_static_com_ukelink_um_proto_ClientInfo_UserValue_descriptor;
      }

      @Override
      protected FieldAccessorTable
          internalGetFieldAccessorTable() {
        return Clientinfo.internal_static_com_ukelink_um_proto_ClientInfo_UserValue_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                UserValue.class, Builder.class);
      }

      public static final int NUMBER_FIELD_NUMBER = 1;
      private volatile Object number_;
      /**
       * <code>string number = 1;</code>
       */
      public String getNumber() {
        Object ref = number_;
        if (ref instanceof String) {
          return (String) ref;
        } else {
          com.google.protobuf.ByteString bs = 
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          number_ = s;
          return s;
        }
      }
      /**
       * <code>string number = 1;</code>
       */
      public com.google.protobuf.ByteString
          getNumberBytes() {
        Object ref = number_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          number_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }

      public static final int ID_FIELD_NUMBER = 2;
      private long id_;
      /**
       * <code>int64 id = 2;</code>
       */
      public long getId() {
        return id_;
      }

      private byte memoizedIsInitialized = -1;
      @Override
      public final boolean isInitialized() {
        byte isInitialized = memoizedIsInitialized;
        if (isInitialized == 1) return true;
        if (isInitialized == 0) return false;

        memoizedIsInitialized = 1;
        return true;
      }

      @Override
      public void writeTo(com.google.protobuf.CodedOutputStream output)
                          throws java.io.IOException {
        if (!getNumberBytes().isEmpty()) {
          com.google.protobuf.GeneratedMessageV3.writeString(output, 1, number_);
        }
        if (id_ != 0L) {
          output.writeInt64(2, id_);
        }
        unknownFields.writeTo(output);
      }

      @Override
      public int getSerializedSize() {
        int size = memoizedSize;
        if (size != -1) return size;

        size = 0;
        if (!getNumberBytes().isEmpty()) {
          size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, number_);
        }
        if (id_ != 0L) {
          size += com.google.protobuf.CodedOutputStream
            .computeInt64Size(2, id_);
        }
        size += unknownFields.getSerializedSize();
        memoizedSize = size;
        return size;
      }

      @Override
      public boolean equals(final Object obj) {
        if (obj == this) {
         return true;
        }
        if (!(obj instanceof UserValue)) {
          return super.equals(obj);
        }
        UserValue other = (UserValue) obj;

        if (!getNumber()
            .equals(other.getNumber())) return false;
        if (getId()
            != other.getId()) return false;
        if (!unknownFields.equals(other.unknownFields)) return false;
        return true;
      }

      @Override
      public int hashCode() {
        if (memoizedHashCode != 0) {
          return memoizedHashCode;
        }
        int hash = 41;
        hash = (19 * hash) + getDescriptor().hashCode();
        hash = (37 * hash) + NUMBER_FIELD_NUMBER;
        hash = (53 * hash) + getNumber().hashCode();
        hash = (37 * hash) + ID_FIELD_NUMBER;
        hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
            getId());
        hash = (29 * hash) + unknownFields.hashCode();
        memoizedHashCode = hash;
        return hash;
      }

      public static UserValue parseFrom(
          java.nio.ByteBuffer data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static UserValue parseFrom(
          java.nio.ByteBuffer data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static UserValue parseFrom(
          com.google.protobuf.ByteString data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static UserValue parseFrom(
          com.google.protobuf.ByteString data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static UserValue parseFrom(byte[] data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static UserValue parseFrom(
          byte[] data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static UserValue parseFrom(java.io.InputStream input)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input);
      }
      public static UserValue parseFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input, extensionRegistry);
      }
      public static UserValue parseDelimitedFrom(java.io.InputStream input)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseDelimitedWithIOException(PARSER, input);
      }
      public static UserValue parseDelimitedFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
      }
      public static UserValue parseFrom(
          com.google.protobuf.CodedInputStream input)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input);
      }
      public static UserValue parseFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input, extensionRegistry);
      }

      @Override
      public Builder newBuilderForType() { return newBuilder(); }
      public static Builder newBuilder() {
        return DEFAULT_INSTANCE.toBuilder();
      }
      public static Builder newBuilder(UserValue prototype) {
        return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
      }
      @Override
      public Builder toBuilder() {
        return this == DEFAULT_INSTANCE
            ? new Builder() : new Builder().mergeFrom(this);
      }

      @Override
      protected Builder newBuilderForType(
          BuilderParent parent) {
        Builder builder = new Builder(parent);
        return builder;
      }
      /**
       * Protobuf type {@code com.ukelink.um.proto.ClientInfo.UserValue}
       */
      public static final class Builder extends
          com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
          // @@protoc_insertion_point(builder_implements:com.ukelink.um.proto.ClientInfo.UserValue)
          UserValueOrBuilder {
        public static final com.google.protobuf.Descriptors.Descriptor
            getDescriptor() {
          return Clientinfo.internal_static_com_ukelink_um_proto_ClientInfo_UserValue_descriptor;
        }

        @Override
        protected FieldAccessorTable
            internalGetFieldAccessorTable() {
          return Clientinfo.internal_static_com_ukelink_um_proto_ClientInfo_UserValue_fieldAccessorTable
              .ensureFieldAccessorsInitialized(
                  UserValue.class, Builder.class);
        }

        // Construct using com.ukelink.um.proto.Clientinfo.ClientInfo.UserValue.newBuilder()
        private Builder() {
          maybeForceBuilderInitialization();
        }

        private Builder(
            BuilderParent parent) {
          super(parent);
          maybeForceBuilderInitialization();
        }
        private void maybeForceBuilderInitialization() {
          if (com.google.protobuf.GeneratedMessageV3
                  .alwaysUseFieldBuilders) {
          }
        }
        @Override
        public Builder clear() {
          super.clear();
          number_ = "";

          id_ = 0L;

          return this;
        }

        @Override
        public com.google.protobuf.Descriptors.Descriptor
            getDescriptorForType() {
          return Clientinfo.internal_static_com_ukelink_um_proto_ClientInfo_UserValue_descriptor;
        }

        @Override
        public UserValue getDefaultInstanceForType() {
          return UserValue.getDefaultInstance();
        }

        @Override
        public UserValue build() {
          UserValue result = buildPartial();
          if (!result.isInitialized()) {
            throw newUninitializedMessageException(result);
          }
          return result;
        }

        @Override
        public UserValue buildPartial() {
          UserValue result = new UserValue(this);
          result.number_ = number_;
          result.id_ = id_;
          onBuilt();
          return result;
        }

        @Override
        public Builder clone() {
          return super.clone();
        }
        @Override
        public Builder setField(
            com.google.protobuf.Descriptors.FieldDescriptor field,
            Object value) {
          return super.setField(field, value);
        }
        @Override
        public Builder clearField(
            com.google.protobuf.Descriptors.FieldDescriptor field) {
          return super.clearField(field);
        }
        @Override
        public Builder clearOneof(
            com.google.protobuf.Descriptors.OneofDescriptor oneof) {
          return super.clearOneof(oneof);
        }
        @Override
        public Builder setRepeatedField(
            com.google.protobuf.Descriptors.FieldDescriptor field,
            int index, Object value) {
          return super.setRepeatedField(field, index, value);
        }
        @Override
        public Builder addRepeatedField(
            com.google.protobuf.Descriptors.FieldDescriptor field,
            Object value) {
          return super.addRepeatedField(field, value);
        }
        @Override
        public Builder mergeFrom(com.google.protobuf.Message other) {
          if (other instanceof UserValue) {
            return mergeFrom((UserValue)other);
          } else {
            super.mergeFrom(other);
            return this;
          }
        }

        public Builder mergeFrom(UserValue other) {
          if (other == UserValue.getDefaultInstance()) return this;
          if (!other.getNumber().isEmpty()) {
            number_ = other.number_;
            onChanged();
          }
          if (other.getId() != 0L) {
            setId(other.getId());
          }
          this.mergeUnknownFields(other.unknownFields);
          onChanged();
          return this;
        }

        @Override
        public final boolean isInitialized() {
          return true;
        }

        @Override
        public Builder mergeFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
          UserValue parsedMessage = null;
          try {
            parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
          } catch (com.google.protobuf.InvalidProtocolBufferException e) {
            parsedMessage = (UserValue) e.getUnfinishedMessage();
            throw e.unwrapIOException();
          } finally {
            if (parsedMessage != null) {
              mergeFrom(parsedMessage);
            }
          }
          return this;
        }

        private Object number_ = "";
        /**
         * <code>string number = 1;</code>
         */
        public String getNumber() {
          Object ref = number_;
          if (!(ref instanceof String)) {
            com.google.protobuf.ByteString bs =
                (com.google.protobuf.ByteString) ref;
            String s = bs.toStringUtf8();
            number_ = s;
            return s;
          } else {
            return (String) ref;
          }
        }
        /**
         * <code>string number = 1;</code>
         */
        public com.google.protobuf.ByteString
            getNumberBytes() {
          Object ref = number_;
          if (ref instanceof String) {
            com.google.protobuf.ByteString b = 
                com.google.protobuf.ByteString.copyFromUtf8(
                    (String) ref);
            number_ = b;
            return b;
          } else {
            return (com.google.protobuf.ByteString) ref;
          }
        }
        /**
         * <code>string number = 1;</code>
         */
        public Builder setNumber(
            String value) {
          if (value == null) {
    throw new NullPointerException();
  }
  
          number_ = value;
          onChanged();
          return this;
        }
        /**
         * <code>string number = 1;</code>
         */
        public Builder clearNumber() {
          
          number_ = getDefaultInstance().getNumber();
          onChanged();
          return this;
        }
        /**
         * <code>string number = 1;</code>
         */
        public Builder setNumberBytes(
            com.google.protobuf.ByteString value) {
          if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
          
          number_ = value;
          onChanged();
          return this;
        }

        private long id_ ;
        /**
         * <code>int64 id = 2;</code>
         */
        public long getId() {
          return id_;
        }
        /**
         * <code>int64 id = 2;</code>
         */
        public Builder setId(long value) {
          
          id_ = value;
          onChanged();
          return this;
        }
        /**
         * <code>int64 id = 2;</code>
         */
        public Builder clearId() {
          
          id_ = 0L;
          onChanged();
          return this;
        }
        @Override
        public final Builder setUnknownFields(
            final com.google.protobuf.UnknownFieldSet unknownFields) {
          return super.setUnknownFields(unknownFields);
        }

        @Override
        public final Builder mergeUnknownFields(
            final com.google.protobuf.UnknownFieldSet unknownFields) {
          return super.mergeUnknownFields(unknownFields);
        }


        // @@protoc_insertion_point(builder_scope:com.ukelink.um.proto.ClientInfo.UserValue)
      }

      // @@protoc_insertion_point(class_scope:com.ukelink.um.proto.ClientInfo.UserValue)
      private static final UserValue DEFAULT_INSTANCE;
      static {
        DEFAULT_INSTANCE = new UserValue();
      }

      public static UserValue getDefaultInstance() {
        return DEFAULT_INSTANCE;
      }

      private static final com.google.protobuf.Parser<UserValue>
          PARSER = new com.google.protobuf.AbstractParser<UserValue>() {
        @Override
        public UserValue parsePartialFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
          return new UserValue(input, extensionRegistry);
        }
      };

      public static com.google.protobuf.Parser<UserValue> parser() {
        return PARSER;
      }

      @Override
      public com.google.protobuf.Parser<UserValue> getParserForType() {
        return PARSER;
      }

      @Override
      public UserValue getDefaultInstanceForType() {
        return DEFAULT_INSTANCE;
      }

    }

    public static final int USERTYPE_FIELD_NUMBER = 1;
    private int userType_;
    /**
     * <code>.com.ukelink.um.proto.ClientInfo.UserType userType = 1;</code>
     */
    public int getUserTypeValue() {
      return userType_;
    }
    /**
     * <code>.com.ukelink.um.proto.ClientInfo.UserType userType = 1;</code>
     */
    public UserType getUserType() {
      @SuppressWarnings("deprecation")
      UserType result = UserType.valueOf(userType_);
      return result == null ? UserType.UNRECOGNIZED : result;
    }

    public static final int USERVALUE_FIELD_NUMBER = 2;
    private UserValue userValue_;
    /**
     * <code>.com.ukelink.um.proto.ClientInfo.UserValue userValue = 2;</code>
     */
    public boolean hasUserValue() {
      return userValue_ != null;
    }
    /**
     * <code>.com.ukelink.um.proto.ClientInfo.UserValue userValue = 2;</code>
     */
    public UserValue getUserValue() {
      return userValue_ == null ? UserValue.getDefaultInstance() : userValue_;
    }
    /**
     * <code>.com.ukelink.um.proto.ClientInfo.UserValue userValue = 2;</code>
     */
    public UserValueOrBuilder getUserValueOrBuilder() {
      return getUserValue();
    }

    public static final int CLIENT_ID_FIELD_NUMBER = 3;
    private volatile Object clientId_;
    /**
     * <code>string client_id = 3;</code>
     */
    public String getClientId() {
      Object ref = clientId_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        clientId_ = s;
        return s;
      }
    }
    /**
     * <code>string client_id = 3;</code>
     */
    public com.google.protobuf.ByteString
        getClientIdBytes() {
      Object ref = clientId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        clientId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int DEVICETYPE_FIELD_NUMBER = 4;
    private volatile Object deviceType_;
    /**
     * <code>string deviceType = 4;</code>
     */
    public String getDeviceType() {
      Object ref = deviceType_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        deviceType_ = s;
        return s;
      }
    }
    /**
     * <code>string deviceType = 4;</code>
     */
    public com.google.protobuf.ByteString
        getDeviceTypeBytes() {
      Object ref = deviceType_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        deviceType_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    @Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (userType_ != UserType.error.getNumber()) {
        output.writeEnum(1, userType_);
      }
      if (userValue_ != null) {
        output.writeMessage(2, getUserValue());
      }
      if (!getClientIdBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 3, clientId_);
      }
      if (!getDeviceTypeBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 4, deviceType_);
      }
      unknownFields.writeTo(output);
    }

    @Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (userType_ != UserType.error.getNumber()) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(1, userType_);
      }
      if (userValue_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, getUserValue());
      }
      if (!getClientIdBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, clientId_);
      }
      if (!getDeviceTypeBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, deviceType_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @Override
    public boolean equals(final Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof ClientInfo)) {
        return super.equals(obj);
      }
      ClientInfo other = (ClientInfo) obj;

      if (userType_ != other.userType_) return false;
      if (hasUserValue() != other.hasUserValue()) return false;
      if (hasUserValue()) {
        if (!getUserValue()
            .equals(other.getUserValue())) return false;
      }
      if (!getClientId()
          .equals(other.getClientId())) return false;
      if (!getDeviceType()
          .equals(other.getDeviceType())) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + USERTYPE_FIELD_NUMBER;
      hash = (53 * hash) + userType_;
      if (hasUserValue()) {
        hash = (37 * hash) + USERVALUE_FIELD_NUMBER;
        hash = (53 * hash) + getUserValue().hashCode();
      }
      hash = (37 * hash) + CLIENT_ID_FIELD_NUMBER;
      hash = (53 * hash) + getClientId().hashCode();
      hash = (37 * hash) + DEVICETYPE_FIELD_NUMBER;
      hash = (53 * hash) + getDeviceType().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static ClientInfo parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static ClientInfo parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static ClientInfo parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static ClientInfo parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static ClientInfo parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static ClientInfo parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static ClientInfo parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static ClientInfo parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static ClientInfo parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static ClientInfo parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static ClientInfo parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static ClientInfo parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(ClientInfo prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @Override
    protected Builder newBuilderForType(
        BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.ukelink.um.proto.ClientInfo}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:com.ukelink.um.proto.ClientInfo)
        ClientInfoOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return Clientinfo.internal_static_com_ukelink_um_proto_ClientInfo_descriptor;
      }

      @Override
      protected FieldAccessorTable
          internalGetFieldAccessorTable() {
        return Clientinfo.internal_static_com_ukelink_um_proto_ClientInfo_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                ClientInfo.class, Builder.class);
      }

      // Construct using com.ukelink.um.proto.Clientinfo.ClientInfo.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @Override
      public Builder clear() {
        super.clear();
        userType_ = 0;

        if (userValueBuilder_ == null) {
          userValue_ = null;
        } else {
          userValue_ = null;
          userValueBuilder_ = null;
        }
        clientId_ = "";

        deviceType_ = "";

        return this;
      }

      @Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return Clientinfo.internal_static_com_ukelink_um_proto_ClientInfo_descriptor;
      }

      @Override
      public ClientInfo getDefaultInstanceForType() {
        return ClientInfo.getDefaultInstance();
      }

      @Override
      public ClientInfo build() {
        ClientInfo result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @Override
      public ClientInfo buildPartial() {
        ClientInfo result = new ClientInfo(this);
        result.userType_ = userType_;
        if (userValueBuilder_ == null) {
          result.userValue_ = userValue_;
        } else {
          result.userValue_ = userValueBuilder_.build();
        }
        result.clientId_ = clientId_;
        result.deviceType_ = deviceType_;
        onBuilt();
        return result;
      }

      @Override
      public Builder clone() {
        return super.clone();
      }
      @Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return super.setField(field, value);
      }
      @Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return super.addRepeatedField(field, value);
      }
      @Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof ClientInfo) {
          return mergeFrom((ClientInfo)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(ClientInfo other) {
        if (other == ClientInfo.getDefaultInstance()) return this;
        if (other.userType_ != 0) {
          setUserTypeValue(other.getUserTypeValue());
        }
        if (other.hasUserValue()) {
          mergeUserValue(other.getUserValue());
        }
        if (!other.getClientId().isEmpty()) {
          clientId_ = other.clientId_;
          onChanged();
        }
        if (!other.getDeviceType().isEmpty()) {
          deviceType_ = other.deviceType_;
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @Override
      public final boolean isInitialized() {
        return true;
      }

      @Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        ClientInfo parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (ClientInfo) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private int userType_ = 0;
      /**
       * <code>.com.ukelink.um.proto.ClientInfo.UserType userType = 1;</code>
       */
      public int getUserTypeValue() {
        return userType_;
      }
      /**
       * <code>.com.ukelink.um.proto.ClientInfo.UserType userType = 1;</code>
       */
      public Builder setUserTypeValue(int value) {
        userType_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>.com.ukelink.um.proto.ClientInfo.UserType userType = 1;</code>
       */
      public UserType getUserType() {
        @SuppressWarnings("deprecation")
        UserType result = UserType.valueOf(userType_);
        return result == null ? UserType.UNRECOGNIZED : result;
      }
      /**
       * <code>.com.ukelink.um.proto.ClientInfo.UserType userType = 1;</code>
       */
      public Builder setUserType(UserType value) {
        if (value == null) {
          throw new NullPointerException();
        }
        
        userType_ = value.getNumber();
        onChanged();
        return this;
      }
      /**
       * <code>.com.ukelink.um.proto.ClientInfo.UserType userType = 1;</code>
       */
      public Builder clearUserType() {
        
        userType_ = 0;
        onChanged();
        return this;
      }

      private UserValue userValue_;
      private com.google.protobuf.SingleFieldBuilderV3<
          UserValue, UserValue.Builder, UserValueOrBuilder> userValueBuilder_;
      /**
       * <code>.com.ukelink.um.proto.ClientInfo.UserValue userValue = 2;</code>
       */
      public boolean hasUserValue() {
        return userValueBuilder_ != null || userValue_ != null;
      }
      /**
       * <code>.com.ukelink.um.proto.ClientInfo.UserValue userValue = 2;</code>
       */
      public UserValue getUserValue() {
        if (userValueBuilder_ == null) {
          return userValue_ == null ? UserValue.getDefaultInstance() : userValue_;
        } else {
          return userValueBuilder_.getMessage();
        }
      }
      /**
       * <code>.com.ukelink.um.proto.ClientInfo.UserValue userValue = 2;</code>
       */
      public Builder setUserValue(UserValue value) {
        if (userValueBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          userValue_ = value;
          onChanged();
        } else {
          userValueBuilder_.setMessage(value);
        }

        return this;
      }
      /**
       * <code>.com.ukelink.um.proto.ClientInfo.UserValue userValue = 2;</code>
       */
      public Builder setUserValue(
          UserValue.Builder builderForValue) {
        if (userValueBuilder_ == null) {
          userValue_ = builderForValue.build();
          onChanged();
        } else {
          userValueBuilder_.setMessage(builderForValue.build());
        }

        return this;
      }
      /**
       * <code>.com.ukelink.um.proto.ClientInfo.UserValue userValue = 2;</code>
       */
      public Builder mergeUserValue(UserValue value) {
        if (userValueBuilder_ == null) {
          if (userValue_ != null) {
            userValue_ =
              UserValue.newBuilder(userValue_).mergeFrom(value).buildPartial();
          } else {
            userValue_ = value;
          }
          onChanged();
        } else {
          userValueBuilder_.mergeFrom(value);
        }

        return this;
      }
      /**
       * <code>.com.ukelink.um.proto.ClientInfo.UserValue userValue = 2;</code>
       */
      public Builder clearUserValue() {
        if (userValueBuilder_ == null) {
          userValue_ = null;
          onChanged();
        } else {
          userValue_ = null;
          userValueBuilder_ = null;
        }

        return this;
      }
      /**
       * <code>.com.ukelink.um.proto.ClientInfo.UserValue userValue = 2;</code>
       */
      public UserValue.Builder getUserValueBuilder() {
        
        onChanged();
        return getUserValueFieldBuilder().getBuilder();
      }
      /**
       * <code>.com.ukelink.um.proto.ClientInfo.UserValue userValue = 2;</code>
       */
      public UserValueOrBuilder getUserValueOrBuilder() {
        if (userValueBuilder_ != null) {
          return userValueBuilder_.getMessageOrBuilder();
        } else {
          return userValue_ == null ?
              UserValue.getDefaultInstance() : userValue_;
        }
      }
      /**
       * <code>.com.ukelink.um.proto.ClientInfo.UserValue userValue = 2;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          UserValue, UserValue.Builder, UserValueOrBuilder>
          getUserValueFieldBuilder() {
        if (userValueBuilder_ == null) {
          userValueBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              UserValue, UserValue.Builder, UserValueOrBuilder>(
                  getUserValue(),
                  getParentForChildren(),
                  isClean());
          userValue_ = null;
        }
        return userValueBuilder_;
      }

      private Object clientId_ = "";
      /**
       * <code>string client_id = 3;</code>
       */
      public String getClientId() {
        Object ref = clientId_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          clientId_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <code>string client_id = 3;</code>
       */
      public com.google.protobuf.ByteString
          getClientIdBytes() {
        Object ref = clientId_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          clientId_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string client_id = 3;</code>
       */
      public Builder setClientId(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        clientId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string client_id = 3;</code>
       */
      public Builder clearClientId() {
        
        clientId_ = getDefaultInstance().getClientId();
        onChanged();
        return this;
      }
      /**
       * <code>string client_id = 3;</code>
       */
      public Builder setClientIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        clientId_ = value;
        onChanged();
        return this;
      }

      private Object deviceType_ = "";
      /**
       * <code>string deviceType = 4;</code>
       */
      public String getDeviceType() {
        Object ref = deviceType_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          deviceType_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <code>string deviceType = 4;</code>
       */
      public com.google.protobuf.ByteString
          getDeviceTypeBytes() {
        Object ref = deviceType_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          deviceType_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string deviceType = 4;</code>
       */
      public Builder setDeviceType(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        deviceType_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string deviceType = 4;</code>
       */
      public Builder clearDeviceType() {
        
        deviceType_ = getDefaultInstance().getDeviceType();
        onChanged();
        return this;
      }
      /**
       * <code>string deviceType = 4;</code>
       */
      public Builder setDeviceTypeBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        deviceType_ = value;
        onChanged();
        return this;
      }
      @Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:com.ukelink.um.proto.ClientInfo)
    }

    // @@protoc_insertion_point(class_scope:com.ukelink.um.proto.ClientInfo)
    private static final ClientInfo DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new ClientInfo();
    }

    public static ClientInfo getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<ClientInfo>
        PARSER = new com.google.protobuf.AbstractParser<ClientInfo>() {
      @Override
      public ClientInfo parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new ClientInfo(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<ClientInfo> parser() {
      return PARSER;
    }

    @Override
    public com.google.protobuf.Parser<ClientInfo> getParserForType() {
      return PARSER;
    }

    @Override
    public ClientInfo getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_ukelink_um_proto_ClientInfo_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_ukelink_um_proto_ClientInfo_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_ukelink_um_proto_ClientInfo_UserValue_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_ukelink_um_proto_ClientInfo_UserValue_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    String[] descriptorData = {
      "\n\020clientinfo.proto\022\024com.ukelink.um.proto" +
      "\"\232\002\n\nClientInfo\022;\n\010userType\030\001 \001(\0162).com." +
      "ukelink.um.proto.ClientInfo.UserType\022=\n\t" +
      "userValue\030\002 \001(\0132*.com.ukelink.um.proto.C" +
      "lientInfo.UserValue\022\021\n\tclient_id\030\003 \001(\t\022\022" +
      "\n\ndeviceType\030\004 \001(\t\032\'\n\tUserValue\022\016\n\006numbe" +
      "r\030\001 \001(\t\022\n\n\002id\030\002 \001(\003\"@\n\010UserType\022\t\n\005error" +
      "\020\000\022\n\n\006userId\020\001\022\007\n\003sim\020\002\022\007\n\003sip\020\003\022\013\n\007grou" +
      "pId\020\004b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_com_ukelink_um_proto_ClientInfo_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_ukelink_um_proto_ClientInfo_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_ukelink_um_proto_ClientInfo_descriptor,
        new String[] { "UserType", "UserValue", "ClientId", "DeviceType", });
    internal_static_com_ukelink_um_proto_ClientInfo_UserValue_descriptor =
      internal_static_com_ukelink_um_proto_ClientInfo_descriptor.getNestedTypes().get(0);
    internal_static_com_ukelink_um_proto_ClientInfo_UserValue_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_ukelink_um_proto_ClientInfo_UserValue_descriptor,
        new String[] { "Number", "Id", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
