// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: vmmbody.proto

package com.ukelink.um.proto;

public final class Vmmbody {
  private Vmmbody() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface VmmBodyOrBuilder extends
      // @@protoc_insertion_point(interface_extends:com.ukelink.um.proto.VmmBody)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>int32 contentType = 1;</code>
     */
    int getContentType();

    /**
     * <code>int32 mediaType = 2;</code>
     */
    int getMediaType();

    /**
     * <code>bytes content = 3;</code>
     */
    com.google.protobuf.ByteString getContent();

    /**
     * <code>int32 thumbnailType = 4;</code>
     */
    int getThumbnailType();

    /**
     * <code>bytes thumbnailContent = 5;</code>
     */
    com.google.protobuf.ByteString getThumbnailContent();

    /**
     * <code>string remoteContentUrl = 6;</code>
     */
    String getRemoteContentUrl();
    /**
     * <code>string remoteContentUrl = 6;</code>
     */
    com.google.protobuf.ByteString
        getRemoteContentUrlBytes();

    /**
     * <code>int32 mentionedType = 7;</code>
     */
    int getMentionedType();

    /**
     * <code>repeated string mentionedUser = 8;</code>
     */
    java.util.List<String>
        getMentionedUserList();
    /**
     * <code>repeated string mentionedUser = 8;</code>
     */
    int getMentionedUserCount();
    /**
     * <code>repeated string mentionedUser = 8;</code>
     */
    String getMentionedUser(int index);
    /**
     * <code>repeated string mentionedUser = 8;</code>
     */
    com.google.protobuf.ByteString
        getMentionedUserBytes(int index);
  }
  /**
   * Protobuf type {@code com.ukelink.um.proto.VmmBody}
   */
  public  static final class VmmBody extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:com.ukelink.um.proto.VmmBody)
      VmmBodyOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use VmmBody.newBuilder() to construct.
    private VmmBody(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private VmmBody() {
      content_ = com.google.protobuf.ByteString.EMPTY;
      thumbnailContent_ = com.google.protobuf.ByteString.EMPTY;
      remoteContentUrl_ = "";
      mentionedUser_ = com.google.protobuf.LazyStringArrayList.EMPTY;
    }

    @Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private VmmBody(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {

              contentType_ = input.readInt32();
              break;
            }
            case 16: {

              mediaType_ = input.readInt32();
              break;
            }
            case 26: {

              content_ = input.readBytes();
              break;
            }
            case 32: {

              thumbnailType_ = input.readInt32();
              break;
            }
            case 42: {

              thumbnailContent_ = input.readBytes();
              break;
            }
            case 50: {
              String s = input.readStringRequireUtf8();

              remoteContentUrl_ = s;
              break;
            }
            case 56: {

              mentionedType_ = input.readInt32();
              break;
            }
            case 66: {
              String s = input.readStringRequireUtf8();
              if (!((mutable_bitField0_ & 0x00000080) != 0)) {
                mentionedUser_ = new com.google.protobuf.LazyStringArrayList();
                mutable_bitField0_ |= 0x00000080;
              }
              mentionedUser_.add(s);
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000080) != 0)) {
          mentionedUser_ = mentionedUser_.getUnmodifiableView();
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return internal_static_com_ukelink_um_proto_VmmBody_descriptor;
    }

    @Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return internal_static_com_ukelink_um_proto_VmmBody_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.ukelink.um.proto.Vmmbody.VmmBody.class, com.ukelink.um.proto.Vmmbody.VmmBody.Builder.class);
    }

    private int bitField0_;
    public static final int CONTENTTYPE_FIELD_NUMBER = 1;
    private int contentType_;
    /**
     * <code>int32 contentType = 1;</code>
     */
    public int getContentType() {
      return contentType_;
    }

    public static final int MEDIATYPE_FIELD_NUMBER = 2;
    private int mediaType_;
    /**
     * <code>int32 mediaType = 2;</code>
     */
    public int getMediaType() {
      return mediaType_;
    }

    public static final int CONTENT_FIELD_NUMBER = 3;
    private com.google.protobuf.ByteString content_;
    /**
     * <code>bytes content = 3;</code>
     */
    public com.google.protobuf.ByteString getContent() {
      return content_;
    }

    public static final int THUMBNAILTYPE_FIELD_NUMBER = 4;
    private int thumbnailType_;
    /**
     * <code>int32 thumbnailType = 4;</code>
     */
    public int getThumbnailType() {
      return thumbnailType_;
    }

    public static final int THUMBNAILCONTENT_FIELD_NUMBER = 5;
    private com.google.protobuf.ByteString thumbnailContent_;
    /**
     * <code>bytes thumbnailContent = 5;</code>
     */
    public com.google.protobuf.ByteString getThumbnailContent() {
      return thumbnailContent_;
    }

    public static final int REMOTECONTENTURL_FIELD_NUMBER = 6;
    private volatile Object remoteContentUrl_;
    /**
     * <code>string remoteContentUrl = 6;</code>
     */
    public String getRemoteContentUrl() {
      Object ref = remoteContentUrl_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        remoteContentUrl_ = s;
        return s;
      }
    }
    /**
     * <code>string remoteContentUrl = 6;</code>
     */
    public com.google.protobuf.ByteString
        getRemoteContentUrlBytes() {
      Object ref = remoteContentUrl_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        remoteContentUrl_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int MENTIONEDTYPE_FIELD_NUMBER = 7;
    private int mentionedType_;
    /**
     * <code>int32 mentionedType = 7;</code>
     */
    public int getMentionedType() {
      return mentionedType_;
    }

    public static final int MENTIONEDUSER_FIELD_NUMBER = 8;
    private com.google.protobuf.LazyStringList mentionedUser_;
    /**
     * <code>repeated string mentionedUser = 8;</code>
     */
    public com.google.protobuf.ProtocolStringList
        getMentionedUserList() {
      return mentionedUser_;
    }
    /**
     * <code>repeated string mentionedUser = 8;</code>
     */
    public int getMentionedUserCount() {
      return mentionedUser_.size();
    }
    /**
     * <code>repeated string mentionedUser = 8;</code>
     */
    public String getMentionedUser(int index) {
      return mentionedUser_.get(index);
    }
    /**
     * <code>repeated string mentionedUser = 8;</code>
     */
    public com.google.protobuf.ByteString
        getMentionedUserBytes(int index) {
      return mentionedUser_.getByteString(index);
    }

    private byte memoizedIsInitialized = -1;
    @Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (contentType_ != 0) {
        output.writeInt32(1, contentType_);
      }
      if (mediaType_ != 0) {
        output.writeInt32(2, mediaType_);
      }
      if (!content_.isEmpty()) {
        output.writeBytes(3, content_);
      }
      if (thumbnailType_ != 0) {
        output.writeInt32(4, thumbnailType_);
      }
      if (!thumbnailContent_.isEmpty()) {
        output.writeBytes(5, thumbnailContent_);
      }
      if (!getRemoteContentUrlBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 6, remoteContentUrl_);
      }
      if (mentionedType_ != 0) {
        output.writeInt32(7, mentionedType_);
      }
      for (int i = 0; i < mentionedUser_.size(); i++) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 8, mentionedUser_.getRaw(i));
      }
      unknownFields.writeTo(output);
    }

    @Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (contentType_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, contentType_);
      }
      if (mediaType_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, mediaType_);
      }
      if (!content_.isEmpty()) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(3, content_);
      }
      if (thumbnailType_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(4, thumbnailType_);
      }
      if (!thumbnailContent_.isEmpty()) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(5, thumbnailContent_);
      }
      if (!getRemoteContentUrlBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(6, remoteContentUrl_);
      }
      if (mentionedType_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(7, mentionedType_);
      }
      {
        int dataSize = 0;
        for (int i = 0; i < mentionedUser_.size(); i++) {
          dataSize += computeStringSizeNoTag(mentionedUser_.getRaw(i));
        }
        size += dataSize;
        size += 1 * getMentionedUserList().size();
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @Override
    public boolean equals(final Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.ukelink.um.proto.Vmmbody.VmmBody)) {
        return super.equals(obj);
      }
      com.ukelink.um.proto.Vmmbody.VmmBody other = (com.ukelink.um.proto.Vmmbody.VmmBody) obj;

      if (getContentType()
          != other.getContentType()) return false;
      if (getMediaType()
          != other.getMediaType()) return false;
      if (!getContent()
          .equals(other.getContent())) return false;
      if (getThumbnailType()
          != other.getThumbnailType()) return false;
      if (!getThumbnailContent()
          .equals(other.getThumbnailContent())) return false;
      if (!getRemoteContentUrl()
          .equals(other.getRemoteContentUrl())) return false;
      if (getMentionedType()
          != other.getMentionedType()) return false;
      if (!getMentionedUserList()
          .equals(other.getMentionedUserList())) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + CONTENTTYPE_FIELD_NUMBER;
      hash = (53 * hash) + getContentType();
      hash = (37 * hash) + MEDIATYPE_FIELD_NUMBER;
      hash = (53 * hash) + getMediaType();
      hash = (37 * hash) + CONTENT_FIELD_NUMBER;
      hash = (53 * hash) + getContent().hashCode();
      hash = (37 * hash) + THUMBNAILTYPE_FIELD_NUMBER;
      hash = (53 * hash) + getThumbnailType();
      hash = (37 * hash) + THUMBNAILCONTENT_FIELD_NUMBER;
      hash = (53 * hash) + getThumbnailContent().hashCode();
      hash = (37 * hash) + REMOTECONTENTURL_FIELD_NUMBER;
      hash = (53 * hash) + getRemoteContentUrl().hashCode();
      hash = (37 * hash) + MENTIONEDTYPE_FIELD_NUMBER;
      hash = (53 * hash) + getMentionedType();
      if (getMentionedUserCount() > 0) {
        hash = (37 * hash) + MENTIONEDUSER_FIELD_NUMBER;
        hash = (53 * hash) + getMentionedUserList().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.ukelink.um.proto.Vmmbody.VmmBody parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.ukelink.um.proto.Vmmbody.VmmBody parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.ukelink.um.proto.Vmmbody.VmmBody parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.ukelink.um.proto.Vmmbody.VmmBody parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.ukelink.um.proto.Vmmbody.VmmBody parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.ukelink.um.proto.Vmmbody.VmmBody parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.ukelink.um.proto.Vmmbody.VmmBody parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.ukelink.um.proto.Vmmbody.VmmBody parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.ukelink.um.proto.Vmmbody.VmmBody parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.ukelink.um.proto.Vmmbody.VmmBody parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.ukelink.um.proto.Vmmbody.VmmBody parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.ukelink.um.proto.Vmmbody.VmmBody parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.ukelink.um.proto.Vmmbody.VmmBody prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.ukelink.um.proto.VmmBody}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:com.ukelink.um.proto.VmmBody)
        com.ukelink.um.proto.Vmmbody.VmmBodyOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return internal_static_com_ukelink_um_proto_VmmBody_descriptor;
      }

      @Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return internal_static_com_ukelink_um_proto_VmmBody_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.ukelink.um.proto.Vmmbody.VmmBody.class, com.ukelink.um.proto.Vmmbody.VmmBody.Builder.class);
      }

      // Construct using com.ukelink.um.proto.Vmmbody.VmmBody.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @Override
      public Builder clear() {
        super.clear();
        contentType_ = 0;

        mediaType_ = 0;

        content_ = com.google.protobuf.ByteString.EMPTY;

        thumbnailType_ = 0;

        thumbnailContent_ = com.google.protobuf.ByteString.EMPTY;

        remoteContentUrl_ = "";

        mentionedType_ = 0;

        mentionedUser_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000080);
        return this;
      }

      @Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return internal_static_com_ukelink_um_proto_VmmBody_descriptor;
      }

      @Override
      public com.ukelink.um.proto.Vmmbody.VmmBody getDefaultInstanceForType() {
        return getDefaultInstance();
      }

      @Override
      public com.ukelink.um.proto.Vmmbody.VmmBody build() {
        com.ukelink.um.proto.Vmmbody.VmmBody result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @Override
      public com.ukelink.um.proto.Vmmbody.VmmBody buildPartial() {
        com.ukelink.um.proto.Vmmbody.VmmBody result = new com.ukelink.um.proto.Vmmbody.VmmBody(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        result.contentType_ = contentType_;
        result.mediaType_ = mediaType_;
        result.content_ = content_;
        result.thumbnailType_ = thumbnailType_;
        result.thumbnailContent_ = thumbnailContent_;
        result.remoteContentUrl_ = remoteContentUrl_;
        result.mentionedType_ = mentionedType_;
        if (((bitField0_ & 0x00000080) != 0)) {
          mentionedUser_ = mentionedUser_.getUnmodifiableView();
          bitField0_ = (bitField0_ & ~0x00000080);
        }
        result.mentionedUser_ = mentionedUser_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      @Override
      public Builder clone() {
        return super.clone();
      }
      @Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return super.setField(field, value);
      }
      @Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return super.addRepeatedField(field, value);
      }
      @Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.ukelink.um.proto.Vmmbody.VmmBody) {
          return mergeFrom((com.ukelink.um.proto.Vmmbody.VmmBody)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.ukelink.um.proto.Vmmbody.VmmBody other) {
        if (other == getDefaultInstance()) return this;
        if (other.getContentType() != 0) {
          setContentType(other.getContentType());
        }
        if (other.getMediaType() != 0) {
          setMediaType(other.getMediaType());
        }
        if (other.getContent() != com.google.protobuf.ByteString.EMPTY) {
          setContent(other.getContent());
        }
        if (other.getThumbnailType() != 0) {
          setThumbnailType(other.getThumbnailType());
        }
        if (other.getThumbnailContent() != com.google.protobuf.ByteString.EMPTY) {
          setThumbnailContent(other.getThumbnailContent());
        }
        if (!other.getRemoteContentUrl().isEmpty()) {
          remoteContentUrl_ = other.remoteContentUrl_;
          onChanged();
        }
        if (other.getMentionedType() != 0) {
          setMentionedType(other.getMentionedType());
        }
        if (!other.mentionedUser_.isEmpty()) {
          if (mentionedUser_.isEmpty()) {
            mentionedUser_ = other.mentionedUser_;
            bitField0_ = (bitField0_ & ~0x00000080);
          } else {
            ensureMentionedUserIsMutable();
            mentionedUser_.addAll(other.mentionedUser_);
          }
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @Override
      public final boolean isInitialized() {
        return true;
      }

      @Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.ukelink.um.proto.Vmmbody.VmmBody parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.ukelink.um.proto.Vmmbody.VmmBody) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private int contentType_ ;
      /**
       * <code>int32 contentType = 1;</code>
       */
      public int getContentType() {
        return contentType_;
      }
      /**
       * <code>int32 contentType = 1;</code>
       */
      public Builder setContentType(int value) {
        
        contentType_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 contentType = 1;</code>
       */
      public Builder clearContentType() {
        
        contentType_ = 0;
        onChanged();
        return this;
      }

      private int mediaType_ ;
      /**
       * <code>int32 mediaType = 2;</code>
       */
      public int getMediaType() {
        return mediaType_;
      }
      /**
       * <code>int32 mediaType = 2;</code>
       */
      public Builder setMediaType(int value) {
        
        mediaType_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 mediaType = 2;</code>
       */
      public Builder clearMediaType() {
        
        mediaType_ = 0;
        onChanged();
        return this;
      }

      private com.google.protobuf.ByteString content_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <code>bytes content = 3;</code>
       */
      public com.google.protobuf.ByteString getContent() {
        return content_;
      }
      /**
       * <code>bytes content = 3;</code>
       */
      public Builder setContent(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        content_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>bytes content = 3;</code>
       */
      public Builder clearContent() {
        
        content_ = getDefaultInstance().getContent();
        onChanged();
        return this;
      }

      private int thumbnailType_ ;
      /**
       * <code>int32 thumbnailType = 4;</code>
       */
      public int getThumbnailType() {
        return thumbnailType_;
      }
      /**
       * <code>int32 thumbnailType = 4;</code>
       */
      public Builder setThumbnailType(int value) {
        
        thumbnailType_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 thumbnailType = 4;</code>
       */
      public Builder clearThumbnailType() {
        
        thumbnailType_ = 0;
        onChanged();
        return this;
      }

      private com.google.protobuf.ByteString thumbnailContent_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <code>bytes thumbnailContent = 5;</code>
       */
      public com.google.protobuf.ByteString getThumbnailContent() {
        return thumbnailContent_;
      }
      /**
       * <code>bytes thumbnailContent = 5;</code>
       */
      public Builder setThumbnailContent(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        thumbnailContent_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>bytes thumbnailContent = 5;</code>
       */
      public Builder clearThumbnailContent() {
        
        thumbnailContent_ = getDefaultInstance().getThumbnailContent();
        onChanged();
        return this;
      }

      private Object remoteContentUrl_ = "";
      /**
       * <code>string remoteContentUrl = 6;</code>
       */
      public String getRemoteContentUrl() {
        Object ref = remoteContentUrl_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          remoteContentUrl_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <code>string remoteContentUrl = 6;</code>
       */
      public com.google.protobuf.ByteString
          getRemoteContentUrlBytes() {
        Object ref = remoteContentUrl_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          remoteContentUrl_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string remoteContentUrl = 6;</code>
       */
      public Builder setRemoteContentUrl(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        remoteContentUrl_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string remoteContentUrl = 6;</code>
       */
      public Builder clearRemoteContentUrl() {
        
        remoteContentUrl_ = getDefaultInstance().getRemoteContentUrl();
        onChanged();
        return this;
      }
      /**
       * <code>string remoteContentUrl = 6;</code>
       */
      public Builder setRemoteContentUrlBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        remoteContentUrl_ = value;
        onChanged();
        return this;
      }

      private int mentionedType_ ;
      /**
       * <code>int32 mentionedType = 7;</code>
       */
      public int getMentionedType() {
        return mentionedType_;
      }
      /**
       * <code>int32 mentionedType = 7;</code>
       */
      public Builder setMentionedType(int value) {
        
        mentionedType_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 mentionedType = 7;</code>
       */
      public Builder clearMentionedType() {
        
        mentionedType_ = 0;
        onChanged();
        return this;
      }

      private com.google.protobuf.LazyStringList mentionedUser_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      private void ensureMentionedUserIsMutable() {
        if (!((bitField0_ & 0x00000080) != 0)) {
          mentionedUser_ = new com.google.protobuf.LazyStringArrayList(mentionedUser_);
          bitField0_ |= 0x00000080;
         }
      }
      /**
       * <code>repeated string mentionedUser = 8;</code>
       */
      public com.google.protobuf.ProtocolStringList
          getMentionedUserList() {
        return mentionedUser_.getUnmodifiableView();
      }
      /**
       * <code>repeated string mentionedUser = 8;</code>
       */
      public int getMentionedUserCount() {
        return mentionedUser_.size();
      }
      /**
       * <code>repeated string mentionedUser = 8;</code>
       */
      public String getMentionedUser(int index) {
        return mentionedUser_.get(index);
      }
      /**
       * <code>repeated string mentionedUser = 8;</code>
       */
      public com.google.protobuf.ByteString
          getMentionedUserBytes(int index) {
        return mentionedUser_.getByteString(index);
      }
      /**
       * <code>repeated string mentionedUser = 8;</code>
       */
      public Builder setMentionedUser(
          int index, String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureMentionedUserIsMutable();
        mentionedUser_.set(index, value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string mentionedUser = 8;</code>
       */
      public Builder addMentionedUser(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureMentionedUserIsMutable();
        mentionedUser_.add(value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string mentionedUser = 8;</code>
       */
      public Builder addAllMentionedUser(
          Iterable<String> values) {
        ensureMentionedUserIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, mentionedUser_);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string mentionedUser = 8;</code>
       */
      public Builder clearMentionedUser() {
        mentionedUser_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000080);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string mentionedUser = 8;</code>
       */
      public Builder addMentionedUserBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        ensureMentionedUserIsMutable();
        mentionedUser_.add(value);
        onChanged();
        return this;
      }
      @Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:com.ukelink.um.proto.VmmBody)
    }

    // @@protoc_insertion_point(class_scope:com.ukelink.um.proto.VmmBody)
    private static final com.ukelink.um.proto.Vmmbody.VmmBody DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.ukelink.um.proto.Vmmbody.VmmBody();
    }

    public static com.ukelink.um.proto.Vmmbody.VmmBody getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<VmmBody>
        PARSER = new com.google.protobuf.AbstractParser<VmmBody>() {
      @Override
      public VmmBody parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new VmmBody(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<VmmBody> parser() {
      return PARSER;
    }

    @Override
    public com.google.protobuf.Parser<VmmBody> getParserForType() {
      return PARSER;
    }

    @Override
    public com.ukelink.um.proto.Vmmbody.VmmBody getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_ukelink_um_proto_VmmBody_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_ukelink_um_proto_VmmBody_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    String[] descriptorData = {
      "\n\rvmmbody.proto\022\024com.ukelink.um.proto\"\273\001" +
      "\n\007VmmBody\022\023\n\013contentType\030\001 \001(\005\022\021\n\tmediaT" +
      "ype\030\002 \001(\005\022\017\n\007content\030\003 \001(\014\022\025\n\rthumbnailT" +
      "ype\030\004 \001(\005\022\030\n\020thumbnailContent\030\005 \001(\014\022\030\n\020r" +
      "emoteContentUrl\030\006 \001(\t\022\025\n\rmentionedType\030\007" +
      " \001(\005\022\025\n\rmentionedUser\030\010 \003(\tb\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_com_ukelink_um_proto_VmmBody_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_ukelink_um_proto_VmmBody_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_ukelink_um_proto_VmmBody_descriptor,
        new String[] { "ContentType", "MediaType", "Content", "ThumbnailType", "ThumbnailContent", "RemoteContentUrl", "MentionedType", "MentionedUser", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
