// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: vmmheader.proto

package com.ukelink.um.proto;

public final class Vmmheader {
  private Vmmheader() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface VmmHeaderOrBuilder extends
      // @@protoc_insertion_point(interface_extends:com.ukelink.um.proto.VmmHeader)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>.com.ukelink.um.proto.ClientInfo fromUser = 1;</code>
     */
    boolean hasFromUser();
    /**
     * <code>.com.ukelink.um.proto.ClientInfo fromUser = 1;</code>
     */
    com.ukelink.um.proto.Clientinfo.ClientInfo getFromUser();
    /**
     * <code>.com.ukelink.um.proto.ClientInfo fromUser = 1;</code>
     */
    com.ukelink.um.proto.Clientinfo.ClientInfoOrBuilder getFromUserOrBuilder();

    /**
     * <code>repeated .com.ukelink.um.proto.ClientInfo toUser = 2;</code>
     */
    java.util.List<com.ukelink.um.proto.Clientinfo.ClientInfo> 
        getToUserList();
    /**
     * <code>repeated .com.ukelink.um.proto.ClientInfo toUser = 2;</code>
     */
    com.ukelink.um.proto.Clientinfo.ClientInfo getToUser(int index);
    /**
     * <code>repeated .com.ukelink.um.proto.ClientInfo toUser = 2;</code>
     */
    int getToUserCount();
    /**
     * <code>repeated .com.ukelink.um.proto.ClientInfo toUser = 2;</code>
     */
    java.util.List<? extends com.ukelink.um.proto.Clientinfo.ClientInfoOrBuilder> 
        getToUserOrBuilderList();
    /**
     * <code>repeated .com.ukelink.um.proto.ClientInfo toUser = 2;</code>
     */
    com.ukelink.um.proto.Clientinfo.ClientInfoOrBuilder getToUserOrBuilder(
            int index);

    /**
     * <code>int32 conversationType = 3;</code>
     */
    int getConversationType();

    /**
     * <pre>
     *消息撤回
     * </pre>
     *
     * <code>int32 action = 4;</code>
     */
    int getAction();

    /**
     * <code>string language = 5;</code>
     */
    String getLanguage();
    /**
     * <code>string language = 5;</code>
     */
    com.google.protobuf.ByteString
        getLanguageBytes();

    /**
     * <code>string originalMsgId = 6;</code>
     */
    String getOriginalMsgId();
    /**
     * <code>string originalMsgId = 6;</code>
     */
    com.google.protobuf.ByteString
        getOriginalMsgIdBytes();

    /**
     * <code>string actionMsgId = 7;</code>
     */
    String getActionMsgId();
    /**
     * <code>string actionMsgId = 7;</code>
     */
    com.google.protobuf.ByteString
        getActionMsgIdBytes();

    /**
     * <code>string serverMsgId = 8;</code>
     */
    String getServerMsgId();
    /**
     * <code>string serverMsgId = 8;</code>
     */
    com.google.protobuf.ByteString
        getServerMsgIdBytes();

    /**
     * <code>int64 messageTime = 9;</code>
     */
    long getMessageTime();
  }
  /**
   * <pre>
   *import public "google/protobuf/timestamp.proto"; 
   * </pre>
   *
   * Protobuf type {@code com.ukelink.um.proto.VmmHeader}
   */
  public  static final class VmmHeader extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:com.ukelink.um.proto.VmmHeader)
      VmmHeaderOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use VmmHeader.newBuilder() to construct.
    private VmmHeader(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private VmmHeader() {
      toUser_ = java.util.Collections.emptyList();
      language_ = "";
      originalMsgId_ = "";
      actionMsgId_ = "";
      serverMsgId_ = "";
    }

    @Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private VmmHeader(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              com.ukelink.um.proto.Clientinfo.ClientInfo.Builder subBuilder = null;
              if (fromUser_ != null) {
                subBuilder = fromUser_.toBuilder();
              }
              fromUser_ = input.readMessage(com.ukelink.um.proto.Clientinfo.ClientInfo.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(fromUser_);
                fromUser_ = subBuilder.buildPartial();
              }

              break;
            }
            case 18: {
              if (!((mutable_bitField0_ & 0x00000002) != 0)) {
                toUser_ = new java.util.ArrayList<com.ukelink.um.proto.Clientinfo.ClientInfo>();
                mutable_bitField0_ |= 0x00000002;
              }
              toUser_.add(
                  input.readMessage(com.ukelink.um.proto.Clientinfo.ClientInfo.parser(), extensionRegistry));
              break;
            }
            case 24: {

              conversationType_ = input.readInt32();
              break;
            }
            case 32: {

              action_ = input.readInt32();
              break;
            }
            case 42: {
              String s = input.readStringRequireUtf8();

              language_ = s;
              break;
            }
            case 50: {
              String s = input.readStringRequireUtf8();

              originalMsgId_ = s;
              break;
            }
            case 58: {
              String s = input.readStringRequireUtf8();

              actionMsgId_ = s;
              break;
            }
            case 66: {
              String s = input.readStringRequireUtf8();

              serverMsgId_ = s;
              break;
            }
            case 72: {

              messageTime_ = input.readInt64();
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000002) != 0)) {
          toUser_ = java.util.Collections.unmodifiableList(toUser_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return internal_static_com_ukelink_um_proto_VmmHeader_descriptor;
    }

    @Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return internal_static_com_ukelink_um_proto_VmmHeader_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.ukelink.um.proto.Vmmheader.VmmHeader.class, com.ukelink.um.proto.Vmmheader.VmmHeader.Builder.class);
    }

    private int bitField0_;
    public static final int FROMUSER_FIELD_NUMBER = 1;
    private com.ukelink.um.proto.Clientinfo.ClientInfo fromUser_;
    /**
     * <code>.com.ukelink.um.proto.ClientInfo fromUser = 1;</code>
     */
    public boolean hasFromUser() {
      return fromUser_ != null;
    }
    /**
     * <code>.com.ukelink.um.proto.ClientInfo fromUser = 1;</code>
     */
    public com.ukelink.um.proto.Clientinfo.ClientInfo getFromUser() {
      return fromUser_ == null ? com.ukelink.um.proto.Clientinfo.ClientInfo.getDefaultInstance() : fromUser_;
    }
    /**
     * <code>.com.ukelink.um.proto.ClientInfo fromUser = 1;</code>
     */
    public com.ukelink.um.proto.Clientinfo.ClientInfoOrBuilder getFromUserOrBuilder() {
      return getFromUser();
    }

    public static final int TOUSER_FIELD_NUMBER = 2;
    private java.util.List<com.ukelink.um.proto.Clientinfo.ClientInfo> toUser_;
    /**
     * <code>repeated .com.ukelink.um.proto.ClientInfo toUser = 2;</code>
     */
    public java.util.List<com.ukelink.um.proto.Clientinfo.ClientInfo> getToUserList() {
      return toUser_;
    }
    /**
     * <code>repeated .com.ukelink.um.proto.ClientInfo toUser = 2;</code>
     */
    public java.util.List<? extends com.ukelink.um.proto.Clientinfo.ClientInfoOrBuilder> 
        getToUserOrBuilderList() {
      return toUser_;
    }
    /**
     * <code>repeated .com.ukelink.um.proto.ClientInfo toUser = 2;</code>
     */
    public int getToUserCount() {
      return toUser_.size();
    }
    /**
     * <code>repeated .com.ukelink.um.proto.ClientInfo toUser = 2;</code>
     */
    public com.ukelink.um.proto.Clientinfo.ClientInfo getToUser(int index) {
      return toUser_.get(index);
    }
    /**
     * <code>repeated .com.ukelink.um.proto.ClientInfo toUser = 2;</code>
     */
    public com.ukelink.um.proto.Clientinfo.ClientInfoOrBuilder getToUserOrBuilder(
        int index) {
      return toUser_.get(index);
    }

    public static final int CONVERSATIONTYPE_FIELD_NUMBER = 3;
    private int conversationType_;
    /**
     * <code>int32 conversationType = 3;</code>
     */
    public int getConversationType() {
      return conversationType_;
    }

    public static final int ACTION_FIELD_NUMBER = 4;
    private int action_;
    /**
     * <pre>
     *消息撤回
     * </pre>
     *
     * <code>int32 action = 4;</code>
     */
    public int getAction() {
      return action_;
    }

    public static final int LANGUAGE_FIELD_NUMBER = 5;
    private volatile Object language_;
    /**
     * <code>string language = 5;</code>
     */
    public String getLanguage() {
      Object ref = language_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        language_ = s;
        return s;
      }
    }
    /**
     * <code>string language = 5;</code>
     */
    public com.google.protobuf.ByteString
        getLanguageBytes() {
      Object ref = language_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        language_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int ORIGINALMSGID_FIELD_NUMBER = 6;
    private volatile Object originalMsgId_;
    /**
     * <code>string originalMsgId = 6;</code>
     */
    public String getOriginalMsgId() {
      Object ref = originalMsgId_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        originalMsgId_ = s;
        return s;
      }
    }
    /**
     * <code>string originalMsgId = 6;</code>
     */
    public com.google.protobuf.ByteString
        getOriginalMsgIdBytes() {
      Object ref = originalMsgId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        originalMsgId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int ACTIONMSGID_FIELD_NUMBER = 7;
    private volatile Object actionMsgId_;
    /**
     * <code>string actionMsgId = 7;</code>
     */
    public String getActionMsgId() {
      Object ref = actionMsgId_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        actionMsgId_ = s;
        return s;
      }
    }
    /**
     * <code>string actionMsgId = 7;</code>
     */
    public com.google.protobuf.ByteString
        getActionMsgIdBytes() {
      Object ref = actionMsgId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        actionMsgId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int SERVERMSGID_FIELD_NUMBER = 8;
    private volatile Object serverMsgId_;
    /**
     * <code>string serverMsgId = 8;</code>
     */
    public String getServerMsgId() {
      Object ref = serverMsgId_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        serverMsgId_ = s;
        return s;
      }
    }
    /**
     * <code>string serverMsgId = 8;</code>
     */
    public com.google.protobuf.ByteString
        getServerMsgIdBytes() {
      Object ref = serverMsgId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        serverMsgId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int MESSAGETIME_FIELD_NUMBER = 9;
    private long messageTime_;
    /**
     * <code>int64 messageTime = 9;</code>
     */
    public long getMessageTime() {
      return messageTime_;
    }

    private byte memoizedIsInitialized = -1;
    @Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (fromUser_ != null) {
        output.writeMessage(1, getFromUser());
      }
      for (int i = 0; i < toUser_.size(); i++) {
        output.writeMessage(2, toUser_.get(i));
      }
      if (conversationType_ != 0) {
        output.writeInt32(3, conversationType_);
      }
      if (action_ != 0) {
        output.writeInt32(4, action_);
      }
      if (!getLanguageBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 5, language_);
      }
      if (!getOriginalMsgIdBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 6, originalMsgId_);
      }
      if (!getActionMsgIdBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 7, actionMsgId_);
      }
      if (!getServerMsgIdBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 8, serverMsgId_);
      }
      if (messageTime_ != 0L) {
        output.writeInt64(9, messageTime_);
      }
      unknownFields.writeTo(output);
    }

    @Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (fromUser_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, getFromUser());
      }
      for (int i = 0; i < toUser_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, toUser_.get(i));
      }
      if (conversationType_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(3, conversationType_);
      }
      if (action_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(4, action_);
      }
      if (!getLanguageBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(5, language_);
      }
      if (!getOriginalMsgIdBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(6, originalMsgId_);
      }
      if (!getActionMsgIdBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(7, actionMsgId_);
      }
      if (!getServerMsgIdBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(8, serverMsgId_);
      }
      if (messageTime_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(9, messageTime_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @Override
    public boolean equals(final Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.ukelink.um.proto.Vmmheader.VmmHeader)) {
        return super.equals(obj);
      }
      com.ukelink.um.proto.Vmmheader.VmmHeader other = (com.ukelink.um.proto.Vmmheader.VmmHeader) obj;

      if (hasFromUser() != other.hasFromUser()) return false;
      if (hasFromUser()) {
        if (!getFromUser()
            .equals(other.getFromUser())) return false;
      }
      if (!getToUserList()
          .equals(other.getToUserList())) return false;
      if (getConversationType()
          != other.getConversationType()) return false;
      if (getAction()
          != other.getAction()) return false;
      if (!getLanguage()
          .equals(other.getLanguage())) return false;
      if (!getOriginalMsgId()
          .equals(other.getOriginalMsgId())) return false;
      if (!getActionMsgId()
          .equals(other.getActionMsgId())) return false;
      if (!getServerMsgId()
          .equals(other.getServerMsgId())) return false;
      if (getMessageTime()
          != other.getMessageTime()) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasFromUser()) {
        hash = (37 * hash) + FROMUSER_FIELD_NUMBER;
        hash = (53 * hash) + getFromUser().hashCode();
      }
      if (getToUserCount() > 0) {
        hash = (37 * hash) + TOUSER_FIELD_NUMBER;
        hash = (53 * hash) + getToUserList().hashCode();
      }
      hash = (37 * hash) + CONVERSATIONTYPE_FIELD_NUMBER;
      hash = (53 * hash) + getConversationType();
      hash = (37 * hash) + ACTION_FIELD_NUMBER;
      hash = (53 * hash) + getAction();
      hash = (37 * hash) + LANGUAGE_FIELD_NUMBER;
      hash = (53 * hash) + getLanguage().hashCode();
      hash = (37 * hash) + ORIGINALMSGID_FIELD_NUMBER;
      hash = (53 * hash) + getOriginalMsgId().hashCode();
      hash = (37 * hash) + ACTIONMSGID_FIELD_NUMBER;
      hash = (53 * hash) + getActionMsgId().hashCode();
      hash = (37 * hash) + SERVERMSGID_FIELD_NUMBER;
      hash = (53 * hash) + getServerMsgId().hashCode();
      hash = (37 * hash) + MESSAGETIME_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getMessageTime());
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.ukelink.um.proto.Vmmheader.VmmHeader parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.ukelink.um.proto.Vmmheader.VmmHeader parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.ukelink.um.proto.Vmmheader.VmmHeader parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.ukelink.um.proto.Vmmheader.VmmHeader parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.ukelink.um.proto.Vmmheader.VmmHeader parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.ukelink.um.proto.Vmmheader.VmmHeader parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.ukelink.um.proto.Vmmheader.VmmHeader parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.ukelink.um.proto.Vmmheader.VmmHeader parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.ukelink.um.proto.Vmmheader.VmmHeader parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.ukelink.um.proto.Vmmheader.VmmHeader parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.ukelink.um.proto.Vmmheader.VmmHeader parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.ukelink.um.proto.Vmmheader.VmmHeader parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.ukelink.um.proto.Vmmheader.VmmHeader prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * <pre>
     *import public "google/protobuf/timestamp.proto"; 
     * </pre>
     *
     * Protobuf type {@code com.ukelink.um.proto.VmmHeader}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:com.ukelink.um.proto.VmmHeader)
        com.ukelink.um.proto.Vmmheader.VmmHeaderOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return internal_static_com_ukelink_um_proto_VmmHeader_descriptor;
      }

      @Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return internal_static_com_ukelink_um_proto_VmmHeader_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.ukelink.um.proto.Vmmheader.VmmHeader.class, com.ukelink.um.proto.Vmmheader.VmmHeader.Builder.class);
      }

      // Construct using com.ukelink.um.proto.Vmmheader.VmmHeader.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
          getToUserFieldBuilder();
        }
      }
      @Override
      public Builder clear() {
        super.clear();
        if (fromUserBuilder_ == null) {
          fromUser_ = null;
        } else {
          fromUser_ = null;
          fromUserBuilder_ = null;
        }
        if (toUserBuilder_ == null) {
          toUser_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000002);
        } else {
          toUserBuilder_.clear();
        }
        conversationType_ = 0;

        action_ = 0;

        language_ = "";

        originalMsgId_ = "";

        actionMsgId_ = "";

        serverMsgId_ = "";

        messageTime_ = 0L;

        return this;
      }

      @Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return internal_static_com_ukelink_um_proto_VmmHeader_descriptor;
      }

      @Override
      public com.ukelink.um.proto.Vmmheader.VmmHeader getDefaultInstanceForType() {
        return getDefaultInstance();
      }

      @Override
      public com.ukelink.um.proto.Vmmheader.VmmHeader build() {
        com.ukelink.um.proto.Vmmheader.VmmHeader result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @Override
      public com.ukelink.um.proto.Vmmheader.VmmHeader buildPartial() {
        com.ukelink.um.proto.Vmmheader.VmmHeader result = new com.ukelink.um.proto.Vmmheader.VmmHeader(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (fromUserBuilder_ == null) {
          result.fromUser_ = fromUser_;
        } else {
          result.fromUser_ = fromUserBuilder_.build();
        }
        if (toUserBuilder_ == null) {
          if (((bitField0_ & 0x00000002) != 0)) {
            toUser_ = java.util.Collections.unmodifiableList(toUser_);
            bitField0_ = (bitField0_ & ~0x00000002);
          }
          result.toUser_ = toUser_;
        } else {
          result.toUser_ = toUserBuilder_.build();
        }
        result.conversationType_ = conversationType_;
        result.action_ = action_;
        result.language_ = language_;
        result.originalMsgId_ = originalMsgId_;
        result.actionMsgId_ = actionMsgId_;
        result.serverMsgId_ = serverMsgId_;
        result.messageTime_ = messageTime_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      @Override
      public Builder clone() {
        return super.clone();
      }
      @Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return super.setField(field, value);
      }
      @Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return super.addRepeatedField(field, value);
      }
      @Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.ukelink.um.proto.Vmmheader.VmmHeader) {
          return mergeFrom((com.ukelink.um.proto.Vmmheader.VmmHeader)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.ukelink.um.proto.Vmmheader.VmmHeader other) {
        if (other == getDefaultInstance()) return this;
        if (other.hasFromUser()) {
          mergeFromUser(other.getFromUser());
        }
        if (toUserBuilder_ == null) {
          if (!other.toUser_.isEmpty()) {
            if (toUser_.isEmpty()) {
              toUser_ = other.toUser_;
              bitField0_ = (bitField0_ & ~0x00000002);
            } else {
              ensureToUserIsMutable();
              toUser_.addAll(other.toUser_);
            }
            onChanged();
          }
        } else {
          if (!other.toUser_.isEmpty()) {
            if (toUserBuilder_.isEmpty()) {
              toUserBuilder_.dispose();
              toUserBuilder_ = null;
              toUser_ = other.toUser_;
              bitField0_ = (bitField0_ & ~0x00000002);
              toUserBuilder_ = 
                com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                   getToUserFieldBuilder() : null;
            } else {
              toUserBuilder_.addAllMessages(other.toUser_);
            }
          }
        }
        if (other.getConversationType() != 0) {
          setConversationType(other.getConversationType());
        }
        if (other.getAction() != 0) {
          setAction(other.getAction());
        }
        if (!other.getLanguage().isEmpty()) {
          language_ = other.language_;
          onChanged();
        }
        if (!other.getOriginalMsgId().isEmpty()) {
          originalMsgId_ = other.originalMsgId_;
          onChanged();
        }
        if (!other.getActionMsgId().isEmpty()) {
          actionMsgId_ = other.actionMsgId_;
          onChanged();
        }
        if (!other.getServerMsgId().isEmpty()) {
          serverMsgId_ = other.serverMsgId_;
          onChanged();
        }
        if (other.getMessageTime() != 0L) {
          setMessageTime(other.getMessageTime());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @Override
      public final boolean isInitialized() {
        return true;
      }

      @Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.ukelink.um.proto.Vmmheader.VmmHeader parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.ukelink.um.proto.Vmmheader.VmmHeader) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private com.ukelink.um.proto.Clientinfo.ClientInfo fromUser_;
      private com.google.protobuf.SingleFieldBuilderV3<
          com.ukelink.um.proto.Clientinfo.ClientInfo, com.ukelink.um.proto.Clientinfo.ClientInfo.Builder, com.ukelink.um.proto.Clientinfo.ClientInfoOrBuilder> fromUserBuilder_;
      /**
       * <code>.com.ukelink.um.proto.ClientInfo fromUser = 1;</code>
       */
      public boolean hasFromUser() {
        return fromUserBuilder_ != null || fromUser_ != null;
      }
      /**
       * <code>.com.ukelink.um.proto.ClientInfo fromUser = 1;</code>
       */
      public com.ukelink.um.proto.Clientinfo.ClientInfo getFromUser() {
        if (fromUserBuilder_ == null) {
          return fromUser_ == null ? com.ukelink.um.proto.Clientinfo.ClientInfo.getDefaultInstance() : fromUser_;
        } else {
          return fromUserBuilder_.getMessage();
        }
      }
      /**
       * <code>.com.ukelink.um.proto.ClientInfo fromUser = 1;</code>
       */
      public Builder setFromUser(com.ukelink.um.proto.Clientinfo.ClientInfo value) {
        if (fromUserBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          fromUser_ = value;
          onChanged();
        } else {
          fromUserBuilder_.setMessage(value);
        }

        return this;
      }
      /**
       * <code>.com.ukelink.um.proto.ClientInfo fromUser = 1;</code>
       */
      public Builder setFromUser(
          com.ukelink.um.proto.Clientinfo.ClientInfo.Builder builderForValue) {
        if (fromUserBuilder_ == null) {
          fromUser_ = builderForValue.build();
          onChanged();
        } else {
          fromUserBuilder_.setMessage(builderForValue.build());
        }

        return this;
      }
      /**
       * <code>.com.ukelink.um.proto.ClientInfo fromUser = 1;</code>
       */
      public Builder mergeFromUser(com.ukelink.um.proto.Clientinfo.ClientInfo value) {
        if (fromUserBuilder_ == null) {
          if (fromUser_ != null) {
            fromUser_ =
              com.ukelink.um.proto.Clientinfo.ClientInfo.newBuilder(fromUser_).mergeFrom(value).buildPartial();
          } else {
            fromUser_ = value;
          }
          onChanged();
        } else {
          fromUserBuilder_.mergeFrom(value);
        }

        return this;
      }
      /**
       * <code>.com.ukelink.um.proto.ClientInfo fromUser = 1;</code>
       */
      public Builder clearFromUser() {
        if (fromUserBuilder_ == null) {
          fromUser_ = null;
          onChanged();
        } else {
          fromUser_ = null;
          fromUserBuilder_ = null;
        }

        return this;
      }
      /**
       * <code>.com.ukelink.um.proto.ClientInfo fromUser = 1;</code>
       */
      public com.ukelink.um.proto.Clientinfo.ClientInfo.Builder getFromUserBuilder() {
        
        onChanged();
        return getFromUserFieldBuilder().getBuilder();
      }
      /**
       * <code>.com.ukelink.um.proto.ClientInfo fromUser = 1;</code>
       */
      public com.ukelink.um.proto.Clientinfo.ClientInfoOrBuilder getFromUserOrBuilder() {
        if (fromUserBuilder_ != null) {
          return fromUserBuilder_.getMessageOrBuilder();
        } else {
          return fromUser_ == null ?
              com.ukelink.um.proto.Clientinfo.ClientInfo.getDefaultInstance() : fromUser_;
        }
      }
      /**
       * <code>.com.ukelink.um.proto.ClientInfo fromUser = 1;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          com.ukelink.um.proto.Clientinfo.ClientInfo, com.ukelink.um.proto.Clientinfo.ClientInfo.Builder, com.ukelink.um.proto.Clientinfo.ClientInfoOrBuilder> 
          getFromUserFieldBuilder() {
        if (fromUserBuilder_ == null) {
          fromUserBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              com.ukelink.um.proto.Clientinfo.ClientInfo, com.ukelink.um.proto.Clientinfo.ClientInfo.Builder, com.ukelink.um.proto.Clientinfo.ClientInfoOrBuilder>(
                  getFromUser(),
                  getParentForChildren(),
                  isClean());
          fromUser_ = null;
        }
        return fromUserBuilder_;
      }

      private java.util.List<com.ukelink.um.proto.Clientinfo.ClientInfo> toUser_ =
        java.util.Collections.emptyList();
      private void ensureToUserIsMutable() {
        if (!((bitField0_ & 0x00000002) != 0)) {
          toUser_ = new java.util.ArrayList<com.ukelink.um.proto.Clientinfo.ClientInfo>(toUser_);
          bitField0_ |= 0x00000002;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilderV3<
          com.ukelink.um.proto.Clientinfo.ClientInfo, com.ukelink.um.proto.Clientinfo.ClientInfo.Builder, com.ukelink.um.proto.Clientinfo.ClientInfoOrBuilder> toUserBuilder_;

      /**
       * <code>repeated .com.ukelink.um.proto.ClientInfo toUser = 2;</code>
       */
      public java.util.List<com.ukelink.um.proto.Clientinfo.ClientInfo> getToUserList() {
        if (toUserBuilder_ == null) {
          return java.util.Collections.unmodifiableList(toUser_);
        } else {
          return toUserBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .com.ukelink.um.proto.ClientInfo toUser = 2;</code>
       */
      public int getToUserCount() {
        if (toUserBuilder_ == null) {
          return toUser_.size();
        } else {
          return toUserBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .com.ukelink.um.proto.ClientInfo toUser = 2;</code>
       */
      public com.ukelink.um.proto.Clientinfo.ClientInfo getToUser(int index) {
        if (toUserBuilder_ == null) {
          return toUser_.get(index);
        } else {
          return toUserBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .com.ukelink.um.proto.ClientInfo toUser = 2;</code>
       */
      public Builder setToUser(
          int index, com.ukelink.um.proto.Clientinfo.ClientInfo value) {
        if (toUserBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureToUserIsMutable();
          toUser_.set(index, value);
          onChanged();
        } else {
          toUserBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .com.ukelink.um.proto.ClientInfo toUser = 2;</code>
       */
      public Builder setToUser(
          int index, com.ukelink.um.proto.Clientinfo.ClientInfo.Builder builderForValue) {
        if (toUserBuilder_ == null) {
          ensureToUserIsMutable();
          toUser_.set(index, builderForValue.build());
          onChanged();
        } else {
          toUserBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .com.ukelink.um.proto.ClientInfo toUser = 2;</code>
       */
      public Builder addToUser(com.ukelink.um.proto.Clientinfo.ClientInfo value) {
        if (toUserBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureToUserIsMutable();
          toUser_.add(value);
          onChanged();
        } else {
          toUserBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .com.ukelink.um.proto.ClientInfo toUser = 2;</code>
       */
      public Builder addToUser(
          int index, com.ukelink.um.proto.Clientinfo.ClientInfo value) {
        if (toUserBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureToUserIsMutable();
          toUser_.add(index, value);
          onChanged();
        } else {
          toUserBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .com.ukelink.um.proto.ClientInfo toUser = 2;</code>
       */
      public Builder addToUser(
          com.ukelink.um.proto.Clientinfo.ClientInfo.Builder builderForValue) {
        if (toUserBuilder_ == null) {
          ensureToUserIsMutable();
          toUser_.add(builderForValue.build());
          onChanged();
        } else {
          toUserBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .com.ukelink.um.proto.ClientInfo toUser = 2;</code>
       */
      public Builder addToUser(
          int index, com.ukelink.um.proto.Clientinfo.ClientInfo.Builder builderForValue) {
        if (toUserBuilder_ == null) {
          ensureToUserIsMutable();
          toUser_.add(index, builderForValue.build());
          onChanged();
        } else {
          toUserBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .com.ukelink.um.proto.ClientInfo toUser = 2;</code>
       */
      public Builder addAllToUser(
          Iterable<? extends com.ukelink.um.proto.Clientinfo.ClientInfo> values) {
        if (toUserBuilder_ == null) {
          ensureToUserIsMutable();
          addAll(
              values, toUser_);
          onChanged();
        } else {
          toUserBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .com.ukelink.um.proto.ClientInfo toUser = 2;</code>
       */
      public Builder clearToUser() {
        if (toUserBuilder_ == null) {
          toUser_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000002);
          onChanged();
        } else {
          toUserBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .com.ukelink.um.proto.ClientInfo toUser = 2;</code>
       */
      public Builder removeToUser(int index) {
        if (toUserBuilder_ == null) {
          ensureToUserIsMutable();
          toUser_.remove(index);
          onChanged();
        } else {
          toUserBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .com.ukelink.um.proto.ClientInfo toUser = 2;</code>
       */
      public com.ukelink.um.proto.Clientinfo.ClientInfo.Builder getToUserBuilder(
          int index) {
        return getToUserFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .com.ukelink.um.proto.ClientInfo toUser = 2;</code>
       */
      public com.ukelink.um.proto.Clientinfo.ClientInfoOrBuilder getToUserOrBuilder(
          int index) {
        if (toUserBuilder_ == null) {
          return toUser_.get(index);  } else {
          return toUserBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .com.ukelink.um.proto.ClientInfo toUser = 2;</code>
       */
      public java.util.List<? extends com.ukelink.um.proto.Clientinfo.ClientInfoOrBuilder> 
           getToUserOrBuilderList() {
        if (toUserBuilder_ != null) {
          return toUserBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(toUser_);
        }
      }
      /**
       * <code>repeated .com.ukelink.um.proto.ClientInfo toUser = 2;</code>
       */
      public com.ukelink.um.proto.Clientinfo.ClientInfo.Builder addToUserBuilder() {
        return getToUserFieldBuilder().addBuilder(
            com.ukelink.um.proto.Clientinfo.ClientInfo.getDefaultInstance());
      }
      /**
       * <code>repeated .com.ukelink.um.proto.ClientInfo toUser = 2;</code>
       */
      public com.ukelink.um.proto.Clientinfo.ClientInfo.Builder addToUserBuilder(
          int index) {
        return getToUserFieldBuilder().addBuilder(
            index, com.ukelink.um.proto.Clientinfo.ClientInfo.getDefaultInstance());
      }
      /**
       * <code>repeated .com.ukelink.um.proto.ClientInfo toUser = 2;</code>
       */
      public java.util.List<com.ukelink.um.proto.Clientinfo.ClientInfo.Builder> 
           getToUserBuilderList() {
        return getToUserFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilderV3<
          com.ukelink.um.proto.Clientinfo.ClientInfo, com.ukelink.um.proto.Clientinfo.ClientInfo.Builder, com.ukelink.um.proto.Clientinfo.ClientInfoOrBuilder> 
          getToUserFieldBuilder() {
        if (toUserBuilder_ == null) {
          toUserBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
              com.ukelink.um.proto.Clientinfo.ClientInfo, com.ukelink.um.proto.Clientinfo.ClientInfo.Builder, com.ukelink.um.proto.Clientinfo.ClientInfoOrBuilder>(
                  toUser_,
                  ((bitField0_ & 0x00000002) != 0),
                  getParentForChildren(),
                  isClean());
          toUser_ = null;
        }
        return toUserBuilder_;
      }

      private int conversationType_ ;
      /**
       * <code>int32 conversationType = 3;</code>
       */
      public int getConversationType() {
        return conversationType_;
      }
      /**
       * <code>int32 conversationType = 3;</code>
       */
      public Builder setConversationType(int value) {
        
        conversationType_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 conversationType = 3;</code>
       */
      public Builder clearConversationType() {
        
        conversationType_ = 0;
        onChanged();
        return this;
      }

      private int action_ ;
      /**
       * <pre>
       *消息撤回
       * </pre>
       *
       * <code>int32 action = 4;</code>
       */
      public int getAction() {
        return action_;
      }
      /**
       * <pre>
       *消息撤回
       * </pre>
       *
       * <code>int32 action = 4;</code>
       */
      public Builder setAction(int value) {
        
        action_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *消息撤回
       * </pre>
       *
       * <code>int32 action = 4;</code>
       */
      public Builder clearAction() {
        
        action_ = 0;
        onChanged();
        return this;
      }

      private Object language_ = "";
      /**
       * <code>string language = 5;</code>
       */
      public String getLanguage() {
        Object ref = language_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          language_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <code>string language = 5;</code>
       */
      public com.google.protobuf.ByteString
          getLanguageBytes() {
        Object ref = language_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          language_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string language = 5;</code>
       */
      public Builder setLanguage(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        language_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string language = 5;</code>
       */
      public Builder clearLanguage() {
        
        language_ = getDefaultInstance().getLanguage();
        onChanged();
        return this;
      }
      /**
       * <code>string language = 5;</code>
       */
      public Builder setLanguageBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        language_ = value;
        onChanged();
        return this;
      }

      private Object originalMsgId_ = "";
      /**
       * <code>string originalMsgId = 6;</code>
       */
      public String getOriginalMsgId() {
        Object ref = originalMsgId_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          originalMsgId_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <code>string originalMsgId = 6;</code>
       */
      public com.google.protobuf.ByteString
          getOriginalMsgIdBytes() {
        Object ref = originalMsgId_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          originalMsgId_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string originalMsgId = 6;</code>
       */
      public Builder setOriginalMsgId(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        originalMsgId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string originalMsgId = 6;</code>
       */
      public Builder clearOriginalMsgId() {
        
        originalMsgId_ = getDefaultInstance().getOriginalMsgId();
        onChanged();
        return this;
      }
      /**
       * <code>string originalMsgId = 6;</code>
       */
      public Builder setOriginalMsgIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        originalMsgId_ = value;
        onChanged();
        return this;
      }

      private Object actionMsgId_ = "";
      /**
       * <code>string actionMsgId = 7;</code>
       */
      public String getActionMsgId() {
        Object ref = actionMsgId_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          actionMsgId_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <code>string actionMsgId = 7;</code>
       */
      public com.google.protobuf.ByteString
          getActionMsgIdBytes() {
        Object ref = actionMsgId_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          actionMsgId_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string actionMsgId = 7;</code>
       */
      public Builder setActionMsgId(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        actionMsgId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string actionMsgId = 7;</code>
       */
      public Builder clearActionMsgId() {
        
        actionMsgId_ = getDefaultInstance().getActionMsgId();
        onChanged();
        return this;
      }
      /**
       * <code>string actionMsgId = 7;</code>
       */
      public Builder setActionMsgIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        actionMsgId_ = value;
        onChanged();
        return this;
      }

      private Object serverMsgId_ = "";
      /**
       * <code>string serverMsgId = 8;</code>
       */
      public String getServerMsgId() {
        Object ref = serverMsgId_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          serverMsgId_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <code>string serverMsgId = 8;</code>
       */
      public com.google.protobuf.ByteString
          getServerMsgIdBytes() {
        Object ref = serverMsgId_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          serverMsgId_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string serverMsgId = 8;</code>
       */
      public Builder setServerMsgId(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        serverMsgId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string serverMsgId = 8;</code>
       */
      public Builder clearServerMsgId() {
        
        serverMsgId_ = getDefaultInstance().getServerMsgId();
        onChanged();
        return this;
      }
      /**
       * <code>string serverMsgId = 8;</code>
       */
      public Builder setServerMsgIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        serverMsgId_ = value;
        onChanged();
        return this;
      }

      private long messageTime_ ;
      /**
       * <code>int64 messageTime = 9;</code>
       */
      public long getMessageTime() {
        return messageTime_;
      }
      /**
       * <code>int64 messageTime = 9;</code>
       */
      public Builder setMessageTime(long value) {
        
        messageTime_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int64 messageTime = 9;</code>
       */
      public Builder clearMessageTime() {
        
        messageTime_ = 0L;
        onChanged();
        return this;
      }
      @Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:com.ukelink.um.proto.VmmHeader)
    }

    // @@protoc_insertion_point(class_scope:com.ukelink.um.proto.VmmHeader)
    private static final com.ukelink.um.proto.Vmmheader.VmmHeader DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.ukelink.um.proto.Vmmheader.VmmHeader();
    }

    public static com.ukelink.um.proto.Vmmheader.VmmHeader getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<VmmHeader>
        PARSER = new com.google.protobuf.AbstractParser<VmmHeader>() {
      @Override
      public VmmHeader parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new VmmHeader(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<VmmHeader> parser() {
      return PARSER;
    }

    @Override
    public com.google.protobuf.Parser<VmmHeader> getParserForType() {
      return PARSER;
    }

    @Override
    public com.ukelink.um.proto.Vmmheader.VmmHeader getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_ukelink_um_proto_VmmHeader_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_ukelink_um_proto_VmmHeader_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    String[] descriptorData = {
      "\n\017vmmheader.proto\022\024com.ukelink.um.proto\032" +
      "\020clientinfo.proto\"\203\002\n\tVmmHeader\0222\n\010fromU" +
      "ser\030\001 \001(\0132 .com.ukelink.um.proto.ClientI" +
      "nfo\0220\n\006toUser\030\002 \003(\0132 .com.ukelink.um.pro" +
      "to.ClientInfo\022\030\n\020conversationType\030\003 \001(\005\022" +
      "\016\n\006action\030\004 \001(\005\022\020\n\010language\030\005 \001(\t\022\025\n\rori" +
      "ginalMsgId\030\006 \001(\t\022\023\n\013actionMsgId\030\007 \001(\t\022\023\n" +
      "\013serverMsgId\030\010 \001(\t\022\023\n\013messageTime\030\t \001(\003b" +
      "\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.ukelink.um.proto.Clientinfo.getDescriptor(),
        }, assigner);
    internal_static_com_ukelink_um_proto_VmmHeader_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_ukelink_um_proto_VmmHeader_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_ukelink_um_proto_VmmHeader_descriptor,
        new String[] { "FromUser", "ToUser", "ConversationType", "Action", "Language", "OriginalMsgId", "ActionMsgId", "ServerMsgId", "MessageTime", });
    com.ukelink.um.proto.Clientinfo.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
