// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: accountinfo.proto

package com.ukelink.um.proto.login;

public final class Accountinfo {
  private Accountinfo() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface AccountInfoOrBuilder extends
      // @@protoc_insertion_point(interface_extends:com.ukelink.um.proto.login.AccountInfo)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string userCode = 1;</code>
     */
    String getUserCode();
    /**
     * <code>string userCode = 1;</code>
     */
    com.google.protobuf.ByteString
        getUserCodeBytes();

    /**
     * <code>string countryCode = 2;</code>
     */
    String getCountryCode();
    /**
     * <code>string countryCode = 2;</code>
     */
    com.google.protobuf.ByteString
        getCountryCodeBytes();

    /**
     * <code>string mvnoCode = 3;</code>
     */
    String getMvnoCode();
    /**
     * <code>string mvnoCode = 3;</code>
     */
    com.google.protobuf.ByteString
        getMvnoCodeBytes();

    /**
     * <pre>
     *msgCode
     * </pre>
     *
     * <code>string verifyCode = 4;</code>
     */
    String getVerifyCode();
    /**
     * <pre>
     *msgCode
     * </pre>
     *
     * <code>string verifyCode = 4;</code>
     */
    com.google.protobuf.ByteString
        getVerifyCodeBytes();

    /**
     * <code>string partnerCode = 5;</code>
     */
    String getPartnerCode();
    /**
     * <code>string partnerCode = 5;</code>
     */
    com.google.protobuf.ByteString
        getPartnerCodeBytes();

    /**
     * <code>string enterpriseCode = 6;</code>
     */
    String getEnterpriseCode();
    /**
     * <code>string enterpriseCode = 6;</code>
     */
    com.google.protobuf.ByteString
        getEnterpriseCodeBytes();

    /**
     * <code>string clientSecret = 7;</code>
     */
    String getClientSecret();
    /**
     * <code>string clientSecret = 7;</code>
     */
    com.google.protobuf.ByteString
        getClientSecretBytes();

    /**
     * <code>string password = 8;</code>
     */
    String getPassword();
    /**
     * <code>string password = 8;</code>
     */
    com.google.protobuf.ByteString
        getPasswordBytes();

    /**
     * <code>string aesKey = 9;</code>
     */
    String getAesKey();
    /**
     * <code>string aesKey = 9;</code>
     */
    com.google.protobuf.ByteString
        getAesKeyBytes();

    /**
     * <code>string ecdh = 10;</code>
     */
    String getEcdh();
    /**
     * <code>string ecdh = 10;</code>
     */
    com.google.protobuf.ByteString
        getEcdhBytes();
  }
  /**
   * Protobuf type {@code com.ukelink.um.proto.login.AccountInfo}
   */
  public  static final class AccountInfo extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:com.ukelink.um.proto.login.AccountInfo)
      AccountInfoOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use AccountInfo.newBuilder() to construct.
    private AccountInfo(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private AccountInfo() {
      userCode_ = "";
      countryCode_ = "";
      mvnoCode_ = "";
      verifyCode_ = "";
      partnerCode_ = "";
      enterpriseCode_ = "";
      clientSecret_ = "";
      password_ = "";
      aesKey_ = "";
      ecdh_ = "";
    }

    @Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private AccountInfo(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              String s = input.readStringRequireUtf8();

              userCode_ = s;
              break;
            }
            case 18: {
              String s = input.readStringRequireUtf8();

              countryCode_ = s;
              break;
            }
            case 26: {
              String s = input.readStringRequireUtf8();

              mvnoCode_ = s;
              break;
            }
            case 34: {
              String s = input.readStringRequireUtf8();

              verifyCode_ = s;
              break;
            }
            case 42: {
              String s = input.readStringRequireUtf8();

              partnerCode_ = s;
              break;
            }
            case 50: {
              String s = input.readStringRequireUtf8();

              enterpriseCode_ = s;
              break;
            }
            case 58: {
              String s = input.readStringRequireUtf8();

              clientSecret_ = s;
              break;
            }
            case 66: {
              String s = input.readStringRequireUtf8();

              password_ = s;
              break;
            }
            case 74: {
              String s = input.readStringRequireUtf8();

              aesKey_ = s;
              break;
            }
            case 82: {
              String s = input.readStringRequireUtf8();

              ecdh_ = s;
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return internal_static_com_ukelink_um_proto_login_AccountInfo_descriptor;
    }

    @Override
    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return internal_static_com_ukelink_um_proto_login_AccountInfo_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.ukelink.um.proto.login.Accountinfo.AccountInfo.class, com.ukelink.um.proto.login.Accountinfo.AccountInfo.Builder.class);
    }

    public static final int USERCODE_FIELD_NUMBER = 1;
    private volatile Object userCode_;
    /**
     * <code>string userCode = 1;</code>
     */
    public String getUserCode() {
      Object ref = userCode_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        userCode_ = s;
        return s;
      }
    }
    /**
     * <code>string userCode = 1;</code>
     */
    public com.google.protobuf.ByteString
        getUserCodeBytes() {
      Object ref = userCode_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        userCode_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int COUNTRYCODE_FIELD_NUMBER = 2;
    private volatile Object countryCode_;
    /**
     * <code>string countryCode = 2;</code>
     */
    public String getCountryCode() {
      Object ref = countryCode_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        countryCode_ = s;
        return s;
      }
    }
    /**
     * <code>string countryCode = 2;</code>
     */
    public com.google.protobuf.ByteString
        getCountryCodeBytes() {
      Object ref = countryCode_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        countryCode_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int MVNOCODE_FIELD_NUMBER = 3;
    private volatile Object mvnoCode_;
    /**
     * <code>string mvnoCode = 3;</code>
     */
    public String getMvnoCode() {
      Object ref = mvnoCode_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        mvnoCode_ = s;
        return s;
      }
    }
    /**
     * <code>string mvnoCode = 3;</code>
     */
    public com.google.protobuf.ByteString
        getMvnoCodeBytes() {
      Object ref = mvnoCode_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        mvnoCode_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int VERIFYCODE_FIELD_NUMBER = 4;
    private volatile Object verifyCode_;
    /**
     * <pre>
     *msgCode
     * </pre>
     *
     * <code>string verifyCode = 4;</code>
     */
    public String getVerifyCode() {
      Object ref = verifyCode_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        verifyCode_ = s;
        return s;
      }
    }
    /**
     * <pre>
     *msgCode
     * </pre>
     *
     * <code>string verifyCode = 4;</code>
     */
    public com.google.protobuf.ByteString
        getVerifyCodeBytes() {
      Object ref = verifyCode_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        verifyCode_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int PARTNERCODE_FIELD_NUMBER = 5;
    private volatile Object partnerCode_;
    /**
     * <code>string partnerCode = 5;</code>
     */
    public String getPartnerCode() {
      Object ref = partnerCode_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        partnerCode_ = s;
        return s;
      }
    }
    /**
     * <code>string partnerCode = 5;</code>
     */
    public com.google.protobuf.ByteString
        getPartnerCodeBytes() {
      Object ref = partnerCode_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        partnerCode_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int ENTERPRISECODE_FIELD_NUMBER = 6;
    private volatile Object enterpriseCode_;
    /**
     * <code>string enterpriseCode = 6;</code>
     */
    public String getEnterpriseCode() {
      Object ref = enterpriseCode_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        enterpriseCode_ = s;
        return s;
      }
    }
    /**
     * <code>string enterpriseCode = 6;</code>
     */
    public com.google.protobuf.ByteString
        getEnterpriseCodeBytes() {
      Object ref = enterpriseCode_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        enterpriseCode_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int CLIENTSECRET_FIELD_NUMBER = 7;
    private volatile Object clientSecret_;
    /**
     * <code>string clientSecret = 7;</code>
     */
    public String getClientSecret() {
      Object ref = clientSecret_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        clientSecret_ = s;
        return s;
      }
    }
    /**
     * <code>string clientSecret = 7;</code>
     */
    public com.google.protobuf.ByteString
        getClientSecretBytes() {
      Object ref = clientSecret_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        clientSecret_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int PASSWORD_FIELD_NUMBER = 8;
    private volatile Object password_;
    /**
     * <code>string password = 8;</code>
     */
    public String getPassword() {
      Object ref = password_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        password_ = s;
        return s;
      }
    }
    /**
     * <code>string password = 8;</code>
     */
    public com.google.protobuf.ByteString
        getPasswordBytes() {
      Object ref = password_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        password_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int AESKEY_FIELD_NUMBER = 9;
    private volatile Object aesKey_;
    /**
     * <code>string aesKey = 9;</code>
     */
    public String getAesKey() {
      Object ref = aesKey_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        aesKey_ = s;
        return s;
      }
    }
    /**
     * <code>string aesKey = 9;</code>
     */
    public com.google.protobuf.ByteString
        getAesKeyBytes() {
      Object ref = aesKey_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        aesKey_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int ECDH_FIELD_NUMBER = 10;
    private volatile Object ecdh_;
    /**
     * <code>string ecdh = 10;</code>
     */
    public String getEcdh() {
      Object ref = ecdh_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        ecdh_ = s;
        return s;
      }
    }
    /**
     * <code>string ecdh = 10;</code>
     */
    public com.google.protobuf.ByteString
        getEcdhBytes() {
      Object ref = ecdh_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        ecdh_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    @Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getUserCodeBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, userCode_);
      }
      if (!getCountryCodeBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, countryCode_);
      }
      if (!getMvnoCodeBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 3, mvnoCode_);
      }
      if (!getVerifyCodeBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 4, verifyCode_);
      }
      if (!getPartnerCodeBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 5, partnerCode_);
      }
      if (!getEnterpriseCodeBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 6, enterpriseCode_);
      }
      if (!getClientSecretBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 7, clientSecret_);
      }
      if (!getPasswordBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 8, password_);
      }
      if (!getAesKeyBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 9, aesKey_);
      }
      if (!getEcdhBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 10, ecdh_);
      }
      unknownFields.writeTo(output);
    }

    @Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getUserCodeBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, userCode_);
      }
      if (!getCountryCodeBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, countryCode_);
      }
      if (!getMvnoCodeBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, mvnoCode_);
      }
      if (!getVerifyCodeBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, verifyCode_);
      }
      if (!getPartnerCodeBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(5, partnerCode_);
      }
      if (!getEnterpriseCodeBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(6, enterpriseCode_);
      }
      if (!getClientSecretBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(7, clientSecret_);
      }
      if (!getPasswordBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(8, password_);
      }
      if (!getAesKeyBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(9, aesKey_);
      }
      if (!getEcdhBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(10, ecdh_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @Override
    public boolean equals(final Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.ukelink.um.proto.login.Accountinfo.AccountInfo)) {
        return super.equals(obj);
      }
      com.ukelink.um.proto.login.Accountinfo.AccountInfo other = (com.ukelink.um.proto.login.Accountinfo.AccountInfo) obj;

      if (!getUserCode()
          .equals(other.getUserCode())) return false;
      if (!getCountryCode()
          .equals(other.getCountryCode())) return false;
      if (!getMvnoCode()
          .equals(other.getMvnoCode())) return false;
      if (!getVerifyCode()
          .equals(other.getVerifyCode())) return false;
      if (!getPartnerCode()
          .equals(other.getPartnerCode())) return false;
      if (!getEnterpriseCode()
          .equals(other.getEnterpriseCode())) return false;
      if (!getClientSecret()
          .equals(other.getClientSecret())) return false;
      if (!getPassword()
          .equals(other.getPassword())) return false;
      if (!getAesKey()
          .equals(other.getAesKey())) return false;
      if (!getEcdh()
          .equals(other.getEcdh())) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + USERCODE_FIELD_NUMBER;
      hash = (53 * hash) + getUserCode().hashCode();
      hash = (37 * hash) + COUNTRYCODE_FIELD_NUMBER;
      hash = (53 * hash) + getCountryCode().hashCode();
      hash = (37 * hash) + MVNOCODE_FIELD_NUMBER;
      hash = (53 * hash) + getMvnoCode().hashCode();
      hash = (37 * hash) + VERIFYCODE_FIELD_NUMBER;
      hash = (53 * hash) + getVerifyCode().hashCode();
      hash = (37 * hash) + PARTNERCODE_FIELD_NUMBER;
      hash = (53 * hash) + getPartnerCode().hashCode();
      hash = (37 * hash) + ENTERPRISECODE_FIELD_NUMBER;
      hash = (53 * hash) + getEnterpriseCode().hashCode();
      hash = (37 * hash) + CLIENTSECRET_FIELD_NUMBER;
      hash = (53 * hash) + getClientSecret().hashCode();
      hash = (37 * hash) + PASSWORD_FIELD_NUMBER;
      hash = (53 * hash) + getPassword().hashCode();
      hash = (37 * hash) + AESKEY_FIELD_NUMBER;
      hash = (53 * hash) + getAesKey().hashCode();
      hash = (37 * hash) + ECDH_FIELD_NUMBER;
      hash = (53 * hash) + getEcdh().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.ukelink.um.proto.login.Accountinfo.AccountInfo parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.ukelink.um.proto.login.Accountinfo.AccountInfo parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.ukelink.um.proto.login.Accountinfo.AccountInfo parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.ukelink.um.proto.login.Accountinfo.AccountInfo parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.ukelink.um.proto.login.Accountinfo.AccountInfo parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.ukelink.um.proto.login.Accountinfo.AccountInfo parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.ukelink.um.proto.login.Accountinfo.AccountInfo parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.ukelink.um.proto.login.Accountinfo.AccountInfo parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.ukelink.um.proto.login.Accountinfo.AccountInfo parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.ukelink.um.proto.login.Accountinfo.AccountInfo parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.ukelink.um.proto.login.Accountinfo.AccountInfo parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.ukelink.um.proto.login.Accountinfo.AccountInfo parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.ukelink.um.proto.login.Accountinfo.AccountInfo prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @Override
    protected Builder newBuilderForType(
        BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.ukelink.um.proto.login.AccountInfo}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:com.ukelink.um.proto.login.AccountInfo)
        com.ukelink.um.proto.login.Accountinfo.AccountInfoOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return internal_static_com_ukelink_um_proto_login_AccountInfo_descriptor;
      }

      @Override
      protected FieldAccessorTable
          internalGetFieldAccessorTable() {
        return internal_static_com_ukelink_um_proto_login_AccountInfo_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.ukelink.um.proto.login.Accountinfo.AccountInfo.class, com.ukelink.um.proto.login.Accountinfo.AccountInfo.Builder.class);
      }

      // Construct using com.ukelink.um.proto.login.Accountinfo.AccountInfo.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @Override
      public Builder clear() {
        super.clear();
        userCode_ = "";

        countryCode_ = "";

        mvnoCode_ = "";

        verifyCode_ = "";

        partnerCode_ = "";

        enterpriseCode_ = "";

        clientSecret_ = "";

        password_ = "";

        aesKey_ = "";

        ecdh_ = "";

        return this;
      }

      @Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return internal_static_com_ukelink_um_proto_login_AccountInfo_descriptor;
      }

      @Override
      public com.ukelink.um.proto.login.Accountinfo.AccountInfo getDefaultInstanceForType() {
        return getDefaultInstance();
      }

      @Override
      public com.ukelink.um.proto.login.Accountinfo.AccountInfo build() {
        com.ukelink.um.proto.login.Accountinfo.AccountInfo result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @Override
      public com.ukelink.um.proto.login.Accountinfo.AccountInfo buildPartial() {
        com.ukelink.um.proto.login.Accountinfo.AccountInfo result = new com.ukelink.um.proto.login.Accountinfo.AccountInfo(this);
        result.userCode_ = userCode_;
        result.countryCode_ = countryCode_;
        result.mvnoCode_ = mvnoCode_;
        result.verifyCode_ = verifyCode_;
        result.partnerCode_ = partnerCode_;
        result.enterpriseCode_ = enterpriseCode_;
        result.clientSecret_ = clientSecret_;
        result.password_ = password_;
        result.aesKey_ = aesKey_;
        result.ecdh_ = ecdh_;
        onBuilt();
        return result;
      }

      @Override
      public Builder clone() {
        return super.clone();
      }
      @Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return super.setField(field, value);
      }
      @Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return super.addRepeatedField(field, value);
      }
      @Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.ukelink.um.proto.login.Accountinfo.AccountInfo) {
          return mergeFrom((com.ukelink.um.proto.login.Accountinfo.AccountInfo)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.ukelink.um.proto.login.Accountinfo.AccountInfo other) {
        if (other == getDefaultInstance()) return this;
        if (!other.getUserCode().isEmpty()) {
          userCode_ = other.userCode_;
          onChanged();
        }
        if (!other.getCountryCode().isEmpty()) {
          countryCode_ = other.countryCode_;
          onChanged();
        }
        if (!other.getMvnoCode().isEmpty()) {
          mvnoCode_ = other.mvnoCode_;
          onChanged();
        }
        if (!other.getVerifyCode().isEmpty()) {
          verifyCode_ = other.verifyCode_;
          onChanged();
        }
        if (!other.getPartnerCode().isEmpty()) {
          partnerCode_ = other.partnerCode_;
          onChanged();
        }
        if (!other.getEnterpriseCode().isEmpty()) {
          enterpriseCode_ = other.enterpriseCode_;
          onChanged();
        }
        if (!other.getClientSecret().isEmpty()) {
          clientSecret_ = other.clientSecret_;
          onChanged();
        }
        if (!other.getPassword().isEmpty()) {
          password_ = other.password_;
          onChanged();
        }
        if (!other.getAesKey().isEmpty()) {
          aesKey_ = other.aesKey_;
          onChanged();
        }
        if (!other.getEcdh().isEmpty()) {
          ecdh_ = other.ecdh_;
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @Override
      public final boolean isInitialized() {
        return true;
      }

      @Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.ukelink.um.proto.login.Accountinfo.AccountInfo parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.ukelink.um.proto.login.Accountinfo.AccountInfo) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private Object userCode_ = "";
      /**
       * <code>string userCode = 1;</code>
       */
      public String getUserCode() {
        Object ref = userCode_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          userCode_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <code>string userCode = 1;</code>
       */
      public com.google.protobuf.ByteString
          getUserCodeBytes() {
        Object ref = userCode_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          userCode_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string userCode = 1;</code>
       */
      public Builder setUserCode(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        userCode_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string userCode = 1;</code>
       */
      public Builder clearUserCode() {
        
        userCode_ = getDefaultInstance().getUserCode();
        onChanged();
        return this;
      }
      /**
       * <code>string userCode = 1;</code>
       */
      public Builder setUserCodeBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        userCode_ = value;
        onChanged();
        return this;
      }

      private Object countryCode_ = "";
      /**
       * <code>string countryCode = 2;</code>
       */
      public String getCountryCode() {
        Object ref = countryCode_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          countryCode_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <code>string countryCode = 2;</code>
       */
      public com.google.protobuf.ByteString
          getCountryCodeBytes() {
        Object ref = countryCode_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          countryCode_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string countryCode = 2;</code>
       */
      public Builder setCountryCode(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        countryCode_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string countryCode = 2;</code>
       */
      public Builder clearCountryCode() {
        
        countryCode_ = getDefaultInstance().getCountryCode();
        onChanged();
        return this;
      }
      /**
       * <code>string countryCode = 2;</code>
       */
      public Builder setCountryCodeBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        countryCode_ = value;
        onChanged();
        return this;
      }

      private Object mvnoCode_ = "";
      /**
       * <code>string mvnoCode = 3;</code>
       */
      public String getMvnoCode() {
        Object ref = mvnoCode_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          mvnoCode_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <code>string mvnoCode = 3;</code>
       */
      public com.google.protobuf.ByteString
          getMvnoCodeBytes() {
        Object ref = mvnoCode_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          mvnoCode_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string mvnoCode = 3;</code>
       */
      public Builder setMvnoCode(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        mvnoCode_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string mvnoCode = 3;</code>
       */
      public Builder clearMvnoCode() {
        
        mvnoCode_ = getDefaultInstance().getMvnoCode();
        onChanged();
        return this;
      }
      /**
       * <code>string mvnoCode = 3;</code>
       */
      public Builder setMvnoCodeBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        mvnoCode_ = value;
        onChanged();
        return this;
      }

      private Object verifyCode_ = "";
      /**
       * <pre>
       *msgCode
       * </pre>
       *
       * <code>string verifyCode = 4;</code>
       */
      public String getVerifyCode() {
        Object ref = verifyCode_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          verifyCode_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <pre>
       *msgCode
       * </pre>
       *
       * <code>string verifyCode = 4;</code>
       */
      public com.google.protobuf.ByteString
          getVerifyCodeBytes() {
        Object ref = verifyCode_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          verifyCode_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       *msgCode
       * </pre>
       *
       * <code>string verifyCode = 4;</code>
       */
      public Builder setVerifyCode(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        verifyCode_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *msgCode
       * </pre>
       *
       * <code>string verifyCode = 4;</code>
       */
      public Builder clearVerifyCode() {
        
        verifyCode_ = getDefaultInstance().getVerifyCode();
        onChanged();
        return this;
      }
      /**
       * <pre>
       *msgCode
       * </pre>
       *
       * <code>string verifyCode = 4;</code>
       */
      public Builder setVerifyCodeBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        verifyCode_ = value;
        onChanged();
        return this;
      }

      private Object partnerCode_ = "";
      /**
       * <code>string partnerCode = 5;</code>
       */
      public String getPartnerCode() {
        Object ref = partnerCode_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          partnerCode_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <code>string partnerCode = 5;</code>
       */
      public com.google.protobuf.ByteString
          getPartnerCodeBytes() {
        Object ref = partnerCode_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          partnerCode_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string partnerCode = 5;</code>
       */
      public Builder setPartnerCode(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        partnerCode_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string partnerCode = 5;</code>
       */
      public Builder clearPartnerCode() {
        
        partnerCode_ = getDefaultInstance().getPartnerCode();
        onChanged();
        return this;
      }
      /**
       * <code>string partnerCode = 5;</code>
       */
      public Builder setPartnerCodeBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        partnerCode_ = value;
        onChanged();
        return this;
      }

      private Object enterpriseCode_ = "";
      /**
       * <code>string enterpriseCode = 6;</code>
       */
      public String getEnterpriseCode() {
        Object ref = enterpriseCode_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          enterpriseCode_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <code>string enterpriseCode = 6;</code>
       */
      public com.google.protobuf.ByteString
          getEnterpriseCodeBytes() {
        Object ref = enterpriseCode_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          enterpriseCode_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string enterpriseCode = 6;</code>
       */
      public Builder setEnterpriseCode(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        enterpriseCode_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string enterpriseCode = 6;</code>
       */
      public Builder clearEnterpriseCode() {
        
        enterpriseCode_ = getDefaultInstance().getEnterpriseCode();
        onChanged();
        return this;
      }
      /**
       * <code>string enterpriseCode = 6;</code>
       */
      public Builder setEnterpriseCodeBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        enterpriseCode_ = value;
        onChanged();
        return this;
      }

      private Object clientSecret_ = "";
      /**
       * <code>string clientSecret = 7;</code>
       */
      public String getClientSecret() {
        Object ref = clientSecret_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          clientSecret_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <code>string clientSecret = 7;</code>
       */
      public com.google.protobuf.ByteString
          getClientSecretBytes() {
        Object ref = clientSecret_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          clientSecret_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string clientSecret = 7;</code>
       */
      public Builder setClientSecret(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        clientSecret_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string clientSecret = 7;</code>
       */
      public Builder clearClientSecret() {
        
        clientSecret_ = getDefaultInstance().getClientSecret();
        onChanged();
        return this;
      }
      /**
       * <code>string clientSecret = 7;</code>
       */
      public Builder setClientSecretBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        clientSecret_ = value;
        onChanged();
        return this;
      }

      private Object password_ = "";
      /**
       * <code>string password = 8;</code>
       */
      public String getPassword() {
        Object ref = password_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          password_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <code>string password = 8;</code>
       */
      public com.google.protobuf.ByteString
          getPasswordBytes() {
        Object ref = password_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          password_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string password = 8;</code>
       */
      public Builder setPassword(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        password_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string password = 8;</code>
       */
      public Builder clearPassword() {
        
        password_ = getDefaultInstance().getPassword();
        onChanged();
        return this;
      }
      /**
       * <code>string password = 8;</code>
       */
      public Builder setPasswordBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        password_ = value;
        onChanged();
        return this;
      }

      private Object aesKey_ = "";
      /**
       * <code>string aesKey = 9;</code>
       */
      public String getAesKey() {
        Object ref = aesKey_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          aesKey_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <code>string aesKey = 9;</code>
       */
      public com.google.protobuf.ByteString
          getAesKeyBytes() {
        Object ref = aesKey_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          aesKey_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string aesKey = 9;</code>
       */
      public Builder setAesKey(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        aesKey_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string aesKey = 9;</code>
       */
      public Builder clearAesKey() {
        
        aesKey_ = getDefaultInstance().getAesKey();
        onChanged();
        return this;
      }
      /**
       * <code>string aesKey = 9;</code>
       */
      public Builder setAesKeyBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        aesKey_ = value;
        onChanged();
        return this;
      }

      private Object ecdh_ = "";
      /**
       * <code>string ecdh = 10;</code>
       */
      public String getEcdh() {
        Object ref = ecdh_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          ecdh_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <code>string ecdh = 10;</code>
       */
      public com.google.protobuf.ByteString
          getEcdhBytes() {
        Object ref = ecdh_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          ecdh_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string ecdh = 10;</code>
       */
      public Builder setEcdh(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        ecdh_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string ecdh = 10;</code>
       */
      public Builder clearEcdh() {
        
        ecdh_ = getDefaultInstance().getEcdh();
        onChanged();
        return this;
      }
      /**
       * <code>string ecdh = 10;</code>
       */
      public Builder setEcdhBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        ecdh_ = value;
        onChanged();
        return this;
      }
      @Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:com.ukelink.um.proto.login.AccountInfo)
    }

    // @@protoc_insertion_point(class_scope:com.ukelink.um.proto.login.AccountInfo)
    private static final com.ukelink.um.proto.login.Accountinfo.AccountInfo DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.ukelink.um.proto.login.Accountinfo.AccountInfo();
    }

    public static com.ukelink.um.proto.login.Accountinfo.AccountInfo getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<AccountInfo>
        PARSER = new com.google.protobuf.AbstractParser<AccountInfo>() {
      @Override
      public AccountInfo parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new AccountInfo(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<AccountInfo> parser() {
      return PARSER;
    }

    @Override
    public com.google.protobuf.Parser<AccountInfo> getParserForType() {
      return PARSER;
    }

    @Override
    public com.ukelink.um.proto.login.Accountinfo.AccountInfo getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_ukelink_um_proto_login_AccountInfo_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_ukelink_um_proto_login_AccountInfo_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    String[] descriptorData = {
      "\n\021accountinfo.proto\022\032com.ukelink.um.prot" +
      "o.login\"\315\001\n\013AccountInfo\022\020\n\010userCode\030\001 \001(" +
      "\t\022\023\n\013countryCode\030\002 \001(\t\022\020\n\010mvnoCode\030\003 \001(\t" +
      "\022\022\n\nverifyCode\030\004 \001(\t\022\023\n\013partnerCode\030\005 \001(" +
      "\t\022\026\n\016enterpriseCode\030\006 \001(\t\022\024\n\014clientSecre" +
      "t\030\007 \001(\t\022\020\n\010password\030\010 \001(\t\022\016\n\006aesKey\030\t \001(" +
      "\t\022\014\n\004ecdh\030\n \001(\tb\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_com_ukelink_um_proto_login_AccountInfo_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_ukelink_um_proto_login_AccountInfo_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_ukelink_um_proto_login_AccountInfo_descriptor,
        new String[] { "UserCode", "CountryCode", "MvnoCode", "VerifyCode", "PartnerCode", "EnterpriseCode", "ClientSecret", "Password", "AesKey", "Ecdh", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
