// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: deviceinfo.proto

package com.ukelink.um.proto.login;

public final class Deviceinfo {
  private Deviceinfo() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface DeviceInfoOrBuilder extends
      // @@protoc_insertion_point(interface_extends:com.ukelink.um.proto.login.DeviceInfo)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string deviceId = 1;</code>
     */
    String getDeviceId();
    /**
     * <code>string deviceId = 1;</code>
     */
    com.google.protobuf.ByteString
        getDeviceIdBytes();

    /**
     * <code>string deviceType = 2;</code>
     */
    String getDeviceType();
    /**
     * <code>string deviceType = 2;</code>
     */
    com.google.protobuf.ByteString
        getDeviceTypeBytes();

    /**
     * <code>string hardwareVersion = 3;</code>
     */
    String getHardwareVersion();
    /**
     * <code>string hardwareVersion = 3;</code>
     */
    com.google.protobuf.ByteString
        getHardwareVersionBytes();

    /**
     * <code>string mobileBrand = 4;</code>
     */
    String getMobileBrand();
    /**
     * <code>string mobileBrand = 4;</code>
     */
    com.google.protobuf.ByteString
        getMobileBrandBytes();

    /**
     * <code>string softVersion = 5;</code>
     */
    String getSoftVersion();
    /**
     * <code>string softVersion = 5;</code>
     */
    com.google.protobuf.ByteString
        getSoftVersionBytes();

    /**
     * <code>string systemVersion = 6;</code>
     */
    String getSystemVersion();
    /**
     * <code>string systemVersion = 6;</code>
     */
    com.google.protobuf.ByteString
        getSystemVersionBytes();

    /**
     * <code>string imsi = 7;</code>
     */
    String getImsi();
    /**
     * <code>string imsi = 7;</code>
     */
    com.google.protobuf.ByteString
        getImsiBytes();

    /**
     * <code>string imei = 8;</code>
     */
    String getImei();
    /**
     * <code>string imei = 8;</code>
     */
    com.google.protobuf.ByteString
        getImeiBytes();

    /**
     * <code>string langType = 9;</code>
     */
    String getLangType();
    /**
     * <code>string langType = 9;</code>
     */
    com.google.protobuf.ByteString
        getLangTypeBytes();

    /**
     * <code>string pushPlatform = 10;</code>
     */
    String getPushPlatform();
    /**
     * <code>string pushPlatform = 10;</code>
     */
    com.google.protobuf.ByteString
        getPushPlatformBytes();

    /**
     * <code>string pushtoken = 11;</code>
     */
    String getPushtoken();
    /**
     * <code>string pushtoken = 11;</code>
     */
    com.google.protobuf.ByteString
        getPushtokenBytes();

    /**
     * <code>string pushtokenType = 12;</code>
     */
    String getPushtokenType();
    /**
     * <code>string pushtokenType = 12;</code>
     */
    com.google.protobuf.ByteString
        getPushtokenTypeBytes();
  }
  /**
   * Protobuf type {@code com.ukelink.um.proto.login.DeviceInfo}
   */
  public  static final class DeviceInfo extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:com.ukelink.um.proto.login.DeviceInfo)
      DeviceInfoOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use DeviceInfo.newBuilder() to construct.
    private DeviceInfo(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private DeviceInfo() {
      deviceId_ = "";
      deviceType_ = "";
      hardwareVersion_ = "";
      mobileBrand_ = "";
      softVersion_ = "";
      systemVersion_ = "";
      imsi_ = "";
      imei_ = "";
      langType_ = "";
      pushPlatform_ = "";
      pushtoken_ = "";
      pushtokenType_ = "";
    }

    @Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private DeviceInfo(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              String s = input.readStringRequireUtf8();

              deviceId_ = s;
              break;
            }
            case 18: {
              String s = input.readStringRequireUtf8();

              deviceType_ = s;
              break;
            }
            case 26: {
              String s = input.readStringRequireUtf8();

              hardwareVersion_ = s;
              break;
            }
            case 34: {
              String s = input.readStringRequireUtf8();

              mobileBrand_ = s;
              break;
            }
            case 42: {
              String s = input.readStringRequireUtf8();

              softVersion_ = s;
              break;
            }
            case 50: {
              String s = input.readStringRequireUtf8();

              systemVersion_ = s;
              break;
            }
            case 58: {
              String s = input.readStringRequireUtf8();

              imsi_ = s;
              break;
            }
            case 66: {
              String s = input.readStringRequireUtf8();

              imei_ = s;
              break;
            }
            case 74: {
              String s = input.readStringRequireUtf8();

              langType_ = s;
              break;
            }
            case 82: {
              String s = input.readStringRequireUtf8();

              pushPlatform_ = s;
              break;
            }
            case 90: {
              String s = input.readStringRequireUtf8();

              pushtoken_ = s;
              break;
            }
            case 98: {
              String s = input.readStringRequireUtf8();

              pushtokenType_ = s;
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return internal_static_com_ukelink_um_proto_login_DeviceInfo_descriptor;
    }

    @Override
    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return internal_static_com_ukelink_um_proto_login_DeviceInfo_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.ukelink.um.proto.login.Deviceinfo.DeviceInfo.class, com.ukelink.um.proto.login.Deviceinfo.DeviceInfo.Builder.class);
    }

    public static final int DEVICEID_FIELD_NUMBER = 1;
    private volatile Object deviceId_;
    /**
     * <code>string deviceId = 1;</code>
     */
    public String getDeviceId() {
      Object ref = deviceId_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        deviceId_ = s;
        return s;
      }
    }
    /**
     * <code>string deviceId = 1;</code>
     */
    public com.google.protobuf.ByteString
        getDeviceIdBytes() {
      Object ref = deviceId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        deviceId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int DEVICETYPE_FIELD_NUMBER = 2;
    private volatile Object deviceType_;
    /**
     * <code>string deviceType = 2;</code>
     */
    public String getDeviceType() {
      Object ref = deviceType_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        deviceType_ = s;
        return s;
      }
    }
    /**
     * <code>string deviceType = 2;</code>
     */
    public com.google.protobuf.ByteString
        getDeviceTypeBytes() {
      Object ref = deviceType_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        deviceType_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int HARDWAREVERSION_FIELD_NUMBER = 3;
    private volatile Object hardwareVersion_;
    /**
     * <code>string hardwareVersion = 3;</code>
     */
    public String getHardwareVersion() {
      Object ref = hardwareVersion_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        hardwareVersion_ = s;
        return s;
      }
    }
    /**
     * <code>string hardwareVersion = 3;</code>
     */
    public com.google.protobuf.ByteString
        getHardwareVersionBytes() {
      Object ref = hardwareVersion_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        hardwareVersion_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int MOBILEBRAND_FIELD_NUMBER = 4;
    private volatile Object mobileBrand_;
    /**
     * <code>string mobileBrand = 4;</code>
     */
    public String getMobileBrand() {
      Object ref = mobileBrand_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        mobileBrand_ = s;
        return s;
      }
    }
    /**
     * <code>string mobileBrand = 4;</code>
     */
    public com.google.protobuf.ByteString
        getMobileBrandBytes() {
      Object ref = mobileBrand_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        mobileBrand_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int SOFTVERSION_FIELD_NUMBER = 5;
    private volatile Object softVersion_;
    /**
     * <code>string softVersion = 5;</code>
     */
    public String getSoftVersion() {
      Object ref = softVersion_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        softVersion_ = s;
        return s;
      }
    }
    /**
     * <code>string softVersion = 5;</code>
     */
    public com.google.protobuf.ByteString
        getSoftVersionBytes() {
      Object ref = softVersion_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        softVersion_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int SYSTEMVERSION_FIELD_NUMBER = 6;
    private volatile Object systemVersion_;
    /**
     * <code>string systemVersion = 6;</code>
     */
    public String getSystemVersion() {
      Object ref = systemVersion_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        systemVersion_ = s;
        return s;
      }
    }
    /**
     * <code>string systemVersion = 6;</code>
     */
    public com.google.protobuf.ByteString
        getSystemVersionBytes() {
      Object ref = systemVersion_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        systemVersion_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int IMSI_FIELD_NUMBER = 7;
    private volatile Object imsi_;
    /**
     * <code>string imsi = 7;</code>
     */
    public String getImsi() {
      Object ref = imsi_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        imsi_ = s;
        return s;
      }
    }
    /**
     * <code>string imsi = 7;</code>
     */
    public com.google.protobuf.ByteString
        getImsiBytes() {
      Object ref = imsi_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        imsi_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int IMEI_FIELD_NUMBER = 8;
    private volatile Object imei_;
    /**
     * <code>string imei = 8;</code>
     */
    public String getImei() {
      Object ref = imei_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        imei_ = s;
        return s;
      }
    }
    /**
     * <code>string imei = 8;</code>
     */
    public com.google.protobuf.ByteString
        getImeiBytes() {
      Object ref = imei_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        imei_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int LANGTYPE_FIELD_NUMBER = 9;
    private volatile Object langType_;
    /**
     * <code>string langType = 9;</code>
     */
    public String getLangType() {
      Object ref = langType_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        langType_ = s;
        return s;
      }
    }
    /**
     * <code>string langType = 9;</code>
     */
    public com.google.protobuf.ByteString
        getLangTypeBytes() {
      Object ref = langType_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        langType_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int PUSHPLATFORM_FIELD_NUMBER = 10;
    private volatile Object pushPlatform_;
    /**
     * <code>string pushPlatform = 10;</code>
     */
    public String getPushPlatform() {
      Object ref = pushPlatform_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        pushPlatform_ = s;
        return s;
      }
    }
    /**
     * <code>string pushPlatform = 10;</code>
     */
    public com.google.protobuf.ByteString
        getPushPlatformBytes() {
      Object ref = pushPlatform_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        pushPlatform_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int PUSHTOKEN_FIELD_NUMBER = 11;
    private volatile Object pushtoken_;
    /**
     * <code>string pushtoken = 11;</code>
     */
    public String getPushtoken() {
      Object ref = pushtoken_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        pushtoken_ = s;
        return s;
      }
    }
    /**
     * <code>string pushtoken = 11;</code>
     */
    public com.google.protobuf.ByteString
        getPushtokenBytes() {
      Object ref = pushtoken_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        pushtoken_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int PUSHTOKENTYPE_FIELD_NUMBER = 12;
    private volatile Object pushtokenType_;
    /**
     * <code>string pushtokenType = 12;</code>
     */
    public String getPushtokenType() {
      Object ref = pushtokenType_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        pushtokenType_ = s;
        return s;
      }
    }
    /**
     * <code>string pushtokenType = 12;</code>
     */
    public com.google.protobuf.ByteString
        getPushtokenTypeBytes() {
      Object ref = pushtokenType_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        pushtokenType_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    @Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getDeviceIdBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, deviceId_);
      }
      if (!getDeviceTypeBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, deviceType_);
      }
      if (!getHardwareVersionBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 3, hardwareVersion_);
      }
      if (!getMobileBrandBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 4, mobileBrand_);
      }
      if (!getSoftVersionBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 5, softVersion_);
      }
      if (!getSystemVersionBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 6, systemVersion_);
      }
      if (!getImsiBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 7, imsi_);
      }
      if (!getImeiBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 8, imei_);
      }
      if (!getLangTypeBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 9, langType_);
      }
      if (!getPushPlatformBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 10, pushPlatform_);
      }
      if (!getPushtokenBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 11, pushtoken_);
      }
      if (!getPushtokenTypeBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 12, pushtokenType_);
      }
      unknownFields.writeTo(output);
    }

    @Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getDeviceIdBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, deviceId_);
      }
      if (!getDeviceTypeBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, deviceType_);
      }
      if (!getHardwareVersionBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, hardwareVersion_);
      }
      if (!getMobileBrandBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, mobileBrand_);
      }
      if (!getSoftVersionBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(5, softVersion_);
      }
      if (!getSystemVersionBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(6, systemVersion_);
      }
      if (!getImsiBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(7, imsi_);
      }
      if (!getImeiBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(8, imei_);
      }
      if (!getLangTypeBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(9, langType_);
      }
      if (!getPushPlatformBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(10, pushPlatform_);
      }
      if (!getPushtokenBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(11, pushtoken_);
      }
      if (!getPushtokenTypeBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(12, pushtokenType_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @Override
    public boolean equals(final Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.ukelink.um.proto.login.Deviceinfo.DeviceInfo)) {
        return super.equals(obj);
      }
      com.ukelink.um.proto.login.Deviceinfo.DeviceInfo other = (com.ukelink.um.proto.login.Deviceinfo.DeviceInfo) obj;

      if (!getDeviceId()
          .equals(other.getDeviceId())) return false;
      if (!getDeviceType()
          .equals(other.getDeviceType())) return false;
      if (!getHardwareVersion()
          .equals(other.getHardwareVersion())) return false;
      if (!getMobileBrand()
          .equals(other.getMobileBrand())) return false;
      if (!getSoftVersion()
          .equals(other.getSoftVersion())) return false;
      if (!getSystemVersion()
          .equals(other.getSystemVersion())) return false;
      if (!getImsi()
          .equals(other.getImsi())) return false;
      if (!getImei()
          .equals(other.getImei())) return false;
      if (!getLangType()
          .equals(other.getLangType())) return false;
      if (!getPushPlatform()
          .equals(other.getPushPlatform())) return false;
      if (!getPushtoken()
          .equals(other.getPushtoken())) return false;
      if (!getPushtokenType()
          .equals(other.getPushtokenType())) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + DEVICEID_FIELD_NUMBER;
      hash = (53 * hash) + getDeviceId().hashCode();
      hash = (37 * hash) + DEVICETYPE_FIELD_NUMBER;
      hash = (53 * hash) + getDeviceType().hashCode();
      hash = (37 * hash) + HARDWAREVERSION_FIELD_NUMBER;
      hash = (53 * hash) + getHardwareVersion().hashCode();
      hash = (37 * hash) + MOBILEBRAND_FIELD_NUMBER;
      hash = (53 * hash) + getMobileBrand().hashCode();
      hash = (37 * hash) + SOFTVERSION_FIELD_NUMBER;
      hash = (53 * hash) + getSoftVersion().hashCode();
      hash = (37 * hash) + SYSTEMVERSION_FIELD_NUMBER;
      hash = (53 * hash) + getSystemVersion().hashCode();
      hash = (37 * hash) + IMSI_FIELD_NUMBER;
      hash = (53 * hash) + getImsi().hashCode();
      hash = (37 * hash) + IMEI_FIELD_NUMBER;
      hash = (53 * hash) + getImei().hashCode();
      hash = (37 * hash) + LANGTYPE_FIELD_NUMBER;
      hash = (53 * hash) + getLangType().hashCode();
      hash = (37 * hash) + PUSHPLATFORM_FIELD_NUMBER;
      hash = (53 * hash) + getPushPlatform().hashCode();
      hash = (37 * hash) + PUSHTOKEN_FIELD_NUMBER;
      hash = (53 * hash) + getPushtoken().hashCode();
      hash = (37 * hash) + PUSHTOKENTYPE_FIELD_NUMBER;
      hash = (53 * hash) + getPushtokenType().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.ukelink.um.proto.login.Deviceinfo.DeviceInfo parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.ukelink.um.proto.login.Deviceinfo.DeviceInfo parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.ukelink.um.proto.login.Deviceinfo.DeviceInfo parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.ukelink.um.proto.login.Deviceinfo.DeviceInfo parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.ukelink.um.proto.login.Deviceinfo.DeviceInfo parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.ukelink.um.proto.login.Deviceinfo.DeviceInfo parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.ukelink.um.proto.login.Deviceinfo.DeviceInfo parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.ukelink.um.proto.login.Deviceinfo.DeviceInfo parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.ukelink.um.proto.login.Deviceinfo.DeviceInfo parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.ukelink.um.proto.login.Deviceinfo.DeviceInfo parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.ukelink.um.proto.login.Deviceinfo.DeviceInfo parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.ukelink.um.proto.login.Deviceinfo.DeviceInfo parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.ukelink.um.proto.login.Deviceinfo.DeviceInfo prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @Override
    protected Builder newBuilderForType(
        BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.ukelink.um.proto.login.DeviceInfo}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:com.ukelink.um.proto.login.DeviceInfo)
        com.ukelink.um.proto.login.Deviceinfo.DeviceInfoOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return internal_static_com_ukelink_um_proto_login_DeviceInfo_descriptor;
      }

      @Override
      protected FieldAccessorTable
          internalGetFieldAccessorTable() {
        return internal_static_com_ukelink_um_proto_login_DeviceInfo_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.ukelink.um.proto.login.Deviceinfo.DeviceInfo.class, com.ukelink.um.proto.login.Deviceinfo.DeviceInfo.Builder.class);
      }

      // Construct using com.ukelink.um.proto.login.Deviceinfo.DeviceInfo.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @Override
      public Builder clear() {
        super.clear();
        deviceId_ = "";

        deviceType_ = "";

        hardwareVersion_ = "";

        mobileBrand_ = "";

        softVersion_ = "";

        systemVersion_ = "";

        imsi_ = "";

        imei_ = "";

        langType_ = "";

        pushPlatform_ = "";

        pushtoken_ = "";

        pushtokenType_ = "";

        return this;
      }

      @Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return internal_static_com_ukelink_um_proto_login_DeviceInfo_descriptor;
      }

      @Override
      public com.ukelink.um.proto.login.Deviceinfo.DeviceInfo getDefaultInstanceForType() {
        return getDefaultInstance();
      }

      @Override
      public com.ukelink.um.proto.login.Deviceinfo.DeviceInfo build() {
        com.ukelink.um.proto.login.Deviceinfo.DeviceInfo result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @Override
      public com.ukelink.um.proto.login.Deviceinfo.DeviceInfo buildPartial() {
        com.ukelink.um.proto.login.Deviceinfo.DeviceInfo result = new com.ukelink.um.proto.login.Deviceinfo.DeviceInfo(this);
        result.deviceId_ = deviceId_;
        result.deviceType_ = deviceType_;
        result.hardwareVersion_ = hardwareVersion_;
        result.mobileBrand_ = mobileBrand_;
        result.softVersion_ = softVersion_;
        result.systemVersion_ = systemVersion_;
        result.imsi_ = imsi_;
        result.imei_ = imei_;
        result.langType_ = langType_;
        result.pushPlatform_ = pushPlatform_;
        result.pushtoken_ = pushtoken_;
        result.pushtokenType_ = pushtokenType_;
        onBuilt();
        return result;
      }

      @Override
      public Builder clone() {
        return super.clone();
      }
      @Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return super.setField(field, value);
      }
      @Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return super.addRepeatedField(field, value);
      }
      @Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.ukelink.um.proto.login.Deviceinfo.DeviceInfo) {
          return mergeFrom((com.ukelink.um.proto.login.Deviceinfo.DeviceInfo)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.ukelink.um.proto.login.Deviceinfo.DeviceInfo other) {
        if (other == getDefaultInstance()) return this;
        if (!other.getDeviceId().isEmpty()) {
          deviceId_ = other.deviceId_;
          onChanged();
        }
        if (!other.getDeviceType().isEmpty()) {
          deviceType_ = other.deviceType_;
          onChanged();
        }
        if (!other.getHardwareVersion().isEmpty()) {
          hardwareVersion_ = other.hardwareVersion_;
          onChanged();
        }
        if (!other.getMobileBrand().isEmpty()) {
          mobileBrand_ = other.mobileBrand_;
          onChanged();
        }
        if (!other.getSoftVersion().isEmpty()) {
          softVersion_ = other.softVersion_;
          onChanged();
        }
        if (!other.getSystemVersion().isEmpty()) {
          systemVersion_ = other.systemVersion_;
          onChanged();
        }
        if (!other.getImsi().isEmpty()) {
          imsi_ = other.imsi_;
          onChanged();
        }
        if (!other.getImei().isEmpty()) {
          imei_ = other.imei_;
          onChanged();
        }
        if (!other.getLangType().isEmpty()) {
          langType_ = other.langType_;
          onChanged();
        }
        if (!other.getPushPlatform().isEmpty()) {
          pushPlatform_ = other.pushPlatform_;
          onChanged();
        }
        if (!other.getPushtoken().isEmpty()) {
          pushtoken_ = other.pushtoken_;
          onChanged();
        }
        if (!other.getPushtokenType().isEmpty()) {
          pushtokenType_ = other.pushtokenType_;
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @Override
      public final boolean isInitialized() {
        return true;
      }

      @Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.ukelink.um.proto.login.Deviceinfo.DeviceInfo parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.ukelink.um.proto.login.Deviceinfo.DeviceInfo) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private Object deviceId_ = "";
      /**
       * <code>string deviceId = 1;</code>
       */
      public String getDeviceId() {
        Object ref = deviceId_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          deviceId_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <code>string deviceId = 1;</code>
       */
      public com.google.protobuf.ByteString
          getDeviceIdBytes() {
        Object ref = deviceId_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          deviceId_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string deviceId = 1;</code>
       */
      public Builder setDeviceId(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        deviceId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string deviceId = 1;</code>
       */
      public Builder clearDeviceId() {
        
        deviceId_ = getDefaultInstance().getDeviceId();
        onChanged();
        return this;
      }
      /**
       * <code>string deviceId = 1;</code>
       */
      public Builder setDeviceIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        deviceId_ = value;
        onChanged();
        return this;
      }

      private Object deviceType_ = "";
      /**
       * <code>string deviceType = 2;</code>
       */
      public String getDeviceType() {
        Object ref = deviceType_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          deviceType_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <code>string deviceType = 2;</code>
       */
      public com.google.protobuf.ByteString
          getDeviceTypeBytes() {
        Object ref = deviceType_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          deviceType_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string deviceType = 2;</code>
       */
      public Builder setDeviceType(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        deviceType_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string deviceType = 2;</code>
       */
      public Builder clearDeviceType() {
        
        deviceType_ = getDefaultInstance().getDeviceType();
        onChanged();
        return this;
      }
      /**
       * <code>string deviceType = 2;</code>
       */
      public Builder setDeviceTypeBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        deviceType_ = value;
        onChanged();
        return this;
      }

      private Object hardwareVersion_ = "";
      /**
       * <code>string hardwareVersion = 3;</code>
       */
      public String getHardwareVersion() {
        Object ref = hardwareVersion_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          hardwareVersion_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <code>string hardwareVersion = 3;</code>
       */
      public com.google.protobuf.ByteString
          getHardwareVersionBytes() {
        Object ref = hardwareVersion_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          hardwareVersion_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string hardwareVersion = 3;</code>
       */
      public Builder setHardwareVersion(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        hardwareVersion_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string hardwareVersion = 3;</code>
       */
      public Builder clearHardwareVersion() {
        
        hardwareVersion_ = getDefaultInstance().getHardwareVersion();
        onChanged();
        return this;
      }
      /**
       * <code>string hardwareVersion = 3;</code>
       */
      public Builder setHardwareVersionBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        hardwareVersion_ = value;
        onChanged();
        return this;
      }

      private Object mobileBrand_ = "";
      /**
       * <code>string mobileBrand = 4;</code>
       */
      public String getMobileBrand() {
        Object ref = mobileBrand_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          mobileBrand_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <code>string mobileBrand = 4;</code>
       */
      public com.google.protobuf.ByteString
          getMobileBrandBytes() {
        Object ref = mobileBrand_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          mobileBrand_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string mobileBrand = 4;</code>
       */
      public Builder setMobileBrand(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        mobileBrand_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string mobileBrand = 4;</code>
       */
      public Builder clearMobileBrand() {
        
        mobileBrand_ = getDefaultInstance().getMobileBrand();
        onChanged();
        return this;
      }
      /**
       * <code>string mobileBrand = 4;</code>
       */
      public Builder setMobileBrandBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        mobileBrand_ = value;
        onChanged();
        return this;
      }

      private Object softVersion_ = "";
      /**
       * <code>string softVersion = 5;</code>
       */
      public String getSoftVersion() {
        Object ref = softVersion_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          softVersion_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <code>string softVersion = 5;</code>
       */
      public com.google.protobuf.ByteString
          getSoftVersionBytes() {
        Object ref = softVersion_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          softVersion_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string softVersion = 5;</code>
       */
      public Builder setSoftVersion(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        softVersion_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string softVersion = 5;</code>
       */
      public Builder clearSoftVersion() {
        
        softVersion_ = getDefaultInstance().getSoftVersion();
        onChanged();
        return this;
      }
      /**
       * <code>string softVersion = 5;</code>
       */
      public Builder setSoftVersionBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        softVersion_ = value;
        onChanged();
        return this;
      }

      private Object systemVersion_ = "";
      /**
       * <code>string systemVersion = 6;</code>
       */
      public String getSystemVersion() {
        Object ref = systemVersion_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          systemVersion_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <code>string systemVersion = 6;</code>
       */
      public com.google.protobuf.ByteString
          getSystemVersionBytes() {
        Object ref = systemVersion_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          systemVersion_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string systemVersion = 6;</code>
       */
      public Builder setSystemVersion(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        systemVersion_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string systemVersion = 6;</code>
       */
      public Builder clearSystemVersion() {
        
        systemVersion_ = getDefaultInstance().getSystemVersion();
        onChanged();
        return this;
      }
      /**
       * <code>string systemVersion = 6;</code>
       */
      public Builder setSystemVersionBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        systemVersion_ = value;
        onChanged();
        return this;
      }

      private Object imsi_ = "";
      /**
       * <code>string imsi = 7;</code>
       */
      public String getImsi() {
        Object ref = imsi_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          imsi_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <code>string imsi = 7;</code>
       */
      public com.google.protobuf.ByteString
          getImsiBytes() {
        Object ref = imsi_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          imsi_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string imsi = 7;</code>
       */
      public Builder setImsi(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        imsi_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string imsi = 7;</code>
       */
      public Builder clearImsi() {
        
        imsi_ = getDefaultInstance().getImsi();
        onChanged();
        return this;
      }
      /**
       * <code>string imsi = 7;</code>
       */
      public Builder setImsiBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        imsi_ = value;
        onChanged();
        return this;
      }

      private Object imei_ = "";
      /**
       * <code>string imei = 8;</code>
       */
      public String getImei() {
        Object ref = imei_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          imei_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <code>string imei = 8;</code>
       */
      public com.google.protobuf.ByteString
          getImeiBytes() {
        Object ref = imei_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          imei_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string imei = 8;</code>
       */
      public Builder setImei(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        imei_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string imei = 8;</code>
       */
      public Builder clearImei() {
        
        imei_ = getDefaultInstance().getImei();
        onChanged();
        return this;
      }
      /**
       * <code>string imei = 8;</code>
       */
      public Builder setImeiBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        imei_ = value;
        onChanged();
        return this;
      }

      private Object langType_ = "";
      /**
       * <code>string langType = 9;</code>
       */
      public String getLangType() {
        Object ref = langType_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          langType_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <code>string langType = 9;</code>
       */
      public com.google.protobuf.ByteString
          getLangTypeBytes() {
        Object ref = langType_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          langType_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string langType = 9;</code>
       */
      public Builder setLangType(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        langType_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string langType = 9;</code>
       */
      public Builder clearLangType() {
        
        langType_ = getDefaultInstance().getLangType();
        onChanged();
        return this;
      }
      /**
       * <code>string langType = 9;</code>
       */
      public Builder setLangTypeBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        langType_ = value;
        onChanged();
        return this;
      }

      private Object pushPlatform_ = "";
      /**
       * <code>string pushPlatform = 10;</code>
       */
      public String getPushPlatform() {
        Object ref = pushPlatform_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          pushPlatform_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <code>string pushPlatform = 10;</code>
       */
      public com.google.protobuf.ByteString
          getPushPlatformBytes() {
        Object ref = pushPlatform_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          pushPlatform_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string pushPlatform = 10;</code>
       */
      public Builder setPushPlatform(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        pushPlatform_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string pushPlatform = 10;</code>
       */
      public Builder clearPushPlatform() {
        
        pushPlatform_ = getDefaultInstance().getPushPlatform();
        onChanged();
        return this;
      }
      /**
       * <code>string pushPlatform = 10;</code>
       */
      public Builder setPushPlatformBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        pushPlatform_ = value;
        onChanged();
        return this;
      }

      private Object pushtoken_ = "";
      /**
       * <code>string pushtoken = 11;</code>
       */
      public String getPushtoken() {
        Object ref = pushtoken_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          pushtoken_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <code>string pushtoken = 11;</code>
       */
      public com.google.protobuf.ByteString
          getPushtokenBytes() {
        Object ref = pushtoken_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          pushtoken_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string pushtoken = 11;</code>
       */
      public Builder setPushtoken(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        pushtoken_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string pushtoken = 11;</code>
       */
      public Builder clearPushtoken() {
        
        pushtoken_ = getDefaultInstance().getPushtoken();
        onChanged();
        return this;
      }
      /**
       * <code>string pushtoken = 11;</code>
       */
      public Builder setPushtokenBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        pushtoken_ = value;
        onChanged();
        return this;
      }

      private Object pushtokenType_ = "";
      /**
       * <code>string pushtokenType = 12;</code>
       */
      public String getPushtokenType() {
        Object ref = pushtokenType_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          pushtokenType_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <code>string pushtokenType = 12;</code>
       */
      public com.google.protobuf.ByteString
          getPushtokenTypeBytes() {
        Object ref = pushtokenType_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          pushtokenType_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string pushtokenType = 12;</code>
       */
      public Builder setPushtokenType(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        pushtokenType_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string pushtokenType = 12;</code>
       */
      public Builder clearPushtokenType() {
        
        pushtokenType_ = getDefaultInstance().getPushtokenType();
        onChanged();
        return this;
      }
      /**
       * <code>string pushtokenType = 12;</code>
       */
      public Builder setPushtokenTypeBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        pushtokenType_ = value;
        onChanged();
        return this;
      }
      @Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:com.ukelink.um.proto.login.DeviceInfo)
    }

    // @@protoc_insertion_point(class_scope:com.ukelink.um.proto.login.DeviceInfo)
    private static final com.ukelink.um.proto.login.Deviceinfo.DeviceInfo DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.ukelink.um.proto.login.Deviceinfo.DeviceInfo();
    }

    public static com.ukelink.um.proto.login.Deviceinfo.DeviceInfo getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<DeviceInfo>
        PARSER = new com.google.protobuf.AbstractParser<DeviceInfo>() {
      @Override
      public DeviceInfo parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new DeviceInfo(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<DeviceInfo> parser() {
      return PARSER;
    }

    @Override
    public com.google.protobuf.Parser<DeviceInfo> getParserForType() {
      return PARSER;
    }

    @Override
    public com.ukelink.um.proto.login.Deviceinfo.DeviceInfo getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_ukelink_um_proto_login_DeviceInfo_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_ukelink_um_proto_login_DeviceInfo_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    String[] descriptorData = {
      "\n\020deviceinfo.proto\022\032com.ukelink.um.proto" +
      ".login\"\372\001\n\nDeviceInfo\022\020\n\010deviceId\030\001 \001(\t\022" +
      "\022\n\ndeviceType\030\002 \001(\t\022\027\n\017hardwareVersion\030\003" +
      " \001(\t\022\023\n\013mobileBrand\030\004 \001(\t\022\023\n\013softVersion" +
      "\030\005 \001(\t\022\025\n\rsystemVersion\030\006 \001(\t\022\014\n\004imsi\030\007 " +
      "\001(\t\022\014\n\004imei\030\010 \001(\t\022\020\n\010langType\030\t \001(\t\022\024\n\014p" +
      "ushPlatform\030\n \001(\t\022\021\n\tpushtoken\030\013 \001(\t\022\025\n\r" +
      "pushtokenType\030\014 \001(\tb\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_com_ukelink_um_proto_login_DeviceInfo_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_ukelink_um_proto_login_DeviceInfo_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_ukelink_um_proto_login_DeviceInfo_descriptor,
        new String[] { "DeviceId", "DeviceType", "HardwareVersion", "MobileBrand", "SoftVersion", "SystemVersion", "Imsi", "Imei", "LangType", "PushPlatform", "Pushtoken", "PushtokenType", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
