// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: TestProtocol2.proto

package io.netty.example.worldclock;

public final class TestProtocol2 {
    private TestProtocol2() {}
    public static void registerAllExtensions(
            com.google.protobuf.ExtensionRegistryLite registry) {
    }

    public static void registerAllExtensions(
            com.google.protobuf.ExtensionRegistry registry) {
        registerAllExtensions(
                (com.google.protobuf.ExtensionRegistryLite) registry);
    }
    public interface RichManOrBuilder extends
            // @@protoc_insertion_point(interface_extends:io.netty.example.worldclock.RichMan)
            com.google.protobuf.MessageOrBuilder {

        /**
         * <code>int32 id = 1;</code>
         */
        int getId();

        /**
         * <code>string name = 2;</code>
         */
        java.lang.String getName();
        /**
         * <code>string name = 2;</code>
         */
        com.google.protobuf.ByteString
        getNameBytes();

        /**
         * <code>string email = 3;</code>
         */
        java.lang.String getEmail();
        /**
         * <code>string email = 3;</code>
         */
        com.google.protobuf.ByteString
        getEmailBytes();

        /**
         * <code>repeated .io.netty.example.worldclock.RichMan.Car cars = 4;</code>
         */
        java.util.List<io.netty.example.worldclock.TestProtocol2.RichMan.Car>
        getCarsList();
        /**
         * <code>repeated .io.netty.example.worldclock.RichMan.Car cars = 4;</code>
         */
        io.netty.example.worldclock.TestProtocol2.RichMan.Car getCars(int index);
        /**
         * <code>repeated .io.netty.example.worldclock.RichMan.Car cars = 4;</code>
         */
        int getCarsCount();
        /**
         * <code>repeated .io.netty.example.worldclock.RichMan.Car cars = 4;</code>
         */
        java.util.List<? extends io.netty.example.worldclock.TestProtocol2.RichMan.CarOrBuilder>
        getCarsOrBuilderList();
        /**
         * <code>repeated .io.netty.example.worldclock.RichMan.Car cars = 4;</code>
         */
        io.netty.example.worldclock.TestProtocol2.RichMan.CarOrBuilder getCarsOrBuilder(
                int index);
    }
    /**
     * Protobuf type {@code io.netty.example.worldclock.RichMan}
     */
    public  static final class RichMan extends
            com.google.protobuf.GeneratedMessageV3 implements
            // @@protoc_insertion_point(message_implements:io.netty.example.worldclock.RichMan)
            RichManOrBuilder {
        private static final long serialVersionUID = 0L;
        // Use RichMan.newBuilder() to construct.
        private RichMan(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
            super(builder);
        }
        private RichMan() {
            name_ = "";
            email_ = "";
            cars_ = java.util.Collections.emptyList();
        }

        @java.lang.Override
        public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
            return this.unknownFields;
        }
        private RichMan(
                com.google.protobuf.CodedInputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            this();
            if (extensionRegistry == null) {
                throw new java.lang.NullPointerException();
            }
            int mutable_bitField0_ = 0;
            com.google.protobuf.UnknownFieldSet.Builder unknownFields =
                    com.google.protobuf.UnknownFieldSet.newBuilder();
            try {
                boolean done = false;
                while (!done) {
                    int tag = input.readTag();
                    switch (tag) {
                        case 0:
                            done = true;
                            break;
                        case 8: {

                            id_ = input.readInt32();
                            break;
                        }
                        case 18: {
                            java.lang.String s = input.readStringRequireUtf8();

                            name_ = s;
                            break;
                        }
                        case 26: {
                            java.lang.String s = input.readStringRequireUtf8();

                            email_ = s;
                            break;
                        }
                        case 34: {
                            if (!((mutable_bitField0_ & 0x00000008) != 0)) {
                                cars_ = new java.util.ArrayList<io.netty.example.worldclock.TestProtocol2.RichMan.Car>();
                                mutable_bitField0_ |= 0x00000008;
                            }
                            cars_.add(
                                    input.readMessage(io.netty.example.worldclock.TestProtocol2.RichMan.Car.parser(), extensionRegistry));
                            break;
                        }
                        default: {
                            if (!parseUnknownField(
                                    input, unknownFields, extensionRegistry, tag)) {
                                done = true;
                            }
                            break;
                        }
                    }
                }
            } catch (com.google.protobuf.InvalidProtocolBufferException e) {
                throw e.setUnfinishedMessage(this);
            } catch (java.io.IOException e) {
                throw new com.google.protobuf.InvalidProtocolBufferException(
                        e).setUnfinishedMessage(this);
            } finally {
                if (((mutable_bitField0_ & 0x00000008) != 0)) {
                    cars_ = java.util.Collections.unmodifiableList(cars_);
                }
                this.unknownFields = unknownFields.build();
                makeExtensionsImmutable();
            }
        }
        public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
            return io.netty.example.worldclock.TestProtocol2.internal_static_io_netty_example_worldclock_RichMan_descriptor;
        }

        @java.lang.Override
        protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
            return io.netty.example.worldclock.TestProtocol2.internal_static_io_netty_example_worldclock_RichMan_fieldAccessorTable
                    .ensureFieldAccessorsInitialized(
                            io.netty.example.worldclock.TestProtocol2.RichMan.class, io.netty.example.worldclock.TestProtocol2.RichMan.Builder.class);
        }

        /**
         * Protobuf enum {@code io.netty.example.worldclock.RichMan.CarType}
         */
        public enum CarType
                implements com.google.protobuf.ProtocolMessageEnum {
            /**
             * <code>AUDI = 0;</code>
             */
            AUDI(0),
            /**
             * <code>BENZ = 1;</code>
             */
            BENZ(1),
            /**
             * <code>LAMBORGHINI = 2;</code>
             */
            LAMBORGHINI(2),
            /**
             * <code>DASAUTO = 3;</code>
             */
            DASAUTO(3),
            UNRECOGNIZED(-1),
            ;

            /**
             * <code>AUDI = 0;</code>
             */
            public static final int AUDI_VALUE = 0;
            /**
             * <code>BENZ = 1;</code>
             */
            public static final int BENZ_VALUE = 1;
            /**
             * <code>LAMBORGHINI = 2;</code>
             */
            public static final int LAMBORGHINI_VALUE = 2;
            /**
             * <code>DASAUTO = 3;</code>
             */
            public static final int DASAUTO_VALUE = 3;


            public final int getNumber() {
                if (this == UNRECOGNIZED) {
                    throw new java.lang.IllegalArgumentException(
                            "Can't get the number of an unknown enum value.");
                }
                return value;
            }

            /**
             * @deprecated Use {@link #forNumber(int)} instead.
             */
            @java.lang.Deprecated
            public static CarType valueOf(int value) {
                return forNumber(value);
            }

            public static CarType forNumber(int value) {
                switch (value) {
                    case 0: return AUDI;
                    case 1: return BENZ;
                    case 2: return LAMBORGHINI;
                    case 3: return DASAUTO;
                    default: return null;
                }
            }

            public static com.google.protobuf.Internal.EnumLiteMap<CarType>
            internalGetValueMap() {
                return internalValueMap;
            }
            private static final com.google.protobuf.Internal.EnumLiteMap<
                    CarType> internalValueMap =
                    new com.google.protobuf.Internal.EnumLiteMap<CarType>() {
                        public CarType findValueByNumber(int number) {
                            return CarType.forNumber(number);
                        }
                    };

            public final com.google.protobuf.Descriptors.EnumValueDescriptor
            getValueDescriptor() {
                return getDescriptor().getValues().get(ordinal());
            }
            public final com.google.protobuf.Descriptors.EnumDescriptor
            getDescriptorForType() {
                return getDescriptor();
            }
            public static final com.google.protobuf.Descriptors.EnumDescriptor
            getDescriptor() {
                return io.netty.example.worldclock.TestProtocol2.RichMan.getDescriptor().getEnumTypes().get(0);
            }

            private static final CarType[] VALUES = values();

            public static CarType valueOf(
                    com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
                if (desc.getType() != getDescriptor()) {
                    throw new java.lang.IllegalArgumentException(
                            "EnumValueDescriptor is not for this type.");
                }
                if (desc.getIndex() == -1) {
                    return UNRECOGNIZED;
                }
                return VALUES[desc.getIndex()];
            }

            private final int value;

            private CarType(int value) {
                this.value = value;
            }

            // @@protoc_insertion_point(enum_scope:io.netty.example.worldclock.RichMan.CarType)
        }

        public interface CarOrBuilder extends
                // @@protoc_insertion_point(interface_extends:io.netty.example.worldclock.RichMan.Car)
                com.google.protobuf.MessageOrBuilder {

            /**
             * <code>string name = 1;</code>
             */
            java.lang.String getName();
            /**
             * <code>string name = 1;</code>
             */
            com.google.protobuf.ByteString
            getNameBytes();

            /**
             * <code>.io.netty.example.worldclock.RichMan.CarType type = 2;</code>
             */
            int getTypeValue();
            /**
             * <code>.io.netty.example.worldclock.RichMan.CarType type = 2;</code>
             */
            io.netty.example.worldclock.TestProtocol2.RichMan.CarType getType();
        }
        /**
         * Protobuf type {@code io.netty.example.worldclock.RichMan.Car}
         */
        public  static final class Car extends
                com.google.protobuf.GeneratedMessageV3 implements
                // @@protoc_insertion_point(message_implements:io.netty.example.worldclock.RichMan.Car)
                CarOrBuilder {
            private static final long serialVersionUID = 0L;
            // Use Car.newBuilder() to construct.
            private Car(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
                super(builder);
            }
            private Car() {
                name_ = "";
                type_ = 0;
            }

            @java.lang.Override
            public final com.google.protobuf.UnknownFieldSet
            getUnknownFields() {
                return this.unknownFields;
            }
            private Car(
                    com.google.protobuf.CodedInputStream input,
                    com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                    throws com.google.protobuf.InvalidProtocolBufferException {
                this();
                if (extensionRegistry == null) {
                    throw new java.lang.NullPointerException();
                }
                int mutable_bitField0_ = 0;
                com.google.protobuf.UnknownFieldSet.Builder unknownFields =
                        com.google.protobuf.UnknownFieldSet.newBuilder();
                try {
                    boolean done = false;
                    while (!done) {
                        int tag = input.readTag();
                        switch (tag) {
                            case 0:
                                done = true;
                                break;
                            case 10: {
                                java.lang.String s = input.readStringRequireUtf8();

                                name_ = s;
                                break;
                            }
                            case 16: {
                                int rawValue = input.readEnum();

                                type_ = rawValue;
                                break;
                            }
                            default: {
                                if (!parseUnknownField(
                                        input, unknownFields, extensionRegistry, tag)) {
                                    done = true;
                                }
                                break;
                            }
                        }
                    }
                } catch (com.google.protobuf.InvalidProtocolBufferException e) {
                    throw e.setUnfinishedMessage(this);
                } catch (java.io.IOException e) {
                    throw new com.google.protobuf.InvalidProtocolBufferException(
                            e).setUnfinishedMessage(this);
                } finally {
                    this.unknownFields = unknownFields.build();
                    makeExtensionsImmutable();
                }
            }
            public static final com.google.protobuf.Descriptors.Descriptor
            getDescriptor() {
                return io.netty.example.worldclock.TestProtocol2.internal_static_io_netty_example_worldclock_RichMan_Car_descriptor;
            }

            @java.lang.Override
            protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
            internalGetFieldAccessorTable() {
                return io.netty.example.worldclock.TestProtocol2.internal_static_io_netty_example_worldclock_RichMan_Car_fieldAccessorTable
                        .ensureFieldAccessorsInitialized(
                                io.netty.example.worldclock.TestProtocol2.RichMan.Car.class, io.netty.example.worldclock.TestProtocol2.RichMan.Car.Builder.class);
            }

            public static final int NAME_FIELD_NUMBER = 1;
            private volatile java.lang.Object name_;
            /**
             * <code>string name = 1;</code>
             */
            public java.lang.String getName() {
                java.lang.Object ref = name_;
                if (ref instanceof java.lang.String) {
                    return (java.lang.String) ref;
                } else {
                    com.google.protobuf.ByteString bs =
                            (com.google.protobuf.ByteString) ref;
                    java.lang.String s = bs.toStringUtf8();
                    name_ = s;
                    return s;
                }
            }
            /**
             * <code>string name = 1;</code>
             */
            public com.google.protobuf.ByteString
            getNameBytes() {
                java.lang.Object ref = name_;
                if (ref instanceof java.lang.String) {
                    com.google.protobuf.ByteString b =
                            com.google.protobuf.ByteString.copyFromUtf8(
                                    (java.lang.String) ref);
                    name_ = b;
                    return b;
                } else {
                    return (com.google.protobuf.ByteString) ref;
                }
            }

            public static final int TYPE_FIELD_NUMBER = 2;
            private int type_;
            /**
             * <code>.io.netty.example.worldclock.RichMan.CarType type = 2;</code>
             */
            public int getTypeValue() {
                return type_;
            }
            /**
             * <code>.io.netty.example.worldclock.RichMan.CarType type = 2;</code>
             */
            public io.netty.example.worldclock.TestProtocol2.RichMan.CarType getType() {
                @SuppressWarnings("deprecation")
                io.netty.example.worldclock.TestProtocol2.RichMan.CarType result = io.netty.example.worldclock.TestProtocol2.RichMan.CarType.valueOf(type_);
                return result == null ? io.netty.example.worldclock.TestProtocol2.RichMan.CarType.UNRECOGNIZED : result;
            }

            private byte memoizedIsInitialized = -1;
            @java.lang.Override
            public final boolean isInitialized() {
                byte isInitialized = memoizedIsInitialized;
                if (isInitialized == 1) return true;
                if (isInitialized == 0) return false;

                memoizedIsInitialized = 1;
                return true;
            }

            @java.lang.Override
            public void writeTo(com.google.protobuf.CodedOutputStream output)
                    throws java.io.IOException {
                if (!getNameBytes().isEmpty()) {
                    com.google.protobuf.GeneratedMessageV3.writeString(output, 1, name_);
                }
                if (type_ != io.netty.example.worldclock.TestProtocol2.RichMan.CarType.AUDI.getNumber()) {
                    output.writeEnum(2, type_);
                }
                unknownFields.writeTo(output);
            }

            @java.lang.Override
            public int getSerializedSize() {
                int size = memoizedSize;
                if (size != -1) return size;

                size = 0;
                if (!getNameBytes().isEmpty()) {
                    size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, name_);
                }
                if (type_ != io.netty.example.worldclock.TestProtocol2.RichMan.CarType.AUDI.getNumber()) {
                    size += com.google.protobuf.CodedOutputStream
                            .computeEnumSize(2, type_);
                }
                size += unknownFields.getSerializedSize();
                memoizedSize = size;
                return size;
            }

            @java.lang.Override
            public boolean equals(final java.lang.Object obj) {
                if (obj == this) {
                    return true;
                }
                if (!(obj instanceof io.netty.example.worldclock.TestProtocol2.RichMan.Car)) {
                    return super.equals(obj);
                }
                io.netty.example.worldclock.TestProtocol2.RichMan.Car other = (io.netty.example.worldclock.TestProtocol2.RichMan.Car) obj;

                if (!getName()
                        .equals(other.getName())) return false;
                if (type_ != other.type_) return false;
                if (!unknownFields.equals(other.unknownFields)) return false;
                return true;
            }

            @java.lang.Override
            public int hashCode() {
                if (memoizedHashCode != 0) {
                    return memoizedHashCode;
                }
                int hash = 41;
                hash = (19 * hash) + getDescriptor().hashCode();
                hash = (37 * hash) + NAME_FIELD_NUMBER;
                hash = (53 * hash) + getName().hashCode();
                hash = (37 * hash) + TYPE_FIELD_NUMBER;
                hash = (53 * hash) + type_;
                hash = (29 * hash) + unknownFields.hashCode();
                memoizedHashCode = hash;
                return hash;
            }

            public static io.netty.example.worldclock.TestProtocol2.RichMan.Car parseFrom(
                    java.nio.ByteBuffer data)
                    throws com.google.protobuf.InvalidProtocolBufferException {
                return PARSER.parseFrom(data);
            }
            public static io.netty.example.worldclock.TestProtocol2.RichMan.Car parseFrom(
                    java.nio.ByteBuffer data,
                    com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                    throws com.google.protobuf.InvalidProtocolBufferException {
                return PARSER.parseFrom(data, extensionRegistry);
            }
            public static io.netty.example.worldclock.TestProtocol2.RichMan.Car parseFrom(
                    com.google.protobuf.ByteString data)
                    throws com.google.protobuf.InvalidProtocolBufferException {
                return PARSER.parseFrom(data);
            }
            public static io.netty.example.worldclock.TestProtocol2.RichMan.Car parseFrom(
                    com.google.protobuf.ByteString data,
                    com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                    throws com.google.protobuf.InvalidProtocolBufferException {
                return PARSER.parseFrom(data, extensionRegistry);
            }
            public static io.netty.example.worldclock.TestProtocol2.RichMan.Car parseFrom(byte[] data)
                    throws com.google.protobuf.InvalidProtocolBufferException {
                return PARSER.parseFrom(data);
            }
            public static io.netty.example.worldclock.TestProtocol2.RichMan.Car parseFrom(
                    byte[] data,
                    com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                    throws com.google.protobuf.InvalidProtocolBufferException {
                return PARSER.parseFrom(data, extensionRegistry);
            }
            public static io.netty.example.worldclock.TestProtocol2.RichMan.Car parseFrom(java.io.InputStream input)
                    throws java.io.IOException {
                return com.google.protobuf.GeneratedMessageV3
                        .parseWithIOException(PARSER, input);
            }
            public static io.netty.example.worldclock.TestProtocol2.RichMan.Car parseFrom(
                    java.io.InputStream input,
                    com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                    throws java.io.IOException {
                return com.google.protobuf.GeneratedMessageV3
                        .parseWithIOException(PARSER, input, extensionRegistry);
            }
            public static io.netty.example.worldclock.TestProtocol2.RichMan.Car parseDelimitedFrom(java.io.InputStream input)
                    throws java.io.IOException {
                return com.google.protobuf.GeneratedMessageV3
                        .parseDelimitedWithIOException(PARSER, input);
            }
            public static io.netty.example.worldclock.TestProtocol2.RichMan.Car parseDelimitedFrom(
                    java.io.InputStream input,
                    com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                    throws java.io.IOException {
                return com.google.protobuf.GeneratedMessageV3
                        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
            }
            public static io.netty.example.worldclock.TestProtocol2.RichMan.Car parseFrom(
                    com.google.protobuf.CodedInputStream input)
                    throws java.io.IOException {
                return com.google.protobuf.GeneratedMessageV3
                        .parseWithIOException(PARSER, input);
            }
            public static io.netty.example.worldclock.TestProtocol2.RichMan.Car parseFrom(
                    com.google.protobuf.CodedInputStream input,
                    com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                    throws java.io.IOException {
                return com.google.protobuf.GeneratedMessageV3
                        .parseWithIOException(PARSER, input, extensionRegistry);
            }

            @java.lang.Override
            public Builder newBuilderForType() { return newBuilder(); }
            public static Builder newBuilder() {
                return DEFAULT_INSTANCE.toBuilder();
            }
            public static Builder newBuilder(io.netty.example.worldclock.TestProtocol2.RichMan.Car prototype) {
                return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
            }
            @java.lang.Override
            public Builder toBuilder() {
                return this == DEFAULT_INSTANCE
                        ? new Builder() : new Builder().mergeFrom(this);
            }

            @java.lang.Override
            protected Builder newBuilderForType(
                    com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
                Builder builder = new Builder(parent);
                return builder;
            }
            /**
             * Protobuf type {@code io.netty.example.worldclock.RichMan.Car}
             */
            public static final class Builder extends
                    com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
                    // @@protoc_insertion_point(builder_implements:io.netty.example.worldclock.RichMan.Car)
                    io.netty.example.worldclock.TestProtocol2.RichMan.CarOrBuilder {
                public static final com.google.protobuf.Descriptors.Descriptor
                getDescriptor() {
                    return io.netty.example.worldclock.TestProtocol2.internal_static_io_netty_example_worldclock_RichMan_Car_descriptor;
                }

                @java.lang.Override
                protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
                internalGetFieldAccessorTable() {
                    return io.netty.example.worldclock.TestProtocol2.internal_static_io_netty_example_worldclock_RichMan_Car_fieldAccessorTable
                            .ensureFieldAccessorsInitialized(
                                    io.netty.example.worldclock.TestProtocol2.RichMan.Car.class, io.netty.example.worldclock.TestProtocol2.RichMan.Car.Builder.class);
                }

                // Construct using io.netty.example.worldclock.TestProtocol2.RichMan.Car.newBuilder()
                private Builder() {
                    maybeForceBuilderInitialization();
                }

                private Builder(
                        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
                    super(parent);
                    maybeForceBuilderInitialization();
                }
                private void maybeForceBuilderInitialization() {
                    if (com.google.protobuf.GeneratedMessageV3
                            .alwaysUseFieldBuilders) {
                    }
                }
                @java.lang.Override
                public Builder clear() {
                    super.clear();
                    name_ = "";

                    type_ = 0;

                    return this;
                }

                @java.lang.Override
                public com.google.protobuf.Descriptors.Descriptor
                getDescriptorForType() {
                    return io.netty.example.worldclock.TestProtocol2.internal_static_io_netty_example_worldclock_RichMan_Car_descriptor;
                }

                @java.lang.Override
                public io.netty.example.worldclock.TestProtocol2.RichMan.Car getDefaultInstanceForType() {
                    return io.netty.example.worldclock.TestProtocol2.RichMan.Car.getDefaultInstance();
                }

                @java.lang.Override
                public io.netty.example.worldclock.TestProtocol2.RichMan.Car build() {
                    io.netty.example.worldclock.TestProtocol2.RichMan.Car result = buildPartial();
                    if (!result.isInitialized()) {
                        throw newUninitializedMessageException(result);
                    }
                    return result;
                }

                @java.lang.Override
                public io.netty.example.worldclock.TestProtocol2.RichMan.Car buildPartial() {
                    io.netty.example.worldclock.TestProtocol2.RichMan.Car result = new io.netty.example.worldclock.TestProtocol2.RichMan.Car(this);
                    result.name_ = name_;
                    result.type_ = type_;
                    onBuilt();
                    return result;
                }

                @java.lang.Override
                public Builder clone() {
                    return super.clone();
                }
                @java.lang.Override
                public Builder setField(
                        com.google.protobuf.Descriptors.FieldDescriptor field,
                        java.lang.Object value) {
                    return super.setField(field, value);
                }
                @java.lang.Override
                public Builder clearField(
                        com.google.protobuf.Descriptors.FieldDescriptor field) {
                    return super.clearField(field);
                }
                @java.lang.Override
                public Builder clearOneof(
                        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
                    return super.clearOneof(oneof);
                }
                @java.lang.Override
                public Builder setRepeatedField(
                        com.google.protobuf.Descriptors.FieldDescriptor field,
                        int index, java.lang.Object value) {
                    return super.setRepeatedField(field, index, value);
                }
                @java.lang.Override
                public Builder addRepeatedField(
                        com.google.protobuf.Descriptors.FieldDescriptor field,
                        java.lang.Object value) {
                    return super.addRepeatedField(field, value);
                }
                @java.lang.Override
                public Builder mergeFrom(com.google.protobuf.Message other) {
                    if (other instanceof io.netty.example.worldclock.TestProtocol2.RichMan.Car) {
                        return mergeFrom((io.netty.example.worldclock.TestProtocol2.RichMan.Car)other);
                    } else {
                        super.mergeFrom(other);
                        return this;
                    }
                }

                public Builder mergeFrom(io.netty.example.worldclock.TestProtocol2.RichMan.Car other) {
                    if (other == io.netty.example.worldclock.TestProtocol2.RichMan.Car.getDefaultInstance()) return this;
                    if (!other.getName().isEmpty()) {
                        name_ = other.name_;
                        onChanged();
                    }
                    if (other.type_ != 0) {
                        setTypeValue(other.getTypeValue());
                    }
                    this.mergeUnknownFields(other.unknownFields);
                    onChanged();
                    return this;
                }

                @java.lang.Override
                public final boolean isInitialized() {
                    return true;
                }

                @java.lang.Override
                public Builder mergeFrom(
                        com.google.protobuf.CodedInputStream input,
                        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                        throws java.io.IOException {
                    io.netty.example.worldclock.TestProtocol2.RichMan.Car parsedMessage = null;
                    try {
                        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
                    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
                        parsedMessage = (io.netty.example.worldclock.TestProtocol2.RichMan.Car) e.getUnfinishedMessage();
                        throw e.unwrapIOException();
                    } finally {
                        if (parsedMessage != null) {
                            mergeFrom(parsedMessage);
                        }
                    }
                    return this;
                }

                private java.lang.Object name_ = "";
                /**
                 * <code>string name = 1;</code>
                 */
                public java.lang.String getName() {
                    java.lang.Object ref = name_;
                    if (!(ref instanceof java.lang.String)) {
                        com.google.protobuf.ByteString bs =
                                (com.google.protobuf.ByteString) ref;
                        java.lang.String s = bs.toStringUtf8();
                        name_ = s;
                        return s;
                    } else {
                        return (java.lang.String) ref;
                    }
                }
                /**
                 * <code>string name = 1;</code>
                 */
                public com.google.protobuf.ByteString
                getNameBytes() {
                    java.lang.Object ref = name_;
                    if (ref instanceof String) {
                        com.google.protobuf.ByteString b =
                                com.google.protobuf.ByteString.copyFromUtf8(
                                        (java.lang.String) ref);
                        name_ = b;
                        return b;
                    } else {
                        return (com.google.protobuf.ByteString) ref;
                    }
                }
                /**
                 * <code>string name = 1;</code>
                 */
                public Builder setName(
                        java.lang.String value) {
                    if (value == null) {
                        throw new NullPointerException();
                    }

                    name_ = value;
                    onChanged();
                    return this;
                }
                /**
                 * <code>string name = 1;</code>
                 */
                public Builder clearName() {

                    name_ = getDefaultInstance().getName();
                    onChanged();
                    return this;
                }
                /**
                 * <code>string name = 1;</code>
                 */
                public Builder setNameBytes(
                        com.google.protobuf.ByteString value) {
                    if (value == null) {
                        throw new NullPointerException();
                    }
                    checkByteStringIsUtf8(value);

                    name_ = value;
                    onChanged();
                    return this;
                }

                private int type_ = 0;
                /**
                 * <code>.io.netty.example.worldclock.RichMan.CarType type = 2;</code>
                 */
                public int getTypeValue() {
                    return type_;
                }
                /**
                 * <code>.io.netty.example.worldclock.RichMan.CarType type = 2;</code>
                 */
                public Builder setTypeValue(int value) {
                    type_ = value;
                    onChanged();
                    return this;
                }
                /**
                 * <code>.io.netty.example.worldclock.RichMan.CarType type = 2;</code>
                 */
                public io.netty.example.worldclock.TestProtocol2.RichMan.CarType getType() {
                    @SuppressWarnings("deprecation")
                    io.netty.example.worldclock.TestProtocol2.RichMan.CarType result = io.netty.example.worldclock.TestProtocol2.RichMan.CarType.valueOf(type_);
                    return result == null ? io.netty.example.worldclock.TestProtocol2.RichMan.CarType.UNRECOGNIZED : result;
                }
                /**
                 * <code>.io.netty.example.worldclock.RichMan.CarType type = 2;</code>
                 */
                public Builder setType(io.netty.example.worldclock.TestProtocol2.RichMan.CarType value) {
                    if (value == null) {
                        throw new NullPointerException();
                    }

                    type_ = value.getNumber();
                    onChanged();
                    return this;
                }
                /**
                 * <code>.io.netty.example.worldclock.RichMan.CarType type = 2;</code>
                 */
                public Builder clearType() {

                    type_ = 0;
                    onChanged();
                    return this;
                }
                @java.lang.Override
                public final Builder setUnknownFields(
                        final com.google.protobuf.UnknownFieldSet unknownFields) {
                    return super.setUnknownFields(unknownFields);
                }

                @java.lang.Override
                public final Builder mergeUnknownFields(
                        final com.google.protobuf.UnknownFieldSet unknownFields) {
                    return super.mergeUnknownFields(unknownFields);
                }


                // @@protoc_insertion_point(builder_scope:io.netty.example.worldclock.RichMan.Car)
            }

            // @@protoc_insertion_point(class_scope:io.netty.example.worldclock.RichMan.Car)
            private static final io.netty.example.worldclock.TestProtocol2.RichMan.Car DEFAULT_INSTANCE;
            static {
                DEFAULT_INSTANCE = new io.netty.example.worldclock.TestProtocol2.RichMan.Car();
            }

            public static io.netty.example.worldclock.TestProtocol2.RichMan.Car getDefaultInstance() {
                return DEFAULT_INSTANCE;
            }

            private static final com.google.protobuf.Parser<Car>
                    PARSER = new com.google.protobuf.AbstractParser<Car>() {
                @java.lang.Override
                public Car parsePartialFrom(
                        com.google.protobuf.CodedInputStream input,
                        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                        throws com.google.protobuf.InvalidProtocolBufferException {
                    return new Car(input, extensionRegistry);
                }
            };

            public static com.google.protobuf.Parser<Car> parser() {
                return PARSER;
            }

            @java.lang.Override
            public com.google.protobuf.Parser<Car> getParserForType() {
                return PARSER;
            }

            @java.lang.Override
            public io.netty.example.worldclock.TestProtocol2.RichMan.Car getDefaultInstanceForType() {
                return DEFAULT_INSTANCE;
            }

        }

        private int bitField0_;
        public static final int ID_FIELD_NUMBER = 1;
        private int id_;
        /**
         * <code>int32 id = 1;</code>
         */
        public int getId() {
            return id_;
        }

        public static final int NAME_FIELD_NUMBER = 2;
        private volatile java.lang.Object name_;
        /**
         * <code>string name = 2;</code>
         */
        public java.lang.String getName() {
            java.lang.Object ref = name_;
            if (ref instanceof java.lang.String) {
                return (java.lang.String) ref;
            } else {
                com.google.protobuf.ByteString bs =
                        (com.google.protobuf.ByteString) ref;
                java.lang.String s = bs.toStringUtf8();
                name_ = s;
                return s;
            }
        }
        /**
         * <code>string name = 2;</code>
         */
        public com.google.protobuf.ByteString
        getNameBytes() {
            java.lang.Object ref = name_;
            if (ref instanceof java.lang.String) {
                com.google.protobuf.ByteString b =
                        com.google.protobuf.ByteString.copyFromUtf8(
                                (java.lang.String) ref);
                name_ = b;
                return b;
            } else {
                return (com.google.protobuf.ByteString) ref;
            }
        }

        public static final int EMAIL_FIELD_NUMBER = 3;
        private volatile java.lang.Object email_;
        /**
         * <code>string email = 3;</code>
         */
        public java.lang.String getEmail() {
            java.lang.Object ref = email_;
            if (ref instanceof java.lang.String) {
                return (java.lang.String) ref;
            } else {
                com.google.protobuf.ByteString bs =
                        (com.google.protobuf.ByteString) ref;
                java.lang.String s = bs.toStringUtf8();
                email_ = s;
                return s;
            }
        }
        /**
         * <code>string email = 3;</code>
         */
        public com.google.protobuf.ByteString
        getEmailBytes() {
            java.lang.Object ref = email_;
            if (ref instanceof java.lang.String) {
                com.google.protobuf.ByteString b =
                        com.google.protobuf.ByteString.copyFromUtf8(
                                (java.lang.String) ref);
                email_ = b;
                return b;
            } else {
                return (com.google.protobuf.ByteString) ref;
            }
        }

        public static final int CARS_FIELD_NUMBER = 4;
        private java.util.List<io.netty.example.worldclock.TestProtocol2.RichMan.Car> cars_;
        /**
         * <code>repeated .io.netty.example.worldclock.RichMan.Car cars = 4;</code>
         */
        public java.util.List<io.netty.example.worldclock.TestProtocol2.RichMan.Car> getCarsList() {
            return cars_;
        }
        /**
         * <code>repeated .io.netty.example.worldclock.RichMan.Car cars = 4;</code>
         */
        public java.util.List<? extends io.netty.example.worldclock.TestProtocol2.RichMan.CarOrBuilder>
        getCarsOrBuilderList() {
            return cars_;
        }
        /**
         * <code>repeated .io.netty.example.worldclock.RichMan.Car cars = 4;</code>
         */
        public int getCarsCount() {
            return cars_.size();
        }
        /**
         * <code>repeated .io.netty.example.worldclock.RichMan.Car cars = 4;</code>
         */
        public io.netty.example.worldclock.TestProtocol2.RichMan.Car getCars(int index) {
            return cars_.get(index);
        }
        /**
         * <code>repeated .io.netty.example.worldclock.RichMan.Car cars = 4;</code>
         */
        public io.netty.example.worldclock.TestProtocol2.RichMan.CarOrBuilder getCarsOrBuilder(
                int index) {
            return cars_.get(index);
        }

        private byte memoizedIsInitialized = -1;
        @java.lang.Override
        public final boolean isInitialized() {
            byte isInitialized = memoizedIsInitialized;
            if (isInitialized == 1) return true;
            if (isInitialized == 0) return false;

            memoizedIsInitialized = 1;
            return true;
        }

        @java.lang.Override
        public void writeTo(com.google.protobuf.CodedOutputStream output)
                throws java.io.IOException {
            if (id_ != 0) {
                output.writeInt32(1, id_);
            }
            if (!getNameBytes().isEmpty()) {
                com.google.protobuf.GeneratedMessageV3.writeString(output, 2, name_);
            }
            if (!getEmailBytes().isEmpty()) {
                com.google.protobuf.GeneratedMessageV3.writeString(output, 3, email_);
            }
            for (int i = 0; i < cars_.size(); i++) {
                output.writeMessage(4, cars_.get(i));
            }
            unknownFields.writeTo(output);
        }

        @java.lang.Override
        public int getSerializedSize() {
            int size = memoizedSize;
            if (size != -1) return size;

            size = 0;
            if (id_ != 0) {
                size += com.google.protobuf.CodedOutputStream
                        .computeInt32Size(1, id_);
            }
            if (!getNameBytes().isEmpty()) {
                size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, name_);
            }
            if (!getEmailBytes().isEmpty()) {
                size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, email_);
            }
            for (int i = 0; i < cars_.size(); i++) {
                size += com.google.protobuf.CodedOutputStream
                        .computeMessageSize(4, cars_.get(i));
            }
            size += unknownFields.getSerializedSize();
            memoizedSize = size;
            return size;
        }

        @java.lang.Override
        public boolean equals(final java.lang.Object obj) {
            if (obj == this) {
                return true;
            }
            if (!(obj instanceof io.netty.example.worldclock.TestProtocol2.RichMan)) {
                return super.equals(obj);
            }
            io.netty.example.worldclock.TestProtocol2.RichMan other = (io.netty.example.worldclock.TestProtocol2.RichMan) obj;

            if (getId()
                    != other.getId()) return false;
            if (!getName()
                    .equals(other.getName())) return false;
            if (!getEmail()
                    .equals(other.getEmail())) return false;
            if (!getCarsList()
                    .equals(other.getCarsList())) return false;
            if (!unknownFields.equals(other.unknownFields)) return false;
            return true;
        }

        @java.lang.Override
        public int hashCode() {
            if (memoizedHashCode != 0) {
                return memoizedHashCode;
            }
            int hash = 41;
            hash = (19 * hash) + getDescriptor().hashCode();
            hash = (37 * hash) + ID_FIELD_NUMBER;
            hash = (53 * hash) + getId();
            hash = (37 * hash) + NAME_FIELD_NUMBER;
            hash = (53 * hash) + getName().hashCode();
            hash = (37 * hash) + EMAIL_FIELD_NUMBER;
            hash = (53 * hash) + getEmail().hashCode();
            if (getCarsCount() > 0) {
                hash = (37 * hash) + CARS_FIELD_NUMBER;
                hash = (53 * hash) + getCarsList().hashCode();
            }
            hash = (29 * hash) + unknownFields.hashCode();
            memoizedHashCode = hash;
            return hash;
        }

        public static io.netty.example.worldclock.TestProtocol2.RichMan parseFrom(
                java.nio.ByteBuffer data)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data);
        }
        public static io.netty.example.worldclock.TestProtocol2.RichMan parseFrom(
                java.nio.ByteBuffer data,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data, extensionRegistry);
        }
        public static io.netty.example.worldclock.TestProtocol2.RichMan parseFrom(
                com.google.protobuf.ByteString data)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data);
        }
        public static io.netty.example.worldclock.TestProtocol2.RichMan parseFrom(
                com.google.protobuf.ByteString data,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data, extensionRegistry);
        }
        public static io.netty.example.worldclock.TestProtocol2.RichMan parseFrom(byte[] data)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data);
        }
        public static io.netty.example.worldclock.TestProtocol2.RichMan parseFrom(
                byte[] data,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data, extensionRegistry);
        }
        public static io.netty.example.worldclock.TestProtocol2.RichMan parseFrom(java.io.InputStream input)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseWithIOException(PARSER, input);
        }
        public static io.netty.example.worldclock.TestProtocol2.RichMan parseFrom(
                java.io.InputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseWithIOException(PARSER, input, extensionRegistry);
        }
        public static io.netty.example.worldclock.TestProtocol2.RichMan parseDelimitedFrom(java.io.InputStream input)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseDelimitedWithIOException(PARSER, input);
        }
        public static io.netty.example.worldclock.TestProtocol2.RichMan parseDelimitedFrom(
                java.io.InputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
        }
        public static io.netty.example.worldclock.TestProtocol2.RichMan parseFrom(
                com.google.protobuf.CodedInputStream input)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseWithIOException(PARSER, input);
        }
        public static io.netty.example.worldclock.TestProtocol2.RichMan parseFrom(
                com.google.protobuf.CodedInputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseWithIOException(PARSER, input, extensionRegistry);
        }

        @java.lang.Override
        public Builder newBuilderForType() { return newBuilder(); }
        public static Builder newBuilder() {
            return DEFAULT_INSTANCE.toBuilder();
        }
        public static Builder newBuilder(io.netty.example.worldclock.TestProtocol2.RichMan prototype) {
            return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
        }
        @java.lang.Override
        public Builder toBuilder() {
            return this == DEFAULT_INSTANCE
                    ? new Builder() : new Builder().mergeFrom(this);
        }

        @java.lang.Override
        protected Builder newBuilderForType(
                com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
            Builder builder = new Builder(parent);
            return builder;
        }
        /**
         * Protobuf type {@code io.netty.example.worldclock.RichMan}
         */
        public static final class Builder extends
                com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
                // @@protoc_insertion_point(builder_implements:io.netty.example.worldclock.RichMan)
                io.netty.example.worldclock.TestProtocol2.RichManOrBuilder {
            public static final com.google.protobuf.Descriptors.Descriptor
            getDescriptor() {
                return io.netty.example.worldclock.TestProtocol2.internal_static_io_netty_example_worldclock_RichMan_descriptor;
            }

            @java.lang.Override
            protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
            internalGetFieldAccessorTable() {
                return io.netty.example.worldclock.TestProtocol2.internal_static_io_netty_example_worldclock_RichMan_fieldAccessorTable
                        .ensureFieldAccessorsInitialized(
                                io.netty.example.worldclock.TestProtocol2.RichMan.class, io.netty.example.worldclock.TestProtocol2.RichMan.Builder.class);
            }

            // Construct using io.netty.example.worldclock.TestProtocol2.RichMan.newBuilder()
            private Builder() {
                maybeForceBuilderInitialization();
            }

            private Builder(
                    com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
                super(parent);
                maybeForceBuilderInitialization();
            }
            private void maybeForceBuilderInitialization() {
                if (com.google.protobuf.GeneratedMessageV3
                        .alwaysUseFieldBuilders) {
                    getCarsFieldBuilder();
                }
            }
            @java.lang.Override
            public Builder clear() {
                super.clear();
                id_ = 0;

                name_ = "";

                email_ = "";

                if (carsBuilder_ == null) {
                    cars_ = java.util.Collections.emptyList();
                    bitField0_ = (bitField0_ & ~0x00000008);
                } else {
                    carsBuilder_.clear();
                }
                return this;
            }

            @java.lang.Override
            public com.google.protobuf.Descriptors.Descriptor
            getDescriptorForType() {
                return io.netty.example.worldclock.TestProtocol2.internal_static_io_netty_example_worldclock_RichMan_descriptor;
            }

            @java.lang.Override
            public io.netty.example.worldclock.TestProtocol2.RichMan getDefaultInstanceForType() {
                return io.netty.example.worldclock.TestProtocol2.RichMan.getDefaultInstance();
            }

            @java.lang.Override
            public io.netty.example.worldclock.TestProtocol2.RichMan build() {
                io.netty.example.worldclock.TestProtocol2.RichMan result = buildPartial();
                if (!result.isInitialized()) {
                    throw newUninitializedMessageException(result);
                }
                return result;
            }

            @java.lang.Override
            public io.netty.example.worldclock.TestProtocol2.RichMan buildPartial() {
                io.netty.example.worldclock.TestProtocol2.RichMan result = new io.netty.example.worldclock.TestProtocol2.RichMan(this);
                int from_bitField0_ = bitField0_;
                int to_bitField0_ = 0;
                result.id_ = id_;
                result.name_ = name_;
                result.email_ = email_;
                if (carsBuilder_ == null) {
                    if (((bitField0_ & 0x00000008) != 0)) {
                        cars_ = java.util.Collections.unmodifiableList(cars_);
                        bitField0_ = (bitField0_ & ~0x00000008);
                    }
                    result.cars_ = cars_;
                } else {
                    result.cars_ = carsBuilder_.build();
                }
                result.bitField0_ = to_bitField0_;
                onBuilt();
                return result;
            }

            @java.lang.Override
            public Builder clone() {
                return super.clone();
            }
            @java.lang.Override
            public Builder setField(
                    com.google.protobuf.Descriptors.FieldDescriptor field,
                    java.lang.Object value) {
                return super.setField(field, value);
            }
            @java.lang.Override
            public Builder clearField(
                    com.google.protobuf.Descriptors.FieldDescriptor field) {
                return super.clearField(field);
            }
            @java.lang.Override
            public Builder clearOneof(
                    com.google.protobuf.Descriptors.OneofDescriptor oneof) {
                return super.clearOneof(oneof);
            }
            @java.lang.Override
            public Builder setRepeatedField(
                    com.google.protobuf.Descriptors.FieldDescriptor field,
                    int index, java.lang.Object value) {
                return super.setRepeatedField(field, index, value);
            }
            @java.lang.Override
            public Builder addRepeatedField(
                    com.google.protobuf.Descriptors.FieldDescriptor field,
                    java.lang.Object value) {
                return super.addRepeatedField(field, value);
            }
            @java.lang.Override
            public Builder mergeFrom(com.google.protobuf.Message other) {
                if (other instanceof io.netty.example.worldclock.TestProtocol2.RichMan) {
                    return mergeFrom((io.netty.example.worldclock.TestProtocol2.RichMan)other);
                } else {
                    super.mergeFrom(other);
                    return this;
                }
            }

            public Builder mergeFrom(io.netty.example.worldclock.TestProtocol2.RichMan other) {
                if (other == io.netty.example.worldclock.TestProtocol2.RichMan.getDefaultInstance()) return this;
                if (other.getId() != 0) {
                    setId(other.getId());
                }
                if (!other.getName().isEmpty()) {
                    name_ = other.name_;
                    onChanged();
                }
                if (!other.getEmail().isEmpty()) {
                    email_ = other.email_;
                    onChanged();
                }
                if (carsBuilder_ == null) {
                    if (!other.cars_.isEmpty()) {
                        if (cars_.isEmpty()) {
                            cars_ = other.cars_;
                            bitField0_ = (bitField0_ & ~0x00000008);
                        } else {
                            ensureCarsIsMutable();
                            cars_.addAll(other.cars_);
                        }
                        onChanged();
                    }
                } else {
                    if (!other.cars_.isEmpty()) {
                        if (carsBuilder_.isEmpty()) {
                            carsBuilder_.dispose();
                            carsBuilder_ = null;
                            cars_ = other.cars_;
                            bitField0_ = (bitField0_ & ~0x00000008);
                            carsBuilder_ =
                                    com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                                            getCarsFieldBuilder() : null;
                        } else {
                            carsBuilder_.addAllMessages(other.cars_);
                        }
                    }
                }
                this.mergeUnknownFields(other.unknownFields);
                onChanged();
                return this;
            }

            @java.lang.Override
            public final boolean isInitialized() {
                return true;
            }

            @java.lang.Override
            public Builder mergeFrom(
                    com.google.protobuf.CodedInputStream input,
                    com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                    throws java.io.IOException {
                io.netty.example.worldclock.TestProtocol2.RichMan parsedMessage = null;
                try {
                    parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
                } catch (com.google.protobuf.InvalidProtocolBufferException e) {
                    parsedMessage = (io.netty.example.worldclock.TestProtocol2.RichMan) e.getUnfinishedMessage();
                    throw e.unwrapIOException();
                } finally {
                    if (parsedMessage != null) {
                        mergeFrom(parsedMessage);
                    }
                }
                return this;
            }
            private int bitField0_;

            private int id_ ;
            /**
             * <code>int32 id = 1;</code>
             */
            public int getId() {
                return id_;
            }
            /**
             * <code>int32 id = 1;</code>
             */
            public Builder setId(int value) {

                id_ = value;
                onChanged();
                return this;
            }
            /**
             * <code>int32 id = 1;</code>
             */
            public Builder clearId() {

                id_ = 0;
                onChanged();
                return this;
            }

            private java.lang.Object name_ = "";
            /**
             * <code>string name = 2;</code>
             */
            public java.lang.String getName() {
                java.lang.Object ref = name_;
                if (!(ref instanceof java.lang.String)) {
                    com.google.protobuf.ByteString bs =
                            (com.google.protobuf.ByteString) ref;
                    java.lang.String s = bs.toStringUtf8();
                    name_ = s;
                    return s;
                } else {
                    return (java.lang.String) ref;
                }
            }
            /**
             * <code>string name = 2;</code>
             */
            public com.google.protobuf.ByteString
            getNameBytes() {
                java.lang.Object ref = name_;
                if (ref instanceof String) {
                    com.google.protobuf.ByteString b =
                            com.google.protobuf.ByteString.copyFromUtf8(
                                    (java.lang.String) ref);
                    name_ = b;
                    return b;
                } else {
                    return (com.google.protobuf.ByteString) ref;
                }
            }
            /**
             * <code>string name = 2;</code>
             */
            public Builder setName(
                    java.lang.String value) {
                if (value == null) {
                    throw new NullPointerException();
                }

                name_ = value;
                onChanged();
                return this;
            }
            /**
             * <code>string name = 2;</code>
             */
            public Builder clearName() {

                name_ = getDefaultInstance().getName();
                onChanged();
                return this;
            }
            /**
             * <code>string name = 2;</code>
             */
            public Builder setNameBytes(
                    com.google.protobuf.ByteString value) {
                if (value == null) {
                    throw new NullPointerException();
                }
                checkByteStringIsUtf8(value);

                name_ = value;
                onChanged();
                return this;
            }

            private java.lang.Object email_ = "";
            /**
             * <code>string email = 3;</code>
             */
            public java.lang.String getEmail() {
                java.lang.Object ref = email_;
                if (!(ref instanceof java.lang.String)) {
                    com.google.protobuf.ByteString bs =
                            (com.google.protobuf.ByteString) ref;
                    java.lang.String s = bs.toStringUtf8();
                    email_ = s;
                    return s;
                } else {
                    return (java.lang.String) ref;
                }
            }
            /**
             * <code>string email = 3;</code>
             */
            public com.google.protobuf.ByteString
            getEmailBytes() {
                java.lang.Object ref = email_;
                if (ref instanceof String) {
                    com.google.protobuf.ByteString b =
                            com.google.protobuf.ByteString.copyFromUtf8(
                                    (java.lang.String) ref);
                    email_ = b;
                    return b;
                } else {
                    return (com.google.protobuf.ByteString) ref;
                }
            }
            /**
             * <code>string email = 3;</code>
             */
            public Builder setEmail(
                    java.lang.String value) {
                if (value == null) {
                    throw new NullPointerException();
                }

                email_ = value;
                onChanged();
                return this;
            }
            /**
             * <code>string email = 3;</code>
             */
            public Builder clearEmail() {

                email_ = getDefaultInstance().getEmail();
                onChanged();
                return this;
            }
            /**
             * <code>string email = 3;</code>
             */
            public Builder setEmailBytes(
                    com.google.protobuf.ByteString value) {
                if (value == null) {
                    throw new NullPointerException();
                }
                checkByteStringIsUtf8(value);

                email_ = value;
                onChanged();
                return this;
            }

            private java.util.List<io.netty.example.worldclock.TestProtocol2.RichMan.Car> cars_ =
                    java.util.Collections.emptyList();
            private void ensureCarsIsMutable() {
                if (!((bitField0_ & 0x00000008) != 0)) {
                    cars_ = new java.util.ArrayList<io.netty.example.worldclock.TestProtocol2.RichMan.Car>(cars_);
                    bitField0_ |= 0x00000008;
                }
            }

            private com.google.protobuf.RepeatedFieldBuilderV3<
                    io.netty.example.worldclock.TestProtocol2.RichMan.Car, io.netty.example.worldclock.TestProtocol2.RichMan.Car.Builder, io.netty.example.worldclock.TestProtocol2.RichMan.CarOrBuilder> carsBuilder_;

            /**
             * <code>repeated .io.netty.example.worldclock.RichMan.Car cars = 4;</code>
             */
            public java.util.List<io.netty.example.worldclock.TestProtocol2.RichMan.Car> getCarsList() {
                if (carsBuilder_ == null) {
                    return java.util.Collections.unmodifiableList(cars_);
                } else {
                    return carsBuilder_.getMessageList();
                }
            }
            /**
             * <code>repeated .io.netty.example.worldclock.RichMan.Car cars = 4;</code>
             */
            public int getCarsCount() {
                if (carsBuilder_ == null) {
                    return cars_.size();
                } else {
                    return carsBuilder_.getCount();
                }
            }
            /**
             * <code>repeated .io.netty.example.worldclock.RichMan.Car cars = 4;</code>
             */
            public io.netty.example.worldclock.TestProtocol2.RichMan.Car getCars(int index) {
                if (carsBuilder_ == null) {
                    return cars_.get(index);
                } else {
                    return carsBuilder_.getMessage(index);
                }
            }
            /**
             * <code>repeated .io.netty.example.worldclock.RichMan.Car cars = 4;</code>
             */
            public Builder setCars(
                    int index, io.netty.example.worldclock.TestProtocol2.RichMan.Car value) {
                if (carsBuilder_ == null) {
                    if (value == null) {
                        throw new NullPointerException();
                    }
                    ensureCarsIsMutable();
                    cars_.set(index, value);
                    onChanged();
                } else {
                    carsBuilder_.setMessage(index, value);
                }
                return this;
            }
            /**
             * <code>repeated .io.netty.example.worldclock.RichMan.Car cars = 4;</code>
             */
            public Builder setCars(
                    int index, io.netty.example.worldclock.TestProtocol2.RichMan.Car.Builder builderForValue) {
                if (carsBuilder_ == null) {
                    ensureCarsIsMutable();
                    cars_.set(index, builderForValue.build());
                    onChanged();
                } else {
                    carsBuilder_.setMessage(index, builderForValue.build());
                }
                return this;
            }
            /**
             * <code>repeated .io.netty.example.worldclock.RichMan.Car cars = 4;</code>
             */
            public Builder addCars(io.netty.example.worldclock.TestProtocol2.RichMan.Car value) {
                if (carsBuilder_ == null) {
                    if (value == null) {
                        throw new NullPointerException();
                    }
                    ensureCarsIsMutable();
                    cars_.add(value);
                    onChanged();
                } else {
                    carsBuilder_.addMessage(value);
                }
                return this;
            }
            /**
             * <code>repeated .io.netty.example.worldclock.RichMan.Car cars = 4;</code>
             */
            public Builder addCars(
                    int index, io.netty.example.worldclock.TestProtocol2.RichMan.Car value) {
                if (carsBuilder_ == null) {
                    if (value == null) {
                        throw new NullPointerException();
                    }
                    ensureCarsIsMutable();
                    cars_.add(index, value);
                    onChanged();
                } else {
                    carsBuilder_.addMessage(index, value);
                }
                return this;
            }
            /**
             * <code>repeated .io.netty.example.worldclock.RichMan.Car cars = 4;</code>
             */
            public Builder addCars(
                    io.netty.example.worldclock.TestProtocol2.RichMan.Car.Builder builderForValue) {
                if (carsBuilder_ == null) {
                    ensureCarsIsMutable();
                    cars_.add(builderForValue.build());
                    onChanged();
                } else {
                    carsBuilder_.addMessage(builderForValue.build());
                }
                return this;
            }
            /**
             * <code>repeated .io.netty.example.worldclock.RichMan.Car cars = 4;</code>
             */
            public Builder addCars(
                    int index, io.netty.example.worldclock.TestProtocol2.RichMan.Car.Builder builderForValue) {
                if (carsBuilder_ == null) {
                    ensureCarsIsMutable();
                    cars_.add(index, builderForValue.build());
                    onChanged();
                } else {
                    carsBuilder_.addMessage(index, builderForValue.build());
                }
                return this;
            }
            /**
             * <code>repeated .io.netty.example.worldclock.RichMan.Car cars = 4;</code>
             */
            public Builder addAllCars(
                    java.lang.Iterable<? extends io.netty.example.worldclock.TestProtocol2.RichMan.Car> values) {
                if (carsBuilder_ == null) {
                    ensureCarsIsMutable();
                    com.google.protobuf.AbstractMessageLite.Builder.addAll(
                            values, cars_);
                    onChanged();
                } else {
                    carsBuilder_.addAllMessages(values);
                }
                return this;
            }
            /**
             * <code>repeated .io.netty.example.worldclock.RichMan.Car cars = 4;</code>
             */
            public Builder clearCars() {
                if (carsBuilder_ == null) {
                    cars_ = java.util.Collections.emptyList();
                    bitField0_ = (bitField0_ & ~0x00000008);
                    onChanged();
                } else {
                    carsBuilder_.clear();
                }
                return this;
            }
            /**
             * <code>repeated .io.netty.example.worldclock.RichMan.Car cars = 4;</code>
             */
            public Builder removeCars(int index) {
                if (carsBuilder_ == null) {
                    ensureCarsIsMutable();
                    cars_.remove(index);
                    onChanged();
                } else {
                    carsBuilder_.remove(index);
                }
                return this;
            }
            /**
             * <code>repeated .io.netty.example.worldclock.RichMan.Car cars = 4;</code>
             */
            public io.netty.example.worldclock.TestProtocol2.RichMan.Car.Builder getCarsBuilder(
                    int index) {
                return getCarsFieldBuilder().getBuilder(index);
            }
            /**
             * <code>repeated .io.netty.example.worldclock.RichMan.Car cars = 4;</code>
             */
            public io.netty.example.worldclock.TestProtocol2.RichMan.CarOrBuilder getCarsOrBuilder(
                    int index) {
                if (carsBuilder_ == null) {
                    return cars_.get(index);  } else {
                    return carsBuilder_.getMessageOrBuilder(index);
                }
            }
            /**
             * <code>repeated .io.netty.example.worldclock.RichMan.Car cars = 4;</code>
             */
            public java.util.List<? extends io.netty.example.worldclock.TestProtocol2.RichMan.CarOrBuilder>
            getCarsOrBuilderList() {
                if (carsBuilder_ != null) {
                    return carsBuilder_.getMessageOrBuilderList();
                } else {
                    return java.util.Collections.unmodifiableList(cars_);
                }
            }
            /**
             * <code>repeated .io.netty.example.worldclock.RichMan.Car cars = 4;</code>
             */
            public io.netty.example.worldclock.TestProtocol2.RichMan.Car.Builder addCarsBuilder() {
                return getCarsFieldBuilder().addBuilder(
                        io.netty.example.worldclock.TestProtocol2.RichMan.Car.getDefaultInstance());
            }
            /**
             * <code>repeated .io.netty.example.worldclock.RichMan.Car cars = 4;</code>
             */
            public io.netty.example.worldclock.TestProtocol2.RichMan.Car.Builder addCarsBuilder(
                    int index) {
                return getCarsFieldBuilder().addBuilder(
                        index, io.netty.example.worldclock.TestProtocol2.RichMan.Car.getDefaultInstance());
            }
            /**
             * <code>repeated .io.netty.example.worldclock.RichMan.Car cars = 4;</code>
             */
            public java.util.List<io.netty.example.worldclock.TestProtocol2.RichMan.Car.Builder>
            getCarsBuilderList() {
                return getCarsFieldBuilder().getBuilderList();
            }
            private com.google.protobuf.RepeatedFieldBuilderV3<
                    io.netty.example.worldclock.TestProtocol2.RichMan.Car, io.netty.example.worldclock.TestProtocol2.RichMan.Car.Builder, io.netty.example.worldclock.TestProtocol2.RichMan.CarOrBuilder>
            getCarsFieldBuilder() {
                if (carsBuilder_ == null) {
                    carsBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
                            io.netty.example.worldclock.TestProtocol2.RichMan.Car, io.netty.example.worldclock.TestProtocol2.RichMan.Car.Builder, io.netty.example.worldclock.TestProtocol2.RichMan.CarOrBuilder>(
                            cars_,
                            ((bitField0_ & 0x00000008) != 0),
                            getParentForChildren(),
                            isClean());
                    cars_ = null;
                }
                return carsBuilder_;
            }
            @java.lang.Override
            public final Builder setUnknownFields(
                    final com.google.protobuf.UnknownFieldSet unknownFields) {
                return super.setUnknownFields(unknownFields);
            }

            @java.lang.Override
            public final Builder mergeUnknownFields(
                    final com.google.protobuf.UnknownFieldSet unknownFields) {
                return super.mergeUnknownFields(unknownFields);
            }


            // @@protoc_insertion_point(builder_scope:io.netty.example.worldclock.RichMan)
        }

        // @@protoc_insertion_point(class_scope:io.netty.example.worldclock.RichMan)
        private static final io.netty.example.worldclock.TestProtocol2.RichMan DEFAULT_INSTANCE;
        static {
            DEFAULT_INSTANCE = new io.netty.example.worldclock.TestProtocol2.RichMan();
        }

        public static io.netty.example.worldclock.TestProtocol2.RichMan getDefaultInstance() {
            return DEFAULT_INSTANCE;
        }

        private static final com.google.protobuf.Parser<RichMan>
                PARSER = new com.google.protobuf.AbstractParser<RichMan>() {
            @java.lang.Override
            public RichMan parsePartialFrom(
                    com.google.protobuf.CodedInputStream input,
                    com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                    throws com.google.protobuf.InvalidProtocolBufferException {
                return new RichMan(input, extensionRegistry);
            }
        };

        public static com.google.protobuf.Parser<RichMan> parser() {
            return PARSER;
        }

        @java.lang.Override
        public com.google.protobuf.Parser<RichMan> getParserForType() {
            return PARSER;
        }

        @java.lang.Override
        public io.netty.example.worldclock.TestProtocol2.RichMan getDefaultInstanceForType() {
            return DEFAULT_INSTANCE;
        }

    }

    private static final com.google.protobuf.Descriptors.Descriptor
            internal_static_io_netty_example_worldclock_RichMan_descriptor;
    private static final
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
            internal_static_io_netty_example_worldclock_RichMan_fieldAccessorTable;
    private static final com.google.protobuf.Descriptors.Descriptor
            internal_static_io_netty_example_worldclock_RichMan_Car_descriptor;
    private static final
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
            internal_static_io_netty_example_worldclock_RichMan_Car_fieldAccessorTable;

    public static com.google.protobuf.Descriptors.FileDescriptor
    getDescriptor() {
        return descriptor;
    }
    private static  com.google.protobuf.Descriptors.FileDescriptor
            descriptor;
    static {
        java.lang.String[] descriptorData = {
                "\n\023TestProtocol2.proto\022\033io.netty.example." +
                        "worldclock\"\370\001\n\007RichMan\022\n\n\002id\030\001 \001(\005\022\014\n\004na" +
                        "me\030\002 \001(\t\022\r\n\005email\030\003 \001(\t\0226\n\004cars\030\004 \003(\0132(." +
                        "io.netty.example.worldclock.RichMan.Car\032" +
                        "O\n\003Car\022\014\n\004name\030\001 \001(\t\022:\n\004type\030\002 \001(\0162,.io." +
                        "netty.example.worldclock.RichMan.CarType" +
                        "\";\n\007CarType\022\010\n\004AUDI\020\000\022\010\n\004BENZ\020\001\022\017\n\013LAMBO" +
                        "RGHINI\020\002\022\013\n\007DASAUTO\020\003b\006proto3"
        };
        com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
                new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
                    public com.google.protobuf.ExtensionRegistry assignDescriptors(
                            com.google.protobuf.Descriptors.FileDescriptor root) {
                        descriptor = root;
                        return null;
                    }
                };
        com.google.protobuf.Descriptors.FileDescriptor
                .internalBuildGeneratedFileFrom(descriptorData,
                        new com.google.protobuf.Descriptors.FileDescriptor[] {
                        }, assigner);
        internal_static_io_netty_example_worldclock_RichMan_descriptor =
                getDescriptor().getMessageTypes().get(0);
        internal_static_io_netty_example_worldclock_RichMan_fieldAccessorTable = new
                com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
                internal_static_io_netty_example_worldclock_RichMan_descriptor,
                new java.lang.String[] { "Id", "Name", "Email", "Cars", });
        internal_static_io_netty_example_worldclock_RichMan_Car_descriptor =
                internal_static_io_netty_example_worldclock_RichMan_descriptor.getNestedTypes().get(0);
        internal_static_io_netty_example_worldclock_RichMan_Car_fieldAccessorTable = new
                com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
                internal_static_io_netty_example_worldclock_RichMan_Car_descriptor,
                new java.lang.String[] { "Name", "Type", });
    }

    // @@protoc_insertion_point(outer_class_scope)
}
